const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const crypto=require('node:crypto');
const AdmZip=require('adm-zip');
const {AmbientPackService}=require('../src/ambient-packs.cjs');
const {validatePack,validateDistribution,PACK_IDS,RELEASE_BASE,REMOTE_MANIFEST_URL}=require('../src/ambient-schema.cjs');
const {migrate}=require('../src/ambient-model.js');
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
function fixture(version=1,{wrongHash=false,extra=false,traversal=false}={}){
  const audio=crypto.randomBytes(5000);audio[0]=version;const sound={id:'rain.light',name:'Chuva leve',category:'Chuva',file:'audio/rain.light.opus',duration:20,loop:true,defaultVolume:60,tags:['chuva'],source:'Nature/file.wav',sha256:wrongHash?'0'.repeat(64):hash(audio),bytes:audio.length};
  const pack={schemaVersion:1,id:'ambient-essentials',name:'Ambient Essentials',version,description:'Chuva',license:'CC0',sounds:[sound]};const zip=new AdmZip();zip.addFile('manifest.json',Buffer.from(JSON.stringify(pack)));zip.addFile(sound.file,audio);if(extra)zip.addFile('evil.exe',Buffer.from('x'));if(traversal)zip.addFile('../escape.opus',Buffer.from('x'));return {zip:zip.toBuffer(),pack};
}
function setup({version=1,fixtureOptions={},fetchError=null,bytes=null,progress=()=>{}}={}){
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ntc-ambient-test-'));const file=path.join(root,'catalog.json'),actual=bytes||fixture(version,fixtureOptions).zip;
  const packs=PACK_IDS.map(id=>({id,name:id,description:id,version:id==='ambient-essentials'?version:1,bytes:id==='ambient-essentials'?actual.length:1500,installedBytes:1500,sha256:id==='ambient-essentials'?hash(actual):'1'.repeat(64),url:`${RELEASE_BASE}/ntc-${id}-v${id==='ambient-essentials'?version:1}.zip`}));
  fs.writeFileSync(file,JSON.stringify({schemaVersion:1,packs}));const fetchImpl=async url=>{if(fetchError)throw fetchError;if(url===REMOTE_MANIFEST_URL)return {ok:true,text:async()=>fs.readFileSync(file,'utf8')};return {ok:true,body:{async *[Symbol.asyncIterator](){yield actual;}}};};
  const service=new AmbientPackService({root,catalogFile:file,fetchImpl,onProgress:progress});return {service,root,file,cleanup:()=>fs.rmSync(root,{recursive:true,force:true})};
}
test('manifest/schema e IDs duplicados',()=>{const {pack}=fixture();assert.equal(validatePack(pack),pack);assert.throws(()=>validatePack({...pack,license:'private'}));assert.throws(()=>validatePack({...pack,sounds:[...pack.sounds,pack.sounds[0]]}));assert.throws(()=>validatePack({...pack,sounds:[{...pack.sounds[0],file:'../file.opus'}]}));});
test('catálogo só aceita URLs oficiais e tamanhos/hashes válidos',()=>{const f=setup();try{const value=JSON.parse(fs.readFileSync(f.file));assert.equal(validateDistribution(value),value);value.packs[0].url='https://example.com/x';assert.throws(()=>validateDistribution(value));}finally{f.cleanup();}});
test('disponível, não instalado, instalação, leitura e remoção',async()=>{const f=setup();try{let state=await f.service.initialize();assert.equal(state.packs.length,3);assert.deepEqual(state.installed,{});state=await f.service.download('ambient-essentials');assert.equal(state.installed['ambient-essentials'].version,1);assert.equal((await f.service.audio('rain.light')).length,5000);state=await f.service.remove('ambient-essentials');assert.deepEqual(state.installed,{});await assert.rejects(f.service.audio('rain.light'));}finally{f.cleanup();}});
test('SHA incorreto rejeita sem instalar',async()=>{const f=setup();try{await f.service.initialize();const value=JSON.parse(fs.readFileSync(f.file));value.packs[0].sha256='0'.repeat(64);fs.writeFileSync(f.file,JSON.stringify(value));await assert.rejects(f.service.download('ambient-essentials'),/integridade/);assert.deepEqual((await f.service.state()).installed,{});}finally{f.cleanup();}});
test('download parcial rejeita',async()=>{const f=setup();try{const value=JSON.parse(fs.readFileSync(f.file));value.packs[0].bytes+=10;fs.writeFileSync(f.file,JSON.stringify(value));await assert.rejects(f.service.download('ambient-essentials'),/integridade/);}finally{f.cleanup();}});
test('áudio interno adulterado rejeita',async()=>{const f=setup({fixtureOptions:{wrongHash:true}});try{await assert.rejects(f.service.download('ambient-essentials'),/corrompido/);assert.deepEqual((await f.service.state()).installed,{});}finally{f.cleanup();}});
test('arquivo inesperado e traversal rejeitados',async()=>{for(const opts of [{extra:true},{traversal:true}]){const f=setup({fixtureOptions:opts});try{await assert.rejects(f.service.download('ambient-essentials'),/Estrutura/);assert.deepEqual((await f.service.state()).installed,{});}finally{f.cleanup();}}});
test('cancelamento limpa job e permite retry',async()=>{let service;const f=setup({progress:message=>{if(message.status==='baixando')service.cancel('ambient-essentials');}});service=f.service;try{await assert.rejects(service.download('ambient-essentials'),/cancelado/i);assert.deepEqual((await service.state()).installed,{});service.onProgress=()=>{};assert.ok((await service.download('ambient-essentials')).installed['ambient-essentials']);}finally{f.cleanup();}});
test('falha de rede e offline preservam instalado',async()=>{const f=setup();try{await f.service.download('ambient-essentials');f.service.fetch=async()=>{throw new Error('offline');};const result=await f.service.refresh();assert.equal(result.online,false);assert.ok((await f.service.state()).installed['ambient-essentials']);await assert.rejects(f.service.download('nature'),/offline/);}finally{f.cleanup();}});
test('atualização v2 mantém v1 em falha e instala v2 válida',async()=>{const f=setup();try{await f.service.download('ambient-essentials');let next=fixture(2,{wrongHash:true}).zip;let value=JSON.parse(fs.readFileSync(f.file));value.packs[0]={...value.packs[0],version:2,bytes:next.length,sha256:hash(next),url:`${RELEASE_BASE}/ntc-ambient-essentials-v2.zip`};fs.writeFileSync(f.file,JSON.stringify(value));f.service.fetch=async()=>({ok:true,body:{async *[Symbol.asyncIterator](){yield next;}}});await assert.rejects(f.service.download('ambient-essentials'),/corrompido/);assert.equal((await f.service.state()).installed['ambient-essentials'].version,1);next=fixture(2).zip;value.packs[0].bytes=next.length;value.packs[0].sha256=hash(next);fs.writeFileSync(f.file,JSON.stringify(value));const result=await f.service.download('ambient-essentials');assert.equal(result.installed['ambient-essentials'].version,2);assert.equal(fs.existsSync(path.join(f.root,'ambient','packs','ambient-essentials-v1')),false);}finally{f.cleanup();}});
test('som próprio referenciado, ausente, relink, importado e removido',async()=>{const f=setup();try{await f.service.initialize();const source=path.join(f.root,'music.wav'),other=path.join(f.root,'other.wav');fs.writeFileSync(source,Buffer.alloc(2000,7));fs.writeFileSync(other,Buffer.alloc(2000,8));let state=await f.service.addCustom(source,'reference');const id=state.custom[0].id;assert.equal(state.custom[0].missing,false);fs.renameSync(source,source+'.bak');assert.equal((await f.service.state()).custom[0].missing,true);state=await f.service.relink(id,other);assert.equal(state.custom[0].missing,false);assert.equal((await f.service.audio(id))[0],8);await f.service.updateCustom(id,{name:'Meu som',volume:70});assert.equal((await f.service.state()).custom[0].name,'Meu som');state=await f.service.addCustom(other,'import');const imported=state.custom.find(item=>item.mode==='import');fs.rmSync(other);assert.equal((await f.service.state()).custom.find(item=>item.id===imported.id).missing,false);await f.service.removeCustom(id);assert.equal(fs.existsSync(source+'.bak'),true);await f.service.removeCustom(imported.id);assert.equal((await f.service.state()).custom.length,0);}finally{f.cleanup();}});
test('migração mantém IDs antigos sem equivalência e presets',()=>{const value=migrate({master:45,sounds:{'rain-light':{on:true,volume:60},cafe:{on:true,volume:33}},presets:[{id:'p1',name:'Antigo',sounds:{'rain-light':{on:true,volume:70},cafe:{on:true,volume:20}}}]});assert.equal(value.sounds['rain.light'].on,true);assert.equal(value.sounds.cafe.on,true);assert.ok(value.presets[0].sounds.cafe);assert.ok(value.presets[0].sounds['rain.light']);});
test('pacotes ficam fora dos arquivos empacotados do instalador',()=>{const pkg=require('../package.json');assert.equal(pkg.build.files.some(value=>value.includes('out')||value.includes('ambient-packs/*.zip')),false);assert.equal(pkg.build.extraResources.some(value=>value.from?.includes('ambient-packs')),false);});
