const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const splash = $('#splash'); const appShell = $('#appShell');
const history = JSON.parse(localStorage.getItem('ntc-history') || '[]');
let folder = localStorage.getItem('ntc-folder') || ''; let queue = []; let current = null; let preview = null; let playlist = null; let previewTimer; const abortedDownloads = new Set();

setTimeout(() => { splash.classList.add('exit'); appShell.classList.add('ready'); appShell.setAttribute('aria-hidden', 'false'); }, 1450);
function syncSettings() { $('#folderPath').textContent = folder || 'Downloads'; $('#settingsFolder').textContent = folder || 'Downloads'; $('#openFolderAfter').checked = localStorage.getItem('ntc-open-folder') === 'true'; $('#duplicatePolicy').value = localStorage.getItem('ntc-duplicate') || 'rename'; }
function formatBytes(bytes) { if (!bytes) return '—'; const units = ['B', 'KB', 'MB', 'GB']; let n = bytes; let i = 0; while (n > 1024 && i < units.length - 1) { n /= 1024; i++; } return `${n.toFixed(i ? 1 : 0)} ${units[i]}`; }
function renderHistory() {
  const list = $('#historyList'); const empty = $('#emptyHistory'); const all = $('#allHistory');
  if (!history.length) { list.classList.add('hidden'); empty.classList.remove('hidden'); all.innerHTML = '<div class="empty-state"><div class="empty-icon">◷</div><p>Nenhum download concluído ainda.</p></div>'; return; }
  const markup = history.map((item, index) => `<article class="history-item"><div class="history-icon">${item.type === 'audio' ? '♫' : '▸'}</div><div class="history-copy"><strong>${item.title}</strong><span>${item.format.toUpperCase()} · ${item.quality} · ${item.size} · ${item.time}</span></div><button class="ghost-button" data-open="${index}">Abrir</button><button class="ghost-button" data-copy="${index}">Copiar</button><button class="ghost-button" data-remove="${index}">×</button></article>`).join('');
  list.innerHTML = markup; list.classList.remove('hidden'); empty.classList.add('hidden'); all.innerHTML = markup;
  $$('[data-open]').forEach(button => button.onclick = () => window.ntc.openFile(history[button.dataset.open].file)); $$('[data-copy]').forEach(button => button.onclick = () => window.ntc.copyPath(history[button.dataset.copy].file)); $$('[data-remove]').forEach(button => button.onclick = () => { history.splice(Number(button.dataset.remove), 1); localStorage.setItem('ntc-history', JSON.stringify(history)); renderHistory(); });
}
function renderQueue() {
  $('#queueCount').textContent = `${queue.length} ${queue.length === 1 ? 'item' : 'itens'}`;
  $('#abortQueue').disabled = !queue.length && !current;
  if (!queue.length) { $('#queueList').innerHTML = '<div class="empty-state"><p>Adicione links à fila para baixá-los em sequência.</p></div>'; return; }
  $('#queueList').innerHTML = queue.map((item, index) => `<article class="queue-item"><span class="queue-index">${index + 1}</span><div class="history-copy"><strong>${item.title || item.url}</strong><span>${item.type === 'audio' ? 'Áudio' : 'Vídeo'} · ${item.format.toUpperCase()} · ${item.quality} · ${item.status}</span></div>${index ? `<button class="ghost-button" data-up="${item.downloadId}">↑</button>` : ''}${index < queue.length - 1 ? `<button class="ghost-button" data-down="${item.downloadId}">↓</button>` : ''}${item.status === 'erro' ? `<button class="ghost-button" data-retry="${item.downloadId}">Tentar</button>` : ''}<button class="ghost-button" data-queue-remove="${item.downloadId}">×</button></article>`).join('');
  $$('[data-queue-remove]').forEach(button => button.onclick = () => { if (current?.downloadId === button.dataset.queueRemove) return; queue = queue.filter(item => item.downloadId !== button.dataset.queueRemove); renderQueue(); });
  $$('[data-up],[data-down]').forEach(button => button.onclick = () => { const index = queue.findIndex(item => item.downloadId === (button.dataset.up || button.dataset.down)); const next = button.dataset.up ? index - 1 : index + 1; if (index > 0 || button.dataset.down) [queue[index], queue[next]] = [queue[next], queue[index]]; renderQueue(); });
  $$('[data-retry]').forEach(button => button.onclick = () => { const item = queue.find(i => i.downloadId === button.dataset.retry); if (item) { item.status = 'aguardando'; startNext(); renderQueue(); } });
}
function setFormatOptions() { const video = $('input[name="downloadType"]:checked').value === 'video'; $('#format').innerHTML = video ? '<option value="mp4">MP4</option><option value="webm">WEBM</option>' : '<option value="mp3">MP3</option><option value="m4a">M4A</option><option value="opus">Opus</option>'; $('#quality').innerHTML = video ? '<option value="best">Melhor disponível</option><option value="2160">2160p</option><option value="1440">1440p</option><option value="1080">1080p</option><option value="720">720p</option><option value="480">480p</option><option value="360">360p</option><option value="240">240p</option><option value="144">144p</option>' : '<option value="original">Original</option><option value="128">128 kbps</option><option value="192">192 kbps</option><option value="256">256 kbps</option><option value="320">320 kbps</option>'; }
async function chooseFolder() { const chosen = await window.ntc.chooseDownloadFolder(); if (chosen) { folder = chosen; localStorage.setItem('ntc-folder', folder); syncSettings(); } }
async function loadPreview() {
  const url = $('#videoUrl').value.trim(); if (!url) { preview = null; playlist = null; $('#previewCard').classList.add('hidden'); $('#selectPlaylist').classList.add('hidden'); return; }
  $('#previewCard').classList.remove('hidden'); $('#previewTitle').textContent = 'Carregando prévia…'; $('#previewMeta').textContent = 'Consultando informações';
  try { preview = await window.ntc.previewUrl(url); playlist = await window.ntc.playlistPreview(url); if (!playlist.isPlaylist) playlist = null; $('#previewImage').src = playlist?.thumbnail || preview.thumbnail; $('#previewTitle').textContent = playlist?.title || preview.title; $('#previewMeta').textContent = playlist ? `${playlist.entries.length} músicas na playlist` : `${preview.channel} · ${preview.duration}`; $('#selectPlaylist').classList.toggle('hidden', !playlist); $('.url-input-wrap').classList.add('valid'); } catch (error) { preview = null; playlist = null; $('#selectPlaylist').classList.add('hidden'); $('#previewTitle').textContent = 'Link indisponível'; $('#previewMeta').textContent = error.message; $('.url-input-wrap').classList.remove('valid'); }
}
function safeBase(value) { return value.replace(/[<>:"/\\|?*\u0000-\u001f]/g, '').replace(/[. ]+$/, '').slice(0, 150) || 'download'; }
function newJob(source = preview) { if (!source) return null; const format = $('#format').value; return { downloadId: `${Date.now()}-${Math.random().toString(16).slice(2)}`, url: source.webpageUrl || $('#videoUrl').value.trim(), title: source.title, filename: `${safeBase(source.title)}.${format}`, type: $('input[name="downloadType"]:checked').value, format, quality: $('#quality').value, folder, duplicate: localStorage.getItem('ntc-duplicate') || 'rename', status: 'aguardando' }; }
function enqueueSources(sources) { let added = 0; sources.forEach(source => { const item = newJob(source); if (item && !queue.some(existing => existing.url === item.url)) { queue.push(item); added++; } }); if (added) { renderQueue(); startNext(); } return added; }
async function addToQueue() { if (!preview) await loadPreview(); if (!preview) return; const sources = playlist ? playlist.entries : [preview]; const added = enqueueSources(sources); if (!added) { $('#previewMeta').textContent = 'Estes links já estão na fila.'; return; } $('#videoUrl').value = ''; preview = null; playlist = null; $('#previewCard').classList.add('hidden'); $('#selectPlaylist').classList.add('hidden'); }
function setProgress(update) { $('#progressBar').style.width = `${update.percent || 0}%`; $('#progressPercent').textContent = `${Math.round(update.percent || 0)}%`; $('#downloadSpeed').textContent = update.speed || '—'; $('#timeRemaining').textContent = update.eta || '—'; }
async function startNext() {
  if (current) return; const item = queue.find(i => i.status === 'aguardando'); if (!item) return; current = item; item.status = 'baixando'; $('#progressCard').classList.remove('hidden'); $('#statusPill').textContent = 'BAIXANDO'; $('#mediaTitle').textContent = item.title; $('#mediaMeta').textContent = `${item.type === 'audio' ? 'Áudio' : 'Vídeo'} · ${item.format.toUpperCase()} · ${item.quality}`; $('#cancelButton').textContent = 'Cancelar'; $('#cancelButton').onclick = () => window.ntc.cancelDownload(item.downloadId); $('#downloadButton').disabled = true; renderQueue();
  try { await window.ntc.startDownload(item); } catch (error) { item.status = error.message.includes('cancelado') ? 'cancelado' : 'erro'; const wasAborted = abortedDownloads.delete(item.downloadId); current = null; $('#downloadButton').disabled = false; $('#statusPill').textContent = wasAborted ? 'INTERROMPIDO' : item.status.toUpperCase(); $('#mediaMeta').textContent = wasAborted ? 'Downloads interrompidos pelo usuário.' : error.message; renderQueue(); setTimeout(startNext, 0); }
}
window.ntc.onDownloadEvent(update => { if (!current || current.downloadId !== update.downloadId || abortedDownloads.has(update.downloadId)) return; if (update.status === 'downloading') { current.title = update.title || current.title; $('#mediaTitle').textContent = current.title; setProgress(update); } if (update.status === 'complete') { current.status = 'concluído'; current.file = update.file; current.size = formatBytes(update.size); history.unshift({ title: current.title, type: current.type, format: current.format, quality: current.quality, size: current.size, file: current.file, time: 'Agora' }); localStorage.setItem('ntc-history', JSON.stringify(history.slice(0, 50))); queue = queue.filter(item => item.downloadId !== current.downloadId); current = null; $('#statusPill').textContent = 'CONCLUÍDO'; $('#mediaTitle').textContent = 'Download concluído'; $('#mediaMeta').textContent = `Salvo em ${folder}`; $('#downloadButton').disabled = false; renderHistory(); renderQueue(); if ($('#openFolderAfter').checked) window.ntc.openFolder(folder); setTimeout(startNext, 0); } });
function openPlaylistSelection() { if (!playlist) return; $('#playlistTitle').textContent = playlist.title; $('#playlistSummary').textContent = `${playlist.entries.length} músicas disponíveis`; $('#playlistList').innerHTML = playlist.entries.map((item, index) => `<label class="playlist-item"><input type="checkbox" data-playlist-entry="${index}" checked><span class="playlist-number">${index + 1}</span><img src="${item.thumbnail || ''}" alt=""><span><strong>${item.title}</strong><small>${item.channel || 'YouTube'} · ${item.duration}</small></span></label>`).join(''); $$('.nav-item').forEach(item => item.classList.remove('active')); $$('.view').forEach(view => view.classList.remove('active')); $('#playlistView').classList.add('active'); }
$('#selectPlaylist').onclick = openPlaylistSelection;
$('#abortQueue').onclick = () => { if (current) { abortedDownloads.add(current.downloadId); window.ntc.cancelDownload(current.downloadId); } queue = []; renderQueue(); $('#progressCard').classList.add('hidden'); };
$('#selectAllPlaylist').onclick = () => $$('[data-playlist-entry]').forEach(item => { item.checked = true; });
$('#clearPlaylistSelection').onclick = () => $$('[data-playlist-entry]').forEach(item => { item.checked = false; });
$('#addSelectedPlaylist').onclick = () => { if (!playlist) return; const chosen = $$('[data-playlist-entry]:checked').map(item => playlist.entries[Number(item.dataset.playlistEntry)]); enqueueSources(chosen); $('#videoUrl').value = ''; preview = null; playlist = null; $('#previewCard').classList.add('hidden'); $('#selectPlaylist').classList.add('hidden'); $$('.view').forEach(view => view.classList.remove('active')); $('#downloaderView').classList.add('active'); $$('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === 'downloader')); };
$('#videoUrl').addEventListener('input', () => { clearTimeout(previewTimer); previewTimer = setTimeout(loadPreview, 650); }); $('#downloadForm').addEventListener('submit', e => { e.preventDefault(); addToQueue(); }); $$('input[name="downloadType"]').forEach(input => input.addEventListener('change', setFormatOptions)); $('#chooseFolder').onclick = chooseFolder; $('#chooseFolderSettings').onclick = chooseFolder; $('#openFolderAfter').onchange = e => localStorage.setItem('ntc-open-folder', e.target.checked); $('#duplicatePolicy').onchange = e => localStorage.setItem('ntc-duplicate', e.target.value); $('#clearHistory').onclick = () => { history.length = 0; localStorage.removeItem('ntc-history'); renderHistory(); }; $('#checkTools').onclick = async () => { const v = await window.ntc.toolVersions(); $('#toolVersions').textContent = v.error || `yt-dlp ${v.ytdlp} · FFmpeg instalado`; };
$$('.nav-item[data-view]').forEach(button => button.onclick = () => { $$('.nav-item').forEach(item => item.classList.remove('active')); button.classList.add('active'); $$('.view').forEach(view => view.classList.remove('active')); $(`#${button.dataset.view}View`).classList.add('active'); });
$$('[data-open-tool]').forEach(button => button.onclick = () => { const target = button.dataset.openTool; $$('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === target)); $$('.view').forEach(view => view.classList.toggle('active', view.id === `${target}View`)); });
$('#minimizeWindow').onclick = () => window.ntc.minimizeWindow();
$('#maximizeWindow').onclick = async () => { const maximized = await window.ntc.toggleMaximize(); $('#maximizeWindow').textContent = maximized ? '❐' : '□'; $('#maximizeWindow').setAttribute('aria-label', maximized ? 'Restaurar' : 'Maximizar'); };
$('#closeWindow').onclick = () => window.ntc.closeWindow();
syncSettings(); setFormatOptions(); renderHistory(); renderQueue(); window.ntc.defaultDownloadFolder().then(value => { if (!folder) { folder = value; localStorage.setItem('ntc-folder', folder); syncSettings(); } });
