const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const splash = $('#splash'); const appShell = $('#appShell'); const loadingProgress = $('#loadingProgress'); const loadingTrack = $('.loading-line');
const history = JSON.parse(localStorage.getItem('ntc-history') || '[]');
let folder = localStorage.getItem('ntc-folder') || '';
let queue = (() => { try { return JSON.parse(localStorage.getItem('ntc-download-queue') || '[]').map(item => ({ ...item, status: item.status === 'baixando' ? 'pausado' : item.status, percent: 0 })); } catch { return []; } })(); let current = null; let preview = null; let playlist = null; let previewTimer; const abortedDownloads = new Set(); const pausedDownloads = new Set();
let conversionQueue = []; let currentConversion = null; let editingConversionId = null; const abortedConversions = new Set();
let waveformData = []; let waveformFor = null; let waveformHandle = null; let waveformZoom = 1; let waveformFocus = null; let previewAudio = null; let playbackTime = null; let playbackFrame = null; let previewAudioContext = null; let previewAudioSource = null; let previewEffectNodes = null;
let downloadedAudioToEdit = null; let editSuggestionTimer = null;
let editorUndoStack = []; let editorRedoStack = []; let editorDraft = null;
let audioMarkers = []; let spectrumVisible = false; let videoQueue = []; let currentVideo = null; let imageQueue = []; let currentImage = null; let lastFailedImage = null;
let screenRecorder = { recorder: null, stream: null, id: null, startedAt: 0, timer: null, chunkChain: Promise.resolve(), withAudio: false };
let screenRecorderStarting = false;
let compressionQueue = []; let compressionRunning = false;

let splashValue = 0;
const advanceSplash = () => { splashValue = Math.min(92, splashValue + (splashValue < 70 ? 4 : 1.5)); loadingProgress.style.width = `${splashValue}%`; loadingTrack.setAttribute('aria-valuenow', String(Math.round(splashValue))); };
const splashTimer = setInterval(advanceSplash, 110);
setTimeout(() => { clearInterval(splashTimer); splashValue = 100; loadingProgress.style.width = '100%'; loadingTrack.setAttribute('aria-valuenow', '100'); setTimeout(() => { splash.classList.add('exit'); appShell.classList.add('ready'); appShell.setAttribute('aria-hidden', 'false'); }, 260); }, 2100);
function formatBytes(bytes) { if (!bytes) return '—'; const units = ['B', 'KB', 'MB', 'GB']; let n = bytes; let i = 0; while (n > 1024 && i < units.length - 1) { n /= 1024; i++; } return `${n.toFixed(i ? 1 : 0)} ${units[i]}`; }
function safeText(value) { return String(value || '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function cleanError(value) { const message = String(value?.message || value || 'Não foi possível concluir a operação.').replace(/^Error invoking remote method ['"]?[^'"]+['"]?: Error:\s*/i, '').replace(/^Error:\s*/i, ''); if (/no space|espaço|disk full/i.test(message)) return 'Sem espaço suficiente na pasta escolhida. Escolha outra pasta ou libere espaço.'; if (/network|connection|timed out|conex/i.test(message)) return 'Falha de conexão. Verifique a internet e tente novamente.'; if (/permission|access is denied|acesso negado|notallowed|denied/i.test(message)) return 'A permissão foi recusada. Verifique o microfone ou escolha gravar somente a tela.'; if (/too large|maximum dimension|jpeg format/i.test(message)) return 'A imagem ficou grande demais para este formato. Diminua largura, altura ou escala e tente novamente.'; if (/invalid|corrupt|corromp/i.test(message)) return 'O arquivo não pôde ser lido. Verifique se ele está completo e em um formato suportado.'; return message; }
let toastTimer = null; let confirmResolver = null;
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2800); }
function formatRecordingTime(milliseconds) { const seconds = Math.floor(Math.max(0, milliseconds) / 1000); const hours = String(Math.floor(seconds / 3600)).padStart(2, '0'); const minutes = String(Math.floor((seconds % 3600) / 60)).padStart(2, '0'); return `${hours}:${minutes}:${String(seconds % 60).padStart(2, '0')}`; }
function updateRecorderStatus(recording = Boolean(screenRecorder.recorder)) { const status = $('#recorderStatus'); if (!status) return; status.classList.toggle('is-recording', recording); $('#recorderState').textContent = recording ? 'Gravando tela' : 'Pronto para gravar'; $('#toggleRecording').textContent = recording ? 'Parar gravação' : 'Iniciar gravação'; if (!recording) $('#recorderTimer').textContent = '00:00:00'; }
function recordingAudioChoice() { const promise = confirmAction('Microfone da gravação', 'Deseja adicionar o microfone ao áudio do computador?', 'Adicionar microfone'); $('#confirmCancel').textContent = 'Som do computador'; return promise.finally(() => { $('#confirmCancel').textContent = 'Cancelar'; }); }
async function getScreenStream(withSystemAudio, withMicrophone) {
  const sources = await window.ntc.screenSources(); if (!sources?.length) throw new Error('Nenhuma tela disponível para capturar.');
  const sourceId = sources[0].id; const screen = await Promise.race([navigator.mediaDevices.getUserMedia({ audio: withSystemAudio ? { mandatory: { chromeMediaSource: 'desktop', chromeMediaSourceId: sourceId } } : false, video: { mandatory: { chromeMediaSource: 'desktop', chromeMediaSourceId: sourceId, minFrameRate: 15, maxFrameRate: 30 } } }), new Promise((_, reject) => setTimeout(() => reject(new Error('Tempo esgotado ao iniciar a captura da tela.')), 8000))]);
  if (!withMicrophone) return screen;
  try { const microphone = await Promise.race([navigator.mediaDevices.getUserMedia({ audio: true, video: false }), new Promise((_, reject) => setTimeout(() => reject(new Error('Tempo esgotado ao solicitar o microfone.')), 8000))]); microphone.getAudioTracks().forEach(track => screen.addTrack(track)); return screen; } catch (error) { screen.getTracks().forEach(track => track.stop()); throw error; }
}
async function startScreenRecording() {
  if (screenRecorder.recorder) return stopScreenRecording(); if (screenRecorderStarting) return; screenRecorderStarting = true;
  const chosenFolder = localStorage.getItem('ntc-recorder-folder') || folder || await window.ntc.defaultDownloadFolder(); if (!chosenFolder) { screenRecorderStarting = false; return; }
  let withMicrophone = await recordingAudioChoice(); let stream; const withSystemAudio = true;
  try { stream = await getScreenStream(withSystemAudio, withMicrophone); } catch (error) { if (withMicrophone) { const fallbackMic = await confirmAction('Microfone indisponível', 'Não foi possível acessar o microfone. Deseja continuar com o áudio do computador?', 'Continuar com áudio do PC'); if (fallbackMic) { try { stream = await getScreenStream(withSystemAudio, false); withMicrophone = false; } catch (systemError) { showToast(`Não foi possível capturar o áudio do computador: ${cleanError(systemError)}`); screenRecorderStarting = false; return; } } else { screenRecorderStarting = false; return; } } else { const fallback = await confirmAction('Áudio do computador indisponível', 'O sistema não permitiu capturar o áudio do computador. Deseja gravar somente a tela?', 'Gravar sem áudio'); if (!fallback) { screenRecorderStarting = false; return; } try { stream = await getScreenStream(false, false); } catch (fallbackError) { showToast(`Não foi possível iniciar a captura: ${cleanError(fallbackError)}`); screenRecorderStarting = false; return; } } }
  const resolution = $('#recordResolution').value || localStorage.getItem('ntc-record-resolution') || 'original'; localStorage.setItem('ntc-record-resolution', resolution); const quality = resolution === 'original' ? 'equilibrada' : 'alta'; const mimeType = MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus') ? 'video/webm;codecs=vp9,opus' : 'video/webm'; const recorder = new MediaRecorder(stream, { mimeType }); let session; try { session = await window.ntc.startScreenRecording({ folder: chosenFolder, resolution, quality, withAudio: stream.getAudioTracks().length > 0 }); } catch (error) { stream.getTracks().forEach(track => track.stop()); screenRecorderStarting = false; showToast(`Não foi possível preparar a gravação: ${cleanError(error)}`); return; }
  screenRecorder = { recorder, stream, id: session.id, startedAt: Date.now(), timer: null, chunkChain: Promise.resolve(), withAudio: stream.getAudioTracks().length > 0 }; screenRecorderStarting = false; recorder.ondataavailable = event => { if (event.data.size) screenRecorder.chunkChain = screenRecorder.chunkChain.then(() => event.data.arrayBuffer()).then(buffer => window.ntc.sendScreenRecordingChunk(session.id, buffer)); }; recorder.onerror = () => showToast('A captura encontrou um erro. Tente novamente.'); recorder.onstop = async () => { clearInterval(screenRecorder.timer); try { const result = await Promise.race([screenRecorder.chunkChain.then(() => window.ntc.stopScreenRecording(session.id)), new Promise((_, reject) => setTimeout(() => reject(new Error('A finalização demorou demais.')), 30000))]); addHistory({ title: result.filename, type: 'video', format: 'mp4', quality: 'H.264', size: formatBytes(result.size), file: result.file, time: 'Agora', operation: 'recording' }); showToast('Gravação salva no histórico.'); } catch (error) { await window.ntc.cancelScreenRecording(session.id).catch(() => {}); showToast(cleanError(error)); } finally { stream.getTracks().forEach(track => track.stop()); screenRecorder = { recorder: null, stream: null, id: null, startedAt: 0, timer: null, chunkChain: Promise.resolve(), withAudio: false }; updateRecorderStatus(false); } }; recorder.start(1000); screenRecorder.timer = setInterval(() => { $('#recorderTimer').textContent = formatRecordingTime(Date.now() - screenRecorder.startedAt); }, 250); updateRecorderStatus(true); showToast(withMicrophone ? 'Áudio do computador e microfone ativados.' : 'Áudio do computador ativado.'); }
async function stopScreenRecording() { if (!screenRecorder.recorder) return; $('#recorderState').textContent = 'Finalizando gravação…'; $('#toggleRecording').disabled = true; const recorder = screenRecorder.recorder; recorder.stop(); await new Promise(resolve => { const wait = setInterval(() => { if (!screenRecorder.recorder) { clearInterval(wait); resolve(); } }, 50); }); $('#toggleRecording').disabled = false; }
async function configureRecordingShortcut(value = $('#recordShortcut')?.value || 'Ctrl+Shift+R') { const result = await window.ntc.registerScreenShortcut(value); if (!result.ok) { showToast(result.message || 'Não foi possível registrar esse atalho.'); return false; } localStorage.setItem('ntc-record-shortcut', value); $('#recordShortcutLabel').textContent = value.replaceAll('Control', 'Ctrl').replaceAll('+', ' + '); showToast('Atalho do gravador atualizado.'); return true; }
function openChangelog() {
  const list = $('#changelogList'); list.replaceChildren(...(window.NTC_CHANGELOG || []).map(entry => {
    const article = document.createElement('article'); article.className = 'changelog-entry';
    const heading = document.createElement('div'); heading.className = 'changelog-entry-heading'; const title = document.createElement('h3'); title.textContent = `v${entry.version}`; const date = document.createElement('time'); date.textContent = entry.date; heading.append(title, date);
    const changes = document.createElement('ul'); entry.changes.forEach(change => { const line = document.createElement('li'); line.textContent = change; changes.append(line); }); article.append(heading, changes); return article;
  }));
  $('#changelogDialog').classList.remove('hidden'); $('#closeChangelog').focus();
}
function changelogLines(notes) { return String(notes || '').split(/\r?\n/).map(line => line.replace(/^\s*[-*•#]+\s*/, '').trim()).filter(Boolean).slice(0, 6); }
function showUpdateNotice(update) {
  const notice = $('#updateNotice'); const status = update?.status || 'idle'; const statusText = $('#updateStatus');
  if (status === 'checking') { statusText.textContent = 'Verificando atualizações…'; return; }
  if (status === 'unavailable') { statusText.textContent = update.message || 'A verificação funciona na versão instalada.'; return; }
  if (status === 'current') { statusText.textContent = `Você já está usando a versão mais recente (v${update.version}).`; showToast('O NTC Utilities está atualizado.'); return; }
  if (status === 'error') { statusText.textContent = update.message || 'Não foi possível verificar atualizações.'; showToast(statusText.textContent); return; }
  if (status === 'available' || status === 'downloading' || status === 'downloaded') {
    const version = update.version ? `v${update.version}` : 'a nova versão'; const downloading = status === 'downloading'; const downloaded = status === 'downloaded';
    statusText.textContent = downloaded ? `${version} está pronta para instalar.` : downloading ? `Baixando ${version}… ${update.percent || 0}%` : `${version} está disponível.`;
    $('#updateTitle').textContent = downloaded ? `${version} pronta para instalar` : `${version} está disponível`;
    $('#updateSummary').textContent = downloaded ? 'A instalação será iniciada ao confirmar.' : downloading ? `Baixando a atualização: ${update.percent || 0}%.` : 'Veja as novidades antes de atualizar.';
    const notes = changelogLines(update.notes); const list = $('#updateNotes'); list.replaceChildren(...notes.map(note => { const li = document.createElement('li'); li.textContent = note; return li; })); list.classList.toggle('hidden', !notes.length);
    const action = $('#updateAction'); action.disabled = downloading; action.textContent = downloaded ? 'Instalar e reiniciar' : downloading ? `Baixando ${update.percent || 0}%` : 'Baixar atualização'; action.dataset.updateStatus = status;
    notice.classList.remove('hidden');
  }
}
function closeConfirm(result) { $('#confirmDialog').classList.add('hidden'); const resolver = confirmResolver; confirmResolver = null; resolver?.(result); }
function confirmAction(title, message, acceptLabel = 'Confirmar') { $('#confirmTitle').textContent = title; $('#confirmMessage').textContent = message; $('#confirmAccept').textContent = acceptLabel; $('#confirmDialog').classList.remove('hidden'); $('#confirmCancel').focus(); return new Promise(resolve => { confirmResolver = resolve; }); }
function syncSettings() { $('#folderPath').textContent = folder || 'Downloads'; $('#settingsFolder').textContent = folder || 'Downloads'; if (!editingConversionId) $('#converterFolderPath').textContent = folder || 'Downloads'; $('#videoFolderPath').textContent = folder || 'Downloads'; $('#imageFolderPath').textContent = folder || 'Downloads'; $('#recorderFolderPath').textContent = localStorage.getItem('ntc-recorder-folder') || folder || 'Downloads'; $('#openFolderAfter').checked = localStorage.getItem('ntc-open-folder') === 'true'; $('#duplicatePolicy').value = localStorage.getItem('ntc-duplicate') || 'rename'; $('#filenameTemplate').value = localStorage.getItem('ntc-filename-template') || 'title'; $('#themePreference').value = localStorage.getItem('ntc-theme') || 'dark'; document.body.classList.toggle('theme-light', $('#themePreference').value === 'light'); document.documentElement.style.colorScheme = $('#themePreference').value; }
async function refreshSpaceHint(estimatedSize = 0) { if (!folder) return; try { const free = await window.ntc.freeSpace(folder); if (!Number.isFinite(free)) { $('#spaceHint').textContent = 'Espaço disponível não informado.'; return; } $('#spaceHint').textContent = estimatedSize ? `Espaço livre: ${formatBytes(free)} · estimativa: ~${formatBytes(estimatedSize)}` : `Espaço livre: ${formatBytes(free)}`; } catch { $('#spaceHint').textContent = 'Espaço disponível não informado.'; } }
function addHistory(item) { history.unshift(item); history.splice(50); localStorage.setItem('ntc-history', JSON.stringify(history)); renderHistory(); }
function compressionIsImage(file) { return /\.(jpe?g|png|webp|bmp|tiff?)$/i.test(file || ''); }
async function updateCompressionPreview() { const item = compressionQueue[0]; const card = $('#compressionPreviewCard'); if (!item) { card.classList.add('hidden'); return; } card.classList.remove('hidden'); $('#compressionPreviewTitle').textContent = item.name; if (!compressionIsImage(item.source)) { $('#compressionPreviewOriginal').removeAttribute('src'); $('#compressionPreviewResult').removeAttribute('src'); $('#compressionPreviewMeta').textContent = /\.(mp4|mkv|mov|avi|webm|m4v)$/i.test(item.source) ? `Resultado previsto: ${$('#compressionResolution').value === 'original' ? 'resolução original' : `${$('#compressionResolution').value}p`} · ${$('#compressionFps').value} FPS · CRF ${$('#compressionCrf').value} · áudio ${$('#compressionBitrate').value} kbps.` : `Resultado previsto: MP3 · ${$('#compressionBitrate').value} kbps.`; return; } $('#compressionPreviewOriginal').src = sourceUrl(item.source); $('#compressionPreviewMeta').textContent = 'Gerando resultado com estes ajustes…'; try { const preview = await window.ntc.previewImage({ source: item.source, format: 'jpg', quality: $('#compressionImageQuality').value, scale: $('#compressionImageScale').value, keepRatio: true }); $('#compressionPreviewResult').src = preview.dataUrl; $('#compressionPreviewMeta').textContent = `Resultado: ${preview.width} × ${preview.height} · qualidade ${$('#compressionImageQuality').value}%.`; } catch (error) { $('#compressionPreviewMeta').textContent = cleanError(error); } }
function renderCompressionQueue() { $('#compressionCount').textContent = `${compressionQueue.length} ${compressionQueue.length === 1 ? 'item' : 'itens'}`; $('#compressionList').innerHTML = compressionQueue.length ? compressionQueue.map((item, index) => `<article class="queue-item conversion-item"><span class="queue-index">${index + 1}</span><div class="history-copy"><strong>${safeText(item.name)}</strong><span>${safeText(item.status || 'Pronto')}</span></div>${item.status !== 'Comprimindo' ? `<button class="ghost-button" data-compression-remove="${item.id}">Remover</button>` : ''}</article>`).join('') : '<div class="empty-state"><p>Adicione arquivos para comprimir.</p></div>'; $$('[data-compression-remove]').forEach(button => button.onclick = () => { compressionQueue = compressionQueue.filter(item => item.id !== button.dataset.compressionRemove); renderCompressionQueue(); updateCompressionPreview(); }); }
function updateCompressionControls() { const source = compressionQueue[0]?.source || ''; const video = /\.(mp4|mkv|mov|avi|webm|m4v)$/i.test(source); $$('.compression-video-option').forEach(element => element.classList.toggle('hidden', Boolean(source) && !video)); }
async function addCompressionFiles(files) { files.filter(file => /\.(mp4|mkv|mov|avi|webm|m4v|mp3|m4a|aac|wav|flac|ogg|opus|wma)$/i.test(file || '')).forEach(file => { if (!compressionQueue.some(item => item.source === file)) compressionQueue.push({ id: toolId(), source: file, name: file.split(/[\\/]/).pop(), status: 'Pronto' }); }); renderCompressionQueue(); updateCompressionControls(); }
function applyCompressionPreset() { const preset = $('#compressionPreset').value; if (preset === 'equilibrado') Object.assign({ }, { }); const values = preset === 'muito' ? { resolution: '144', fps: 8, crf: 45, bitrate: 16, quality: 5, scale: 20 } : { resolution: '720', fps: 24, crf: 30, bitrate: 64, quality: 60, scale: 60 }; if (preset !== 'manual') { $('#compressionResolution').value = values.resolution; $('#compressionFps').value = values.fps; $('#compressionCrf').value = values.crf; $('#compressionBitrate').value = values.bitrate; $('#compressionImageQuality').value = values.quality; $('#compressionImageScale').value = values.scale; } }
async function startCompressionQueue() { if (compressionRunning) return; compressionRunning = true; const compressionFolder = localStorage.getItem('ntc-compression-folder') || folder; for (const item of compressionQueue.filter(entry => entry.status === 'Pronto' || entry.status === 'Falhou')) { item.status = 'Comprimindo'; renderCompressionQueue(); try { const result = await window.ntc.startCompression({ ...item, folder: compressionFolder, duplicate: 'rename', resolution: $('#compressionResolution').value, fps: $('#compressionFps').value, crf: $('#compressionCrf').value, audioBitrate: $('#compressionBitrate').value, imageQuality: $('#compressionImageQuality').value, imageScale: $('#compressionImageScale').value }); item.status = 'Concluído'; addHistory({ title: result.file.split(/[\\/]/).pop(), type: result.kind, format: result.kind === 'image' ? 'JPG' : result.kind === 'video' ? 'MP4' : 'MP3', quality: 'comprimido', size: formatBytes(result.size), file: result.file, time: 'Agora', operation: 'compression' }); } catch (error) { item.status = `Falhou: ${cleanError(error)}`; } renderCompressionQueue(); } compressionRunning = false; }
function showEditAfterDownload(file, title) { downloadedAudioToEdit = { file, title }; $('#downloadedAudioName').textContent = title || 'Download concluído.'; $('#editAfterDownloadModal').classList.remove('hidden'); clearTimeout(editSuggestionTimer); editSuggestionTimer = setTimeout(hideEditAfterDownload, 8000); }
function hideEditAfterDownload() { clearTimeout(editSuggestionTimer); editSuggestionTimer = null; downloadedAudioToEdit = null; $('#editAfterDownloadModal').classList.add('hidden'); }

function renderHistory() {
  const list = $('#historyList'); const empty = $('#emptyHistory'); const all = $('#allHistory');
  if (!history.length) { list.classList.add('hidden'); empty.classList.remove('hidden'); all.innerHTML = '<div class="empty-state"><div class="empty-icon">◷</div><p>Nenhum arquivo concluído ainda.</p></div>'; return; }
  const filter = $('#historyFilter')?.value || 'all'; const visible = history.map((item, index) => ({ item, index })).filter(({ item }) => filter === 'all' || (filter === 'failed' ? item.state === 'erro' : item.operation === filter));
  const markup = visible.length ? visible.map(({ item, index }) => `<article class="history-item"><div class="history-icon">${item.state === 'erro' ? '!' : (item.type === 'video' ? '▸' : (item.type === 'image' ? '▧' : '♫'))}</div><div class="history-copy"><strong>${safeText(item.title)}</strong><span>${safeText(item.format?.toUpperCase() || '—')} · ${safeText(item.quality || 'original')} · ${safeText(item.size || '—')} · ${safeText(item.state === 'erro' ? 'falhou' : item.time)}</span></div>${item.file ? `<button class="ghost-button" data-open="${index}">Abrir</button><button class="ghost-button" data-folder="${index}">Pasta</button>` : ''}${item.type === 'audio' && (item.file || item.source) ? `<button class="ghost-button" data-edit-audio="${index}">Abrir no Editor</button>` : ''}</article>`).join('') : '<div class="empty-state"><p>Nenhum item neste filtro.</p></div>';
  list.innerHTML = markup; list.classList.remove('hidden'); empty.classList.add('hidden'); all.innerHTML = markup;
  $$('[data-open]').forEach(button => button.onclick = async () => { const result = await window.ntc.openFile(history[button.dataset.open].file); if (result) showToast('Não foi possível abrir o arquivo.'); });
  $$('[data-folder]').forEach(button => button.onclick = async () => { const result = await window.ntc.openFileFolder(history[button.dataset.folder].file); if (result) showToast('Não foi possível abrir a pasta.'); });
  $$('[data-edit-audio]').forEach(button => button.onclick = async () => { const item = history[button.dataset.editAudio]; const source = item?.file || item?.source; if (!source) return; await addMediaFiles([source]); $$('.nav-item').forEach(nav => nav.classList.toggle('active', nav.dataset.view === 'converter')); $$('.view').forEach(view => view.classList.toggle('active', view.id === 'converterView')); });
}

function persistQueue() { localStorage.setItem('ntc-download-queue', JSON.stringify(queue.map(item => ({ ...item, status: item.status === 'baixando' ? 'pausado' : item.status, percent: 0 })))); }
function queueStatusLabel(status) { return ({ aguardando: 'Aguardando', baixando: 'Baixando', pausado: 'Pausado', erro: 'Erro', cancelado: 'Cancelado' }[status] || status); }
function queuePercent(item) { return Math.max(0, Math.min(100, Number(item.percent) || 0)); }
function updateQueueProgress(item) {
  const row = document.querySelector(`[data-queue-progress="${item.downloadId}"]`); if (!row) return;
  const bar = row.querySelector('.queue-progress-fill'); const label = row.querySelector('.queue-progress-percent'); const percent = queuePercent(item);
  if (bar) bar.style.width = `${percent}%`; if (label) label.textContent = `${Math.round(percent)}%`;
}
function renderQueue() {
  const resumable = queue.some(item => ['aguardando', 'pausado', 'erro'].includes(item.status)); $('#queueCount').textContent = `${queue.length} ${queue.length === 1 ? 'item' : 'itens'}`; $('#abortQueue').disabled = !current; $('#abortQueue').classList.toggle('hidden', !current); $('#resumeQueue').classList.toggle('hidden', Boolean(current) || !resumable);
  if (!queue.length) { $('#queueList').innerHTML = '<div class="empty-state"><p>Adicione links à fila para baixá-los em sequência.</p></div>'; return; }
  $('#queueList').innerHTML = queue.map((item, index) => {
    const active = item.status === 'baixando'; const percent = queuePercent(item); const canMove = !active; const actionLabel = item.status === 'erro' ? 'Tentar novamente' : 'Remover da fila';
    const thumbnail = item.thumbnail ? `<img class="queue-thumbnail" src="${safeText(item.thumbnail)}" alt="" />` : '<span class="queue-thumbnail-fallback">♫</span>';
    return `<article class="queue-item download-queue-item ${active ? 'is-active' : ''}" data-queue-item="${item.downloadId}"><span class="queue-index">${index + 1}</span>${thumbnail}<div class="queue-item-main"><div class="queue-item-topline"><strong>${safeText(item.title || item.url)}</strong><span class="queue-item-status" data-status="${safeText(item.status)}">${safeText(queueStatusLabel(item.status))}</span></div><span class="queue-item-meta">${item.type === 'thumbnail' ? 'Thumbnail' : (item.type === 'audio' ? 'Áudio' : 'Vídeo')} · ${item.format.toUpperCase()} · ${safeText(item.quality)}${item.estimatedSize ? ` · ~${formatBytes(item.estimatedSize)}` : ''}</span><div class="queue-progress" data-queue-progress="${item.downloadId}" aria-label="Progresso de ${safeText(item.title || item.url)}"><span class="queue-progress-fill" style="width:${percent}%"></span><small class="queue-progress-percent">${active ? `${Math.round(percent)}%` : ''}</small></div></div>${canMove && index ? `<button class="ghost-button" data-up="${item.downloadId}" aria-label="Mover ${safeText(item.title || item.url)} para cima">↑</button>` : ''}${canMove && index < queue.length - 1 ? `<button class="ghost-button" data-down="${item.downloadId}" aria-label="Mover ${safeText(item.title || item.url)} para baixo">↓</button>` : ''}${item.status === 'erro' || item.status === 'pausado' ? `<button class="ghost-button" data-retry="${item.downloadId}">${item.status === 'pausado' ? 'Retomar' : actionLabel}</button>` : ''}${!active ? `<button class="ghost-button" data-queue-remove="${item.downloadId}" aria-label="Remover ${safeText(item.title || item.url)} da fila">×</button>` : ''}</article>`;
  }).join('');
  $$('[data-queue-remove]').forEach(button => button.onclick = () => { queue = queue.filter(item => item.downloadId !== button.dataset.queueRemove); persistQueue(); renderQueue(); });
  $$('[data-up],[data-down]').forEach(button => button.onclick = () => { const index = queue.findIndex(item => item.downloadId === (button.dataset.up || button.dataset.down)); const next = button.dataset.up ? index - 1 : index + 1; if (next >= 0 && next < queue.length && queue[index].status !== 'baixando' && queue[next].status !== 'baixando') [queue[index], queue[next]] = [queue[next], queue[index]]; persistQueue(); renderQueue(); });
  $$('[data-retry]').forEach(button => button.onclick = () => { const item = queue.find(entry => entry.downloadId === button.dataset.retry); if (item) { item.status = 'aguardando'; item.percent = 0; persistQueue(); startNext(); renderQueue(); } });
}
function setFormatOptions() { const type = $('input[name="downloadType"]:checked').value; const video = type === 'video'; const thumbnail = type === 'thumbnail'; $('#format').innerHTML = thumbnail ? '<option value="jpg">JPG</option><option value="png">PNG</option>' : (video ? '<option value="mp4">MP4</option><option value="webm">WEBM</option>' : '<option value="mp3">MP3</option><option value="m4a">M4A</option><option value="opus">Opus</option>'); $('#quality').disabled = thumbnail; $('#quality').innerHTML = thumbnail ? '<option value="original">Maior disponível</option>' : (video ? '<option value="best">Melhor disponível</option><option value="2160">2160p</option><option value="1440">1440p</option><option value="1080">1080p</option><option value="720">720p</option><option value="480">480p</option><option value="360">360p</option><option value="240">240p</option><option value="144">144p</option>' : '<option value="original">Original</option><option value="128">128 kbps</option><option value="192">192 kbps</option><option value="256">256 kbps</option><option value="320">320 kbps</option>'); }
async function chooseFolder() { const chosen = await window.ntc.chooseDownloadFolder(); if (chosen) { folder = chosen; localStorage.setItem('ntc-folder', folder); syncSettings(); refreshSpaceHint(); showToast('Pasta padrão atualizada.'); } }
async function loadPreview() {
  const url = $('#videoUrl').value.trim();
  if (!url) { preview = null; playlist = null; $('#previewCard').classList.add('hidden'); $('#selectPlaylist').classList.add('hidden'); return; }
  $('#previewCard').classList.remove('hidden'); $('#previewTitle').textContent = 'Carregando prévia…'; $('#previewMeta').textContent = 'Consultando informações';
  try { preview = await window.ntc.previewUrl(url); playlist = await window.ntc.playlistPreview(url); if (!playlist.isPlaylist) playlist = null; $('#previewImage').src = playlist?.thumbnail || preview.thumbnail; $('#previewTitle').textContent = playlist?.title || preview.title; $('#previewMeta').textContent = playlist ? `${playlist.entries.length} músicas na playlist` : `${preview.channel} · ${preview.duration}${preview.estimatedSize ? ` · ~${formatBytes(preview.estimatedSize)}` : ''}`; refreshSpaceHint(preview.estimatedSize); $('#selectPlaylist').classList.toggle('hidden', !playlist); $('.url-input-wrap').classList.add('valid'); }
  catch (error) { preview = null; playlist = null; $('#selectPlaylist').classList.add('hidden'); $('#previewTitle').textContent = 'Link indisponível'; $('#previewMeta').textContent = error.message; $('.url-input-wrap').classList.remove('valid'); }
}
function safeBase(value) { return value.replace(/[<>:"/\\|?*\u0000-\u001f]/g, '').replace(/[. ]+$/, '').slice(0, 150) || 'download'; }
function downloadBaseName(source) { const title = safeBase(source.title); const channel = safeBase(source.channel || 'Canal'); const template = localStorage.getItem('ntc-filename-template') || 'title'; if (template === 'channel-title') return safeBase(`${channel} - ${title}`); if (template === 'date-title') return safeBase(`${new Date().toISOString().slice(0, 10)} - ${title}`); return title; }
function newJob(source = preview) { if (!source) return null; const format = $('#format').value; return { downloadId: `${Date.now()}-${Math.random().toString(16).slice(2)}`, url: source.webpageUrl || $('#videoUrl').value.trim(), title: source.title, thumbnail: source.thumbnail || '', estimatedSize: Number(source.estimatedSize || 0), filename: `${downloadBaseName(source)}.${format}`, type: $('input[name="downloadType"]:checked').value, format, quality: $('#quality').value, speedLimit: $('#speedLimit').value, folder, duplicate: localStorage.getItem('ntc-duplicate') || 'rename', status: 'aguardando' }; }
function enqueueSources(sources) { let added = 0; sources.forEach(source => { const item = newJob(source); if (item && !queue.some(existing => existing.url === item.url)) { queue.push(item); added++; } }); if (added) { persistQueue(); renderQueue(); startNext(); } return added; }
async function addToQueue() { if (!preview) await loadPreview(); if (!preview) return; const sources = playlist ? playlist.entries : [preview]; const added = enqueueSources(sources); if (!added) { $('#previewMeta').textContent = 'Estes links já estão na fila.'; return; } $('#videoUrl').value = ''; preview = null; playlist = null; $('#previewCard').classList.add('hidden'); $('#selectPlaylist').classList.add('hidden'); }
function setProgress(update) { $('#progressBar').style.width = `${update.percent || 0}%`; $('#progressPercent').textContent = `${Math.round(update.percent || 0)}%`; $('#downloadSpeed').textContent = update.speed || '—'; $('#timeRemaining').textContent = update.eta || '—'; }
async function startNext() {
  if (current) return; const item = queue.find(entry => entry.status === 'aguardando'); if (!item) return;
  current = item; item.status = 'baixando'; item.percent = 0; $('#progressCard').classList.remove('hidden'); $('#statusPill').textContent = 'BAIXANDO'; $('#pauseButton').classList.remove('hidden'); $('#pauseButton').textContent = 'Pausar'; $('#cancelButton').textContent = 'Cancelar'; $('#mediaTitle').textContent = item.title; $('#mediaMeta').textContent = `${item.type === 'audio' ? 'Áudio' : (item.type === 'thumbnail' ? 'Thumbnail' : 'Vídeo')} · ${item.format.toUpperCase()} · ${item.quality}${item.speedLimit ? ` · limite ${item.speedLimit}/s` : ''}`; $('#cancelButton').onclick = () => window.ntc.cancelDownload(item.downloadId); $('#pauseButton').onclick = () => { pausedDownloads.add(item.downloadId); window.ntc.cancelDownload(item.downloadId); }; $('#downloadButton').disabled = true; persistQueue(); renderQueue();
  try { await window.ntc.startDownload(item); } catch (error) { const message = cleanError(error); const wasPaused = pausedDownloads.delete(item.downloadId); item.status = wasPaused ? 'pausado' : (message.includes('cancelado') ? 'cancelado' : 'erro'); const wasAborted = abortedDownloads.delete(item.downloadId); if (item.status === 'erro') addHistory({ title: item.title, type: item.type, format: item.format, quality: item.quality, size: '—', time: 'Agora', operation: 'download', state: 'erro' }); current = null; $('#downloadButton').disabled = false; $('#statusPill').textContent = wasPaused ? 'PAUSADO' : (wasAborted ? 'INTERROMPIDO' : item.status.toUpperCase()); $('#mediaMeta').textContent = wasPaused ? 'Download pausado. Você pode retomá-lo pela fila.' : (wasAborted ? 'Downloads interrompidos pelo usuário.' : message); persistQueue(); renderQueue(); if (!wasPaused) setTimeout(startNext, 0); }
}
window.ntc.onDownloadEvent(update => {
  if (!current || current.downloadId !== update.downloadId || abortedDownloads.has(update.downloadId)) return;
  if (update.status === 'downloading') { current.title = update.title || current.title; current.percent = update.percent || 0; $('#mediaTitle').textContent = current.title; setProgress(update); updateQueueProgress(current); }
  if (update.status === 'complete') { const completed = current; completed.status = 'concluído'; completed.file = update.file; completed.size = formatBytes(update.size); addHistory({ title: completed.title, type: completed.type, format: completed.format, quality: completed.quality, size: completed.size, file: completed.file, time: 'Agora', operation: 'download' }); queue = queue.filter(item => item.downloadId !== completed.downloadId); current = null; $('#statusPill').textContent = 'CONCLUÍDO'; $('#progressPercent').textContent = '100%'; $('#progressBar').style.width = '100%'; $('#mediaTitle').textContent = 'Download concluído'; $('#mediaMeta').textContent = `Salvo em ${completed.folder}`; $('#downloadSpeed').textContent = '—'; $('#timeRemaining').textContent = '0s'; $('#pauseButton').classList.add('hidden'); $('#cancelButton').textContent = 'Abrir pasta'; $('#cancelButton').onclick = () => window.ntc.openFolder(completed.folder); $('#downloadButton').disabled = false; persistQueue(); renderQueue(); if (completed.type === 'audio') showEditAfterDownload(completed.file, completed.title); if ($('#openFolderAfter').checked) window.ntc.openFolder(completed.folder); setTimeout(startNext, 0); }
});

function conversionQualityOptions(format, selected = '192') {
  const lossless = ['wav', 'flac', 'aiff'].includes(format); const select = $('#converterQuality');
  select.disabled = lossless; select.innerHTML = lossless ? '<option value="lossless">Sem perdas</option>' : '<option value="128">128 kbps</option><option value="192">192 kbps</option><option value="256">256 kbps</option><option value="320">320 kbps</option>';
  select.value = lossless ? 'lossless' : (['128', '192', '256', '320'].includes(String(selected)) ? String(selected) : '192');
}
function updateConverterExtension(format = $('#converterFormat').value) { $('#converterExtension').textContent = `.${format}`; }
function newConversion(info) {
  return { conversionId: `${Date.now()}-${Math.random().toString(16).slice(2)}`, source: info.path, sourceName: info.name, sourceType: info.type, duration: info.duration, durationLabel: info.durationLabel, coverStreamIndex: info.coverStreamIndex, outputName: safeBase(info.baseName), format: 'mp3', quality: '192', folder, duplicate: localStorage.getItem('ntc-duplicate') || 'rename', trimStart: '', trimEnd: '', normalize: false, gain: 0, eqBass: 0, eqMid: 0, eqTreble: 0, removeSilence: false, metadata: info.metadata || {}, cover: null, status: 'pronto' };
}
function currentEditingConversion() { return conversionQueue.find(item => item.conversionId === editingConversionId); }
function readEditorDraft() { return { format: $('#converterFormat').value, quality: $('#converterQuality').value, outputName: $('#converterOutputName').value, trimStart: $('#trimStart').value, trimEnd: $('#trimEnd').value, normalize: $('#normalizeAudio').checked, gain: $('#audioGain').value, eqBass: $('#eqBass').value, eqMid: $('#eqMid').value, eqTreble: $('#eqTreble').value, removeSilence: $('#removeSilence').checked, title: $('#metadataTitle').value, artist: $('#metadataArtist').value, album: $('#metadataAlbum').value, year: $('#metadataYear').value, genre: $('#metadataGenre').value }; }
function applyEditorDraft(draft) { $('#converterFormat').value = draft.format; conversionQualityOptions(draft.format, draft.quality); updateConverterExtension(draft.format); $('#converterQuality').value = draft.quality; $('#converterOutputName').value = draft.outputName; $('#trimStart').value = draft.trimStart; $('#trimEnd').value = draft.trimEnd; $('#normalizeAudio').checked = draft.normalize; $('#audioGain').value = draft.gain || 0; $('#eqBass').value = draft.eqBass || 0; $('#eqMid').value = draft.eqMid || 0; $('#eqTreble').value = draft.eqTreble || 0; $('#removeSilence').checked = Boolean(draft.removeSilence); $('#metadataTitle').value = draft.title; $('#metadataArtist').value = draft.artist; $('#metadataAlbum').value = draft.album; $('#metadataYear').value = draft.year; $('#metadataGenre').value = draft.genre; paintWaveform(); }
function updateEditorHistoryButtons() { $('#undoEdit').disabled = !editorUndoStack.length || currentEditingConversion()?.status === 'convertendo'; $('#redoEdit').disabled = !editorRedoStack.length || currentEditingConversion()?.status === 'convertendo'; }
function rememberEditorChange() { if (!editingConversionId) return; const next = readEditorDraft(); if (!editorDraft || JSON.stringify(next) === JSON.stringify(editorDraft)) return; editorUndoStack.push(editorDraft); editorUndoStack.splice(0, 80); editorRedoStack = []; editorDraft = next; updateEditorHistoryButtons(); }
function undoEditorChange() { const item = currentEditingConversion(); if (!item || item.status === 'convertendo' || !editorUndoStack.length) return; const currentDraft = readEditorDraft(); const previous = editorUndoStack.pop(); editorRedoStack.push(currentDraft); applyEditorDraft(previous); editorDraft = previous; updateEditorHistoryButtons(); }
function redoEditorChange() { const item = currentEditingConversion(); if (!item || item.status === 'convertendo' || !editorRedoStack.length) return; const currentDraft = readEditorDraft(); const next = editorRedoStack.pop(); editorUndoStack.push(currentDraft); applyEditorDraft(next); editorDraft = next; updateEditorHistoryButtons(); }
function readEditorTime(value, fallback) {
  const text = String(value || '').trim(); if (!text) return fallback;
  if (/^\d+(?:\.\d+)?$/.test(text)) return Number(text);
  const parts = text.split(':').map(Number); if (!parts.length || parts.length > 3 || parts.some(part => !Number.isFinite(part) || part < 0)) return fallback;
  return parts.reduce((total, part) => total * 60 + part, 0);
}
function formatEditorTime(seconds) { const total = Math.max(0, Math.round(seconds)); const hours = Math.floor(total / 3600); const minutes = Math.floor((total % 3600) / 60); const secs = total % 60; return [hours, minutes, secs].map(value => String(value).padStart(2, '0')).join(':'); }
function waveformBounds(item = currentEditingConversion()) {
  const duration = Number(item?.duration || 0); let start = readEditorTime($('#trimStart').value, 0); let end = readEditorTime($('#trimEnd').value, duration);
  start = Math.max(0, Math.min(start, duration)); end = Math.max(start, Math.min(end, duration)); return [start, end, duration];
}
function waveformViewport(duration, start, end) {
  if (!duration || waveformZoom <= 1) return [0, 1];
  const visible = 1 / waveformZoom; const selectionFocus = Math.max(0, Math.min(1, ((start + end) / 2) / duration)); const focus = waveformFocus === null ? selectionFocus : waveformFocus; const from = Math.max(0, Math.min(1 - visible, focus - visible / 2));
  return [from, from + visible];
}
function paintWaveform() {
  const item = currentEditingConversion(); const canvas = $('#waveformCanvas'); if (!item || !canvas) return;
  const rect = canvas.getBoundingClientRect(); const scale = window.devicePixelRatio || 1; const width = Math.max(1, Math.round(rect.width * scale)); const height = Math.max(1, Math.round(rect.height * scale));
  if (canvas.width !== width || canvas.height !== height) { canvas.width = width; canvas.height = height; }
  const ctx = canvas.getContext('2d'); const [start, end, duration] = waveformBounds(item); const [viewStart, viewEnd] = waveformViewport(duration, start, end); const toX = value => duration ? Math.max(0, Math.min(width, ((value / duration) - viewStart) / (viewEnd - viewStart) * width)) : 0; const startX = toX(start); const endX = duration ? toX(end) : width;
  ctx.clearRect(0, 0, width, height); ctx.fillStyle = '#161616'; ctx.fillRect(0, 0, width, height); ctx.fillStyle = '#242424'; ctx.fillRect(startX, 0, Math.max(0, endX - startX), height);
  const values = waveformData.length ? waveformData : Array.from({ length: 110 }, () => .025); const first = Math.max(0, Math.floor(viewStart * values.length)); const last = Math.max(first + 1, Math.min(values.length, Math.ceil(viewEnd * values.length))); const visibleValues = values.slice(first, last); const middle = height / 2; const barWidth = width / visibleValues.length;
  ctx.fillStyle = '#a8a8a8'; visibleValues.forEach((value, index) => { const x = index * barWidth; const amplitude = Math.max(2 * scale, value * height * .42); ctx.fillRect(x, middle - amplitude, Math.max(scale, barWidth - scale), amplitude * 2); });
  if (spectrumVisible) { ctx.fillStyle = 'rgba(230,230,230,.18)'; visibleValues.forEach((value, index) => { const x = index * barWidth; const bands = Math.max(1, Math.round(value * 6)); for (let band = 0; band < bands; band++) ctx.fillRect(x, 10 * scale + band * 12 * scale, Math.max(scale, barWidth - scale), 3 * scale); }); }
  ctx.fillStyle = '#f0f0f0'; [startX, endX].forEach(x => { ctx.fillRect(Math.round(x - scale), 0, scale * 2, height); ctx.beginPath(); ctx.moveTo(x - 6 * scale, 0); ctx.lineTo(x + 6 * scale, 0); ctx.lineTo(x, 8 * scale); ctx.closePath(); ctx.fill(); });
  if (playbackTime !== null && duration) { const playX = toX(playbackTime); ctx.fillStyle = '#ffffff'; ctx.fillRect(Math.round(playX - scale), 0, scale * 2, height); ctx.beginPath(); ctx.moveTo(playX - 6 * scale, height); ctx.lineTo(playX + 6 * scale, height); ctx.lineTo(playX, height - 8 * scale); ctx.closePath(); ctx.fill(); }
  $('#waveformDuration').textContent = duration ? formatEditorTime(duration) : '—'; $('#waveformSelection').textContent = duration && (start > 0 || end < duration) ? `${formatEditorTime(start)} — ${formatEditorTime(end)}` : 'Arquivo completo';
}
async function loadWaveform(item) {
  waveformFor = item.conversionId; waveformData = []; paintWaveform();
  try { const values = await window.ntc.getWaveform(item.source); if (waveformFor === item.conversionId) { waveformData = values; paintWaveform(); } }
  catch { if (waveformFor === item.conversionId) { waveformData = []; paintWaveform(); } }
}
function moveWaveformHandle(event) {
  const item = currentEditingConversion(); const canvas = $('#waveformCanvas'); if (!item || !canvas || !item.duration) return;
  const rect = canvas.getBoundingClientRect(); const ratio = Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)); const [start, end, duration] = waveformBounds(item); const [viewStart, viewEnd] = waveformViewport(duration, start, end); const point = (viewStart + ratio * (viewEnd - viewStart)) * duration; const topHandleArea = event.clientY - rect.top < 20;
  if (!waveformHandle) {
    const nearPlayback = playbackTime !== null && Math.abs(point - playbackTime) < duration * .035; waveformHandle = nearPlayback && !topHandleArea ? 'playback' : (Math.abs(point - start) <= Math.abs(point - end) ? 'start' : 'end');
  }
  if (waveformHandle === 'playback') { playbackTime = Math.max(start, Math.min(point, end)); if (previewAudio) previewAudio.currentTime = playbackTime; }
  if (waveformHandle === 'start') $('#trimStart').value = formatEditorTime(Math.min(point, Math.max(0, end - .1)));
  else if (waveformHandle === 'end') $('#trimEnd').value = formatEditorTime(Math.max(point, Math.min(duration, start + .1)));
  paintWaveform();
}
function sourceUrl(file) { return `file:///${file.replace(/\\/g, '/').split('/').map(encodeURIComponent).join('/')}`; }
function setupPreviewEffects() { if (!previewAudio) return; if (!previewAudioContext) previewAudioContext = new AudioContext(); if (!previewAudioSource) { previewAudioSource = previewAudioContext.createMediaElementSource(previewAudio); const bass = previewAudioContext.createBiquadFilter(); bass.type = 'lowshelf'; bass.frequency.value = 100; const mid = previewAudioContext.createBiquadFilter(); mid.type = 'peaking'; mid.frequency.value = 1000; mid.Q.value = 1; const treble = previewAudioContext.createBiquadFilter(); treble.type = 'highshelf'; treble.frequency.value = 6000; const gain = previewAudioContext.createGain(); previewAudioSource.connect(bass).connect(mid).connect(treble).connect(gain).connect(previewAudioContext.destination); previewEffectNodes = { bass, mid, treble, gain }; } updatePreviewEffects(); }
function updatePreviewEffects() { if (!previewEffectNodes) return; const value = id => Number($(`#${id}`).value) || 0; previewEffectNodes.bass.gain.setTargetAtTime(value('eqBass'), previewAudioContext.currentTime, .025); previewEffectNodes.mid.gain.setTargetAtTime(value('eqMid'), previewAudioContext.currentTime, .025); previewEffectNodes.treble.gain.setTargetAtTime(value('eqTreble'), previewAudioContext.currentTime, .025); previewEffectNodes.gain.gain.setTargetAtTime(Math.pow(10, value('audioGain') / 20), previewAudioContext.currentTime, .025); }
function releasePreviewEffects() { if (previewAudioSource) { try { previewAudioSource.disconnect(); } catch {} } previewAudioSource = null; previewEffectNodes = null; }
function updatePreviewButton() { $('#playSelection').textContent = previewAudio && !previewAudio.paused ? 'Ⅱ Pausar' : '▶ Ouvir seleção'; }
function stopPreview(keepCursor = false) { if (playbackFrame) cancelAnimationFrame(playbackFrame); playbackFrame = null; if (previewAudio) previewAudio.pause(); releasePreviewEffects(); previewAudio = null; if (!keepCursor) playbackTime = null; updatePreviewButton(); paintWaveform(); }
function animatePlayback(item) {
  if (!previewAudio || previewAudio.paused) return; const [, end] = waveformBounds(item); playbackTime = previewAudio.currentTime;
  if (playbackTime >= end) { previewAudio.pause(); playbackTime = end; updatePreviewButton(); paintWaveform(); return; }
  paintWaveform(); playbackFrame = requestAnimationFrame(() => animatePlayback(item));
}
function playSelectedRange() {
  const item = currentEditingConversion(); if (!item) return; const [start, end] = waveformBounds(item);
  if (previewAudio && !previewAudio.paused) { if (playbackFrame) cancelAnimationFrame(playbackFrame); previewAudio.pause(); previewAudio.currentTime = start; playbackTime = start; updatePreviewButton(); paintWaveform(); return; }
  const sameFile = previewAudio?.dataset.ntcSource === item.source;
  if (!sameFile) { if (previewAudio) previewAudio.pause(); releasePreviewEffects(); previewAudio = new Audio(sourceUrl(item.source)); previewAudio.dataset.ntcSource = item.source; setupPreviewEffects(); }
  if (!previewAudio || !Number.isFinite(end) || end <= start) return;
  const begin = () => { if (previewAudioContext?.state === 'suspended') previewAudioContext.resume(); updatePreviewEffects(); if (previewAudio.currentTime < start || previewAudio.currentTime >= end || !sameFile) previewAudio.currentTime = start; playbackTime = previewAudio.currentTime; previewAudio.play().then(() => { updatePreviewButton(); if (playbackFrame) cancelAnimationFrame(playbackFrame); animatePlayback(item); }).catch(() => { $('#waveformSelection').textContent = 'Não foi possível reproduzir este arquivo.'; updatePreviewButton(); }); };
  if (previewAudio.readyState >= 1) begin(); else previewAudio.addEventListener('loadedmetadata', begin, { once: true });
}
function seekPreview(offset) {
  const item = currentEditingConversion(); if (!item) return;
  if (!previewAudio) { playSelectedRange(); return; }
  const [start, end] = waveformBounds(item); const target = Math.max(start, Math.min(end, (Number.isFinite(previewAudio.currentTime) ? previewAudio.currentTime : start) + offset)); previewAudio.currentTime = target; playbackTime = target;
  if (target >= end && !previewAudio.paused) { previewAudio.pause(); updatePreviewButton(); }
  paintWaveform();
}
function renderConversionQueue() {
  const readyItems = conversionQueue.length; $('#conversionQueueCount').textContent = `${readyItems} ${readyItems === 1 ? 'item' : 'itens'}`; $('#abortConversions').disabled = !currentConversion; $('#abortConversions').classList.toggle('hidden', !currentConversion); $('#startConversions').disabled = !conversionQueue.some(item => ['pronto', 'erro'].includes(item.status));
  if (!readyItems) { $('#conversionQueueList').innerHTML = '<div class="empty-state"><p>Selecione arquivos para preparar conversões.</p></div>'; return; }
  $('#conversionQueueList').innerHTML = conversionQueue.map((item, index) => `<article class="queue-item conversion-item ${item.conversionId === editingConversionId ? 'selected' : ''}" data-conversion-edit="${item.conversionId}"><span class="queue-index">${index + 1}</span><div class="history-copy"><strong>${safeText(item.sourceName)}</strong><span>${safeText(item.sourceType)} · ${item.format.toUpperCase()} · ${safeText(item.quality === 'lossless' ? 'sem perdas' : `${item.quality} kbps`)} · ${safeText(item.status)}</span></div>${item.status === 'erro' ? `<button class="ghost-button" data-conversion-retry="${item.conversionId}">Tentar</button>` : ''}${item.status !== 'convertendo' ? `<button class="ghost-button" data-conversion-remove="${item.conversionId}">×</button>` : ''}</article>`).join('');
  $$('[data-conversion-edit]').forEach(element => element.onclick = event => { if (event.target.closest('button')) return; selectConversion(element.dataset.conversionEdit); });
  $$('[data-conversion-remove]').forEach(button => button.onclick = () => { conversionQueue = conversionQueue.filter(item => item.conversionId !== button.dataset.conversionRemove); if (editingConversionId === button.dataset.conversionRemove) { editingConversionId = null; $('#converterEditor').classList.add('hidden'); } renderConversionQueue(); });
  $$('[data-conversion-retry]').forEach(button => button.onclick = () => { const item = conversionQueue.find(entry => entry.conversionId === button.dataset.conversionRetry); if (item) { item.status = 'pronto'; renderConversionQueue(); } });
}
function loadConversionEditor(item) {
  if (!item) return; stopPreview(); waveformZoom = 1; waveformFocus = null; editingConversionId = item.conversionId; $('#converterEditor').classList.remove('hidden'); $('#editingMediaName').textContent = item.sourceName; $('#converterFormat').value = item.format; conversionQualityOptions(item.format, item.quality); updateConverterExtension(item.format); $('#converterOutputName').value = item.outputName; $('#trimStart').value = item.trimStart; $('#trimEnd').value = item.trimEnd; $('#normalizeAudio').checked = item.normalize; $('#audioGain').value = item.gain || 0; $('#eqBass').value = item.eqBass || 0; $('#eqMid').value = item.eqMid || 0; $('#eqTreble').value = item.eqTreble || 0; $('#removeSilence').checked = Boolean(item.removeSilence); $('#metadataTitle').value = item.metadata?.title || ''; $('#metadataArtist').value = item.metadata?.artist || ''; $('#metadataAlbum').value = item.metadata?.album || ''; $('#metadataYear').value = item.metadata?.year || ''; $('#metadataGenre').value = item.metadata?.genre || ''; $('#coverName').textContent = item.cover ? item.cover.split(/[\\/]/).pop() : 'Sem alteração'; $('#converterFolderPath').textContent = item.folder || 'Downloads'; editorUndoStack = []; editorRedoStack = []; editorDraft = readEditorDraft(); updateEditorHistoryButtons(); renderConversionQueue(); requestAnimationFrame(() => loadWaveform(item));
}
function selectConversion(id) { const item = conversionQueue.find(entry => entry.conversionId === id); if (item && item.status !== 'convertendo') loadConversionEditor(item); }
function renderMarkers() { const list = $('#markerList'); if (!audioMarkers.length) { list.innerHTML = '<span>Nenhum marcador criado.</span>'; return; } list.innerHTML = audioMarkers.map(marker => `<span class="marker-chip"><input data-marker-name="${marker.id}" value="${safeText(marker.name)}" aria-label="Nome do marcador" /><small>${formatEditorTime(marker.start)} — ${formatEditorTime(marker.end)}</small><button class="ghost-button" data-marker-remove="${marker.id}" type="button" aria-label="Remover marcador">×</button></span>`).join(''); $$('[data-marker-name]').forEach(input => input.oninput = () => { const marker = audioMarkers.find(entry => entry.id === input.dataset.markerName); if (marker) marker.name = input.value.trim() || 'Trecho'; }); $$('[data-marker-remove]').forEach(button => button.onclick = () => { audioMarkers = audioMarkers.filter(marker => marker.id !== button.dataset.markerRemove); renderMarkers(); }); }
function currentAudioSettings() { return { gain: $('#audioGain').value, eqBass: $('#eqBass').value, eqMid: $('#eqMid').value, eqTreble: $('#eqTreble').value, removeSilence: $('#removeSilence').checked, normalize: $('#normalizeAudio').checked }; }
function applyAudioSettings(settings) { $('#audioGain').value = settings.gain || 0; $('#eqBass').value = settings.eqBass || 0; $('#eqMid').value = settings.eqMid || 0; $('#eqTreble').value = settings.eqTreble || 0; $('#removeSilence').checked = Boolean(settings.removeSilence); $('#normalizeAudio').checked = Boolean(settings.normalize); rememberEditorChange(); }
function refreshAudioPresets() { const select = $('#audioPreset'); const selected = select.value; const saved = JSON.parse(localStorage.getItem('ntc-audio-presets') || '{}'); select.innerHTML = '<option value="">Preset de áudio</option><option value="voz">Voz</option><option value="musica">Música</option><option value="podcast">Podcast</option>' + Object.keys(saved).map(name => `<option value="saved:${safeText(name)}">${safeText(name)}</option>`).join(''); select.value = selected; }
const loadConversionEditorBase = loadConversionEditor; loadConversionEditor = function(item) { loadConversionEditorBase(item); spectrumVisible = false; $('#toggleSpectrum').textContent = 'Ver espectro'; audioMarkers = Array.isArray(item?.markers) ? structuredClone(item.markers) : []; renderMarkers(); };
const saveConversionEditsBase = saveConversionEdits; saveConversionEdits = function() { saveConversionEditsBase(); const item = currentEditingConversion(); if (item) item.markers = structuredClone(audioMarkers); };
function saveConversionEdits() {
  const item = currentEditingConversion(); if (!item || item.status === 'convertendo') return;
  item.format = $('#converterFormat').value; item.quality = $('#converterQuality').value; item.outputName = $('#converterOutputName').value.trim() || safeBase(item.sourceName.replace(/\.[^.]+$/, '')); item.trimStart = $('#trimStart').value.trim(); item.trimEnd = $('#trimEnd').value.trim(); item.normalize = $('#normalizeAudio').checked; item.gain = $('#audioGain').value; item.eqBass = $('#eqBass').value; item.eqMid = $('#eqMid').value; item.eqTreble = $('#eqTreble').value; item.removeSilence = $('#removeSilence').checked; item.metadata = { title: $('#metadataTitle').value.trim(), artist: $('#metadataArtist').value.trim(), album: $('#metadataAlbum').value.trim(), year: $('#metadataYear').value.trim(), genre: $('#metadataGenre').value.trim() }; item.duplicate = localStorage.getItem('ntc-duplicate') || 'rename'; renderConversionQueue();
}
async function addMediaFiles(files) {
  const results = await Promise.allSettled(files.map(file => window.ntc.inspectMedia(file))); let first = null; let failures = 0;
  results.forEach(result => { if (result.status === 'fulfilled' && !conversionQueue.some(item => item.source === result.value.path)) { const item = newConversion(result.value); conversionQueue.push(item); first ||= item; } else if (result.status === 'rejected') failures++; });
  if (first) loadConversionEditor(first); renderConversionQueue(); if (failures && !first) $('#conversionQueueList').innerHTML = '<div class="empty-state"><p>Não foi possível ler os arquivos selecionados.</p></div>';
}
async function chooseConverterFolder() { const chosen = await window.ntc.chooseDownloadFolder(); const item = currentEditingConversion(); if (chosen && item) { folder = chosen; localStorage.setItem('ntc-folder', folder); item.folder = chosen; syncSettings(); $('#converterFolderPath').textContent = chosen; } }
async function chooseCover() { const item = currentEditingConversion(); if (!item) return; const cover = await window.ntc.chooseCoverFile(); if (cover) { item.cover = cover; $('#coverName').textContent = cover.split(/[\\/]/).pop(); } }
async function startNextConversion() {
  if (currentConversion) return; const item = conversionQueue.find(entry => entry.status === 'pronto'); if (!item) return;
  currentConversion = item; item.status = 'convertendo'; $('#conversionProgress').classList.remove('hidden'); $('#conversionStatus').textContent = 'CONVERTENDO'; $('#conversionTitle').textContent = item.sourceName; $('#conversionMeta').textContent = `${item.sourceType} → ${item.format.toUpperCase()} · ${item.quality === 'lossless' ? 'sem perdas' : `${item.quality} kbps`}`; $('#conversionPercent').textContent = '0%'; $('#conversionProgressBar').style.width = '0%'; $('#conversionEta').textContent = '—'; $('#cancelConversion').textContent = 'Cancelar'; $('#cancelConversion').onclick = () => window.ntc.cancelConversion(item.conversionId); renderConversionQueue();
  try { await window.ntc.startConversion(item); } catch (error) { const message = cleanError(error); item.status = message.includes('cancelada') ? 'cancelado' : 'erro'; const wasAborted = abortedConversions.delete(item.conversionId); if (item.status === 'erro') addHistory({ title: item.outputName, type: 'audio', format: item.format, quality: item.quality === 'lossless' ? 'sem perdas' : `${item.quality} kbps`, size: '—', time: 'Agora', source: item.source, operation: 'conversion', state: 'erro' }); currentConversion = null; $('#conversionStatus').textContent = wasAborted ? 'INTERROMPIDO' : item.status.toUpperCase(); $('#conversionMeta').textContent = wasAborted ? 'Conversões interrompidas pelo usuário.' : message; renderConversionQueue(); setTimeout(startNextConversion, 0); }
}
window.ntc.onConversionEvent(update => {
  if (!currentConversion || update.conversionId !== currentConversion.conversionId || abortedConversions.has(update.conversionId)) return;
  if (update.status === 'converting') { $('#conversionPercent').textContent = `${Math.round(update.percent || 0)}%`; $('#conversionProgressBar').style.width = `${update.percent || 0}%`; $('#conversionEta').textContent = update.eta || '—'; }
  if (update.status === 'complete') { const completed = currentConversion; addHistory({ title: completed.outputName, type: 'audio', format: completed.format, quality: completed.quality === 'lossless' ? 'sem perdas' : `${completed.quality} kbps`, size: formatBytes(update.size), file: update.file, time: 'Agora', source: completed.source, operation: 'conversion' }); conversionQueue = conversionQueue.filter(item => item.conversionId !== completed.conversionId); currentConversion = null; if (editingConversionId === completed.conversionId) { editingConversionId = null; $('#converterEditor').classList.add('hidden'); } $('#conversionStatus').textContent = 'CONCLUÍDO'; $('#conversionPercent').textContent = '100%'; $('#conversionProgressBar').style.width = '100%'; $('#conversionEta').textContent = '0s'; $('#conversionTitle').textContent = 'Conversão concluída'; $('#conversionMeta').textContent = `Salvo como ${update.filename}`; $('#cancelConversion').textContent = 'Abrir arquivo'; $('#cancelConversion').onclick = () => window.ntc.openFile(update.file); renderConversionQueue(); if ($('#openFolderAfter').checked) window.ntc.openFolder(completed.folder); setTimeout(startNextConversion, 0); }
});

function openPlaylistSelection() { if (!playlist) return; $('#playlistTitle').textContent = playlist.title; $('#playlistSummary').textContent = `${playlist.entries.length} músicas disponíveis`; $('#playlistList').innerHTML = playlist.entries.map((item, index) => `<label class="playlist-item"><input type="checkbox" data-playlist-entry="${index}" checked><span class="playlist-number">${index + 1}</span><img src="${item.thumbnail || ''}" alt=""><span><strong>${safeText(item.title)}</strong><small>${safeText(item.channel || 'YouTube')} · ${safeText(item.duration)}</small></span></label>`).join(''); $$('.nav-item').forEach(item => item.classList.remove('active')); $$('.view').forEach(view => view.classList.remove('active')); $('#playlistView').classList.add('active'); }
function toolId() { return `${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function renderMediaQueue(kind) { const video = kind === 'video'; const items = video ? videoQueue : imageQueue; const list = $(`#${kind}QueueList`); $(`#${kind}QueueCount`).textContent = `${items.length} ${items.length === 1 ? 'item' : 'itens'}`; $(`#start${video ? 'Videos' : 'Images'}`).disabled = !items.some(item => ['pronto', 'erro'].includes(item.status)); if (!items.length) { list.innerHTML = `<div class="empty-state"><p>Adicione ${video ? 'vídeos' : 'imagens'} para converter.</p></div>`; return; } list.innerHTML = items.map((item, index) => `<article class="queue-item conversion-item ${item.status === 'erro' ? 'has-error' : ''}"><span class="queue-index">${index + 1}</span><div class="history-copy"><strong>${safeText(item.name)}</strong><span>${safeText(item.status === 'erro' && item.error ? item.error : `${item.meta} · ${item.status}`)}</span></div>${item.status === 'erro' ? `<button class="ghost-button" data-${kind}-retry="${item.id}">Tentar novamente</button>` : ''}${item.status !== 'convertendo' ? `<button class="ghost-button" data-${kind}-remove="${item.id}" aria-label="Remover">Remover</button>` : ''}</article>`).join(''); $$(`[data-${kind}-remove]`).forEach(button => button.onclick = () => { if (video) videoQueue = videoQueue.filter(item => item.id !== button.dataset[`${kind}Remove`]); else imageQueue = imageQueue.filter(item => item.id !== button.dataset[`${kind}Remove`]); renderMediaQueue(kind); if (!video) scheduleImagePreview(); }); $$(`[data-${kind}-retry]`).forEach(button => button.onclick = async () => { const item = items.find(entry => entry.id === button.dataset[`${kind}Retry`]); if (!item) return; item.status = 'pronto'; item.error = ''; if (video) { renderMediaQueue('video'); startNextVideo(); } else { renderMediaQueue('image'); await startImagesWithWarning(); } }); }
async function addVideos(files) { const results = await Promise.allSettled(files.map(file => window.ntc.inspectVideo(file))); let invalid = 0; results.forEach(result => { if (result.status !== 'fulfilled') { invalid++; return; } const info = result.value; if (!videoQueue.some(item => item.source === info.path)) videoQueue.push({ id: toolId(), source: info.path, name: info.name || info.path.split(/[\\/]/).pop(), meta: `${info.width || '—'}×${info.height || '—'} · ${formatEditorTime(info.duration || 0)}`, duration: info.duration || 0, outputName: safeBase((info.name || 'video').replace(/\.[^.]+$/, '')), folder, duplicate: localStorage.getItem('ntc-duplicate') || 'rename', status: 'pronto' }); }); renderMediaQueue('video'); if (invalid) showToast('Alguns arquivos não são vídeos compatíveis.'); }
async function addImages(files) { const results = await Promise.allSettled(files.map(file => window.ntc.inspectImage(file))); let invalid = 0; results.forEach(result => { if (result.status !== 'fulfilled') { invalid++; return; } const info = result.value; if (!imageQueue.some(item => item.source === info.path)) imageQueue.push({ id: toolId(), source: info.path, name: info.name || info.path.split(/[\\/]/).pop(), sourceWidth: info.width, sourceHeight: info.height, meta: `${info.width || '—'}×${info.height || '—'}`, outputName: safeBase((info.name || 'imagem').replace(/\.[^.]+$/, '')), folder, duplicate: localStorage.getItem('ntc-duplicate') || 'rename', status: 'pronto' }); }); renderMediaQueue('image'); if (invalid) showToast('Alguns arquivos não são imagens compatíveis.'); }
function startNextVideo() { if (currentVideo) return; const item = videoQueue.find(entry => entry.status === 'pronto'); if (!item) return; currentVideo = item; Object.assign(item, { format: $('#videoFormat').value, codec: $('#videoCodec').value, resolution: $('#videoResolution').value, quality: $('#videoQuality').value, audioMode: $('#videoAudio').value, folder, duplicate: localStorage.getItem('ntc-duplicate') || 'rename', status: 'convertendo', error: '' }); $('#videoProgress').classList.remove('hidden'); $('#videoStatus').textContent = 'CONVERTENDO'; $('#videoTitle').textContent = item.name; $('#videoPercent').textContent = '0%'; $('#videoProgressBar').style.width = '0%'; $('#cancelVideo').onclick = () => window.ntc.cancelVideoConversion(item.id); renderMediaQueue('video'); window.ntc.startVideoConversion(item).catch(error => { item.status = 'erro'; item.error = cleanError(error); currentVideo = null; $('#videoStatus').textContent = 'ERRO'; $('#videoPercent').textContent = 'ERRO'; $('#videoMeta').textContent = item.error; renderMediaQueue('video'); setTimeout(startNextVideo, 0); }); }
function startNextImage() { if (currentImage) return; const item = imageQueue.find(entry => entry.status === 'pronto'); if (!item) return; currentImage = item; Object.assign(item, { format: $('#imageFormat').value, quality: $('#imageQuality').value, scale: $('#imageScale').value, width: $('#imageWidth').value, height: $('#imageHeight').value, keepRatio: $('#imageKeepRatio').checked, folder, duplicate: localStorage.getItem('ntc-duplicate') || 'rename', status: 'convertendo', error: '' }); $('#imageProgress').classList.remove('hidden'); $('#imageStatus').textContent = 'CONVERTENDO'; $('#imageTitle').textContent = item.name; $('#imagePercent').textContent = '0%'; $('#imageProgressBar').style.width = '0%'; $('#cancelImage').textContent = 'Cancelar'; $('#cancelImage').onclick = () => window.ntc.cancelImageConversion(item.id); renderMediaQueue('image'); window.ntc.startImageConversion(item).catch(error => { const reason = cleanError(error); item.status = 'erro'; item.error = reason; lastFailedImage = item; currentImage = null; $('#imageStatus').textContent = 'FALHOU'; $('#imagePercent').textContent = 'ERRO'; $('#imageProgressBar').style.width = '100%'; $('#imageMeta').textContent = `${reason} Ajuste tamanho, escala ou formato e tente novamente.`; $('#cancelImage').textContent = 'Tentar com ajustes atuais'; $('#cancelImage').onclick = async () => { item.status = 'pronto'; item.error = ''; lastFailedImage = null; $('#imageStatus').textContent = 'TENTANDO NOVAMENTE'; $('#imagePercent').textContent = '0%'; $('#imageProgressBar').style.width = '0%'; renderMediaQueue('image'); await startImagesWithWarning(); }; renderMediaQueue('image'); showToast('A conversão falhou. O motivo e a ação para tentar novamente estão na fila.'); }); }
window.ntc.onVideoEvent(update => { if (!currentVideo || update.id !== currentVideo.id) return; if (update.status === 'converting') { $('#videoPercent').textContent = `${Math.round(update.percent || 0)}%`; $('#videoProgressBar').style.width = `${update.percent || 0}%`; } if (update.status === 'complete') { const item = currentVideo; addHistory({ title: item.outputName, type: 'video', format: item.format, quality: item.quality, size: formatBytes(update.size), file: update.file, source: item.source, operation: 'conversion', time: 'Agora' }); videoQueue = videoQueue.filter(entry => entry.id !== item.id); currentVideo = null; $('#videoStatus').textContent = 'CONCLUÍDO'; $('#videoPercent').textContent = '100%'; $('#videoProgressBar').style.width = '100%'; $('#videoMeta').textContent = `Salvo como ${update.filename}`; if ($('#openFolderAfter').checked) window.ntc.openFolder(item.folder); renderMediaQueue('video'); setTimeout(startNextVideo, 0); } });
window.ntc.onImageEvent(update => { if (!currentImage || update.id !== currentImage.id) return; if (update.status === 'converting') { $('#imagePercent').textContent = `${Math.round(update.percent || 0)}%`; $('#imageProgressBar').style.width = `${update.percent || 0}%`; } if (update.status === 'complete') { const item = currentImage; addHistory({ title: item.outputName, type: 'image', format: item.format, quality: `${item.quality}%`, size: formatBytes(update.size), file: update.file, source: item.source, operation: 'conversion', time: 'Agora' }); imageQueue = imageQueue.filter(entry => entry.id !== item.id); currentImage = null; $('#imageStatus').textContent = 'CONCLUÍDO'; $('#imagePercent').textContent = '100%'; $('#imageProgressBar').style.width = '100%'; $('#imageMeta').textContent = `Salvo em ${item.folder} · ${update.filename}`; $('#cancelImage').textContent = 'Abrir pasta'; $('#cancelImage').onclick = () => window.ntc.openFolder(item.folder); if ($('#openFolderAfter').checked) window.ntc.openFolder(item.folder); renderMediaQueue('image'); scheduleImagePreview(); setTimeout(startNextImage, 0); } });
function bindDropzone(id, choose, add) { const element = $(`#${id}`); element.onclick = async () => add(await choose()); element.onkeydown = async event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); add(await choose()); } }; ['dragenter', 'dragover'].forEach(name => element.addEventListener(name, event => { event.preventDefault(); event.stopPropagation(); element.classList.add('dragging'); })); ['dragleave', 'drop'].forEach(name => element.addEventListener(name, event => { event.preventDefault(); event.stopPropagation(); element.classList.remove('dragging'); })); element.addEventListener('drop', event => { const files = [...event.dataTransfer.files].map(file => file.path || window.ntc.pathForFile(file)).filter(Boolean); if (files.length) add(files); else showToast('Não foi possível acessar o arquivo arrastado. Use Selecionar imagens.'); }); }
$('#selectPlaylist').onclick = openPlaylistSelection;
$('#resumeQueue').onclick = () => { queue.forEach(item => { if (['pausado', 'erro', 'cancelado'].includes(item.status)) { item.status = 'aguardando'; item.percent = 0; } }); persistQueue(); renderQueue(); startNext(); };
$('#abortQueue').onclick = () => { if (current) { abortedDownloads.add(current.downloadId); window.ntc.cancelDownload(current.downloadId); } queue = []; localStorage.removeItem('ntc-download-queue'); renderQueue(); $('#progressCard').classList.add('hidden'); };
$('#selectAllPlaylist').onclick = () => $$('[data-playlist-entry]').forEach(item => { item.checked = true; });
$('#clearPlaylistSelection').onclick = () => $$('[data-playlist-entry]').forEach(item => { item.checked = false; });
$('#addSelectedPlaylist').onclick = () => { if (!playlist) return; const chosen = $$('[data-playlist-entry]:checked').map(item => playlist.entries[Number(item.dataset.playlistEntry)]); enqueueSources(chosen); $('#videoUrl').value = ''; preview = null; playlist = null; $('#previewCard').classList.add('hidden'); $('#selectPlaylist').classList.add('hidden'); $$('.view').forEach(view => view.classList.remove('active')); $('#downloaderView').classList.add('active'); $$('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === 'downloader')); };
$('#videoUrl').addEventListener('input', () => { clearTimeout(previewTimer); previewTimer = setTimeout(loadPreview, 650); });
$('#downloadForm').addEventListener('submit', event => { event.preventDefault(); addToQueue(); });
$$('input[name="downloadType"]').forEach(input => input.addEventListener('change', setFormatOptions));
$('#chooseFolder').onclick = chooseFolder; $('#chooseFolderSettings').onclick = chooseFolder;
$('#openFolderAfter').onchange = event => localStorage.setItem('ntc-open-folder', event.target.checked); $('#duplicatePolicy').onchange = event => localStorage.setItem('ntc-duplicate', event.target.value); $('#filenameTemplate').onchange = event => { localStorage.setItem('ntc-filename-template', event.target.value); showToast('Modelo de nome atualizado.'); };
async function clearHistoryWithConfirm() { if (!history.length) { showToast('O histórico já está vazio.'); return; } if (!await confirmAction('Limpar histórico?', 'Os registros locais serão removidos. Os arquivos baixados não serão apagados.', 'Limpar')) return; history.length = 0; localStorage.removeItem('ntc-history'); renderHistory(); showToast('Histórico limpo.'); }
async function resetPreferences() { if (!await confirmAction('Restaurar preferências?', 'A pasta, a abertura automática, a regra de duplicatas e o modelo de nome voltarão ao padrão.', 'Restaurar')) return; localStorage.removeItem('ntc-folder'); localStorage.removeItem('ntc-open-folder'); localStorage.removeItem('ntc-duplicate'); localStorage.removeItem('ntc-filename-template'); folder = await window.ntc.defaultDownloadFolder(); localStorage.setItem('ntc-folder', folder); syncSettings(); showToast('Preferências restauradas.'); }
async function checkTools() { const button = $('#checkTools'); button.disabled = true; $('#toolVersions').textContent = 'Verificando yt-dlp, FFmpeg e FFprobe…'; try { const version = await window.ntc.toolVersions(); if (version.error) { $('#toolVersions').textContent = `Erro: ${cleanError(version.error)}`; showToast('Não foi possível verificar as ferramentas.'); } else { $('#toolVersions').textContent = `yt-dlp ${version.ytdlp} · FFmpeg ${version.ffmpeg.match(/ffmpeg version\s+([^\s]+)/i)?.[1] || 'instalado'} · FFprobe ${version.ffprobe.match(/ffprobe version\s+([^\s]+)/i)?.[1] || 'instalado'}`; showToast('Ferramentas verificadas.'); } } catch (error) { $('#toolVersions').textContent = `Erro: ${cleanError(error)}`; showToast('Não foi possível verificar as ferramentas.'); } finally { button.disabled = false; } }
async function checkUpdates() { const button = $('#checkUpdates'); button.disabled = true; $('#updateStatus').textContent = 'Verificando atualizações…'; try { showUpdateNotice(await window.ntc.checkForUpdates()); } catch { showUpdateNotice({ status: 'error', message: 'Não foi possível verificar atualizações agora.' }); } finally { button.disabled = false; } }
let imagePreviewTimer = null;
async function updateImagePreview() { const item = imageQueue[0]; if (!item) { $('#imagePreviewCard').classList.add('hidden'); return; } $('#imagePreviewCard').classList.remove('hidden'); $('#imagePreviewTitle').textContent = item.name; $('#imagePreviewOriginal').src = sourceUrl(item.source); $('#imagePreviewMeta').textContent = 'Gerando o resultado com estes ajustes…'; try { const preview = await window.ntc.previewImage({ source: item.source, format: $('#imageFormat').value, quality: $('#imageQuality').value, scale: $('#imageScale').value, width: $('#imageWidth').value, height: $('#imageHeight').value, keepRatio: $('#imageKeepRatio').checked }); $('#imagePreview').src = preview.dataUrl; $('#imagePreviewMeta').textContent = `Resultado: ${preview.width || 'original'} × ${preview.height || 'original'} · qualidade ${Math.max(1, Math.min(100, Number($('#imageQuality').value) || 85))}%`; } catch (error) { $('#imagePreviewMeta').textContent = cleanError(error); } }
function scheduleImagePreview() { clearTimeout(imagePreviewTimer); imagePreviewTimer = setTimeout(updateImagePreview, 260); }
$('#themePreference').onchange = event => { localStorage.setItem('ntc-theme', event.target.value); syncSettings(); showToast(`Tema ${event.target.value === 'light' ? 'claro' : 'escuro'} aplicado.`); };
$('#addMarker').onclick = () => { const [start, end] = waveformBounds(); if (end <= start) return; audioMarkers.push({ id: toolId(), name: `Trecho ${audioMarkers.length + 1}`, start, end }); renderMarkers(); showToast('Marcador criado para a seleção atual.'); };
$('#exportMarkers').onclick = () => { const item = currentEditingConversion(); if (!item || !audioMarkers.length) { showToast('Crie ao menos um marcador primeiro.'); return; } saveConversionEdits(); audioMarkers.forEach(marker => { const outputName = safeBase(`${item.outputName} - ${marker.name}`); conversionQueue.push({ ...structuredClone(item), conversionId: toolId(), outputName, trimStart: formatEditorTime(marker.start), trimEnd: formatEditorTime(marker.end), markers: [], status: 'pronto' }); }); renderConversionQueue(); startNextConversion(); showToast(`${audioMarkers.length} trechos adicionados à fila.`); };
$('#applyToAudioQueue').onclick = () => { const item = currentEditingConversion(); if (!item) return; saveConversionEdits(); const settings = currentAudioSettings(); conversionQueue.filter(entry => entry.conversionId !== item.conversionId && entry.status === 'pronto').forEach(entry => Object.assign(entry, settings)); renderConversionQueue(); showToast('Ajustes aplicados aos itens prontos da fila.'); };
$('#toggleSpectrum').onclick = () => { spectrumVisible = !spectrumVisible; $('#toggleSpectrum').textContent = spectrumVisible ? 'Ocultar espectro' : 'Ver espectro'; paintWaveform(); };
$('#audioPreset').onchange = event => { const basic = { voz: { gain: 1, eqBass: -2, eqMid: 3, eqTreble: 2, removeSilence: false }, musica: { gain: 0, eqBass: 2, eqMid: 0, eqTreble: 2, removeSilence: false }, podcast: { gain: 2, eqBass: -1, eqMid: 3, eqTreble: 1, removeSilence: true } }; const saved = JSON.parse(localStorage.getItem('ntc-audio-presets') || '{}'); const value = event.target.value; if (value) { applyAudioSettings(value.startsWith('saved:') ? saved[value.slice(6)] : basic[value]); showToast('Preset aplicado.'); } };
$('#saveAudioPreset').onclick = () => { const name = window.prompt('Nome do preset'); if (!name?.trim()) return; const presets = JSON.parse(localStorage.getItem('ntc-audio-presets') || '{}'); presets[name.trim().slice(0, 40)] = currentAudioSettings(); localStorage.setItem('ntc-audio-presets', JSON.stringify(presets)); refreshAudioPresets(); $('#audioPreset').value = `saved:${name.trim().slice(0, 40)}`; showToast('Preset salvo neste computador.'); };
async function chooseToolFolder() { const chosen = await window.ntc.chooseDownloadFolder(); if (!chosen) return; folder = chosen; localStorage.setItem('ntc-folder', folder); syncSettings(); refreshSpaceHint(); showToast('Pasta de destino atualizada.'); }
function wouldCreateLargeImage() { const scale = Math.max(1, Number($('#imageScale').value) || 100) / 100; const typedWidth = Number($('#imageWidth').value); const typedHeight = Number($('#imageHeight').value); return imageQueue.some(item => Math.max(typedWidth || Math.round((item.sourceWidth || 0) * scale), typedHeight || Math.round((item.sourceHeight || 0) * scale)) > 16384); }
async function startImagesWithWarning() { if (!imageQueue.some(item => item.status === 'pronto') && lastFailedImage) { if (!imageQueue.some(item => item.id === lastFailedImage.id)) imageQueue.push(lastFailedImage); lastFailedImage.status = 'pronto'; lastFailedImage = null; renderMediaQueue('image'); } if (wouldCreateLargeImage()) { const accepted = await confirmAction('Imagem muito grande', 'Este tamanho pode consumir muita memória, travar o computador ou falhar por limite do formato. Deseja tentar mesmo assim?', 'Tentar mesmo assim'); if (!accepted) return; } startNextImage(); }
$('#chooseVideo').onclick = async () => addVideos(await window.ntc.chooseVideoFiles()); $('#chooseImages').onclick = async () => { await addImages(await window.ntc.chooseImageFiles()); scheduleImagePreview(); }; $('#chooseVideoFolder').onclick = chooseToolFolder; $('#chooseImageFolder').onclick = chooseToolFolder; bindDropzone('videoDropzone', () => window.ntc.chooseVideoFiles(), addVideos); bindDropzone('imageDropzone', () => window.ntc.chooseImageFiles(), async files => { await addImages(files); scheduleImagePreview(); }); ['imageFormat', 'imageQuality', 'imageScale', 'imageWidth', 'imageHeight', 'imageKeepRatio'].forEach(id => $(`#${id}`).addEventListener(id === 'imageKeepRatio' ? 'change' : 'input', scheduleImagePreview)); $('#startVideos').onclick = startNextVideo; $('#startImages').onclick = startImagesWithWarning;
$('#clearHistory').onclick = clearHistoryWithConfirm; $('#clearHistorySettings').onclick = clearHistoryWithConfirm; $('#clearHistoryPage').onclick = clearHistoryWithConfirm; $('#resetPreferences').onclick = resetPreferences; $('#checkTools').onclick = checkTools; $('#checkUpdates').onclick = checkUpdates;
$('#chooseRecorderFolder').onclick = async () => { const chosen = await window.ntc.chooseDownloadFolder(); if (!chosen) return; localStorage.setItem('ntc-recorder-folder', chosen); syncSettings(); showToast('Pasta de gravações atualizada.'); };
$('#chooseCompression').onclick = async () => addCompressionFiles(await window.ntc.chooseCompressorFiles()); $('#compressionDropzone').onclick = async () => addCompressionFiles(await window.ntc.chooseCompressorFiles()); bindDropzone('compressionDropzone', () => window.ntc.chooseCompressorFiles(), addCompressionFiles); $('#compressionPreset').onchange = () => { applyCompressionPreset(); updateCompressionPreview(); }; ['compressionResolution', 'compressionFps', 'compressionCrf', 'compressionBitrate', 'compressionImageQuality', 'compressionImageScale'].forEach(id => $(`#${id}`).addEventListener('input', updateCompressionPreview)); $('#startCompression').onclick = startCompressionQueue; $('#chooseCompressionFolder').onclick = async () => { const chosen = await window.ntc.chooseDownloadFolder(); if (chosen) { localStorage.setItem('ntc-compression-folder', chosen); $('#compressionFolderPath').textContent = chosen; } };
$('#recordResolution').value = localStorage.getItem('ntc-record-resolution') || 'original'; $('#recordResolution').addEventListener('change', event => localStorage.setItem('ntc-record-resolution', event.target.value)); $('#toggleRecording').onclick = startScreenRecording;
$('#recordShortcut').value = localStorage.getItem('ntc-record-shortcut') || 'Ctrl+Shift+R'; $('#recordShortcut').addEventListener('change', () => configureRecordingShortcut());
window.ntc.onScreenHotkey(() => startScreenRecording());
window.ntc.onScreenCloseRequest(async () => { if (!screenRecorder.recorder) { window.ntc.forceCloseWindow(); return; } const close = await confirmAction('Gravação em andamento', 'Deseja finalizar e salvar a gravação antes de fechar o aplicativo?', 'Salvar e fechar'); if (close) { await stopScreenRecording(); window.ntc.forceCloseWindow(); } });
$('#openChangelog').onclick = openChangelog;
$('#closeChangelog').onclick = () => $('#changelogDialog').classList.add('hidden');
$('#dismissUpdate').onclick = () => $('#updateNotice').classList.add('hidden');
$('#updateAction').onclick = async () => { const status = $('#updateAction').dataset.updateStatus; if (status === 'downloaded') { window.ntc.installUpdate(); return; } if (status === 'available') showUpdateNotice(await window.ntc.downloadUpdate()); };
window.ntc.onUpdateEvent(showUpdateNotice);
$('#historyFilter').onchange = renderHistory;
$('#confirmCancel').onclick = () => closeConfirm(false); $('#confirmAccept').onclick = () => closeConfirm(true);
$$('.nav-item[data-view]').forEach(button => button.onclick = () => { $$('.nav-item').forEach(item => item.classList.remove('active')); button.classList.add('active'); $$('.view').forEach(view => view.classList.remove('active')); $(`#${button.dataset.view}View`).classList.add('active'); });
$$('[data-open-tool]').forEach(button => button.onclick = () => { const target = button.dataset.openTool; $$('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === target)); $$('.view').forEach(view => view.classList.toggle('active', view.id === `${target}View`)); });
$('#minimizeWindow').onclick = () => window.ntc.minimizeWindow(); $('#maximizeWindow').onclick = async () => { const maximized = await window.ntc.toggleMaximize(); $('#maximizeWindow').textContent = maximized ? '❐' : '□'; $('#maximizeWindow').setAttribute('aria-label', maximized ? 'Restaurar' : 'Maximizar'); }; $('#closeWindow').onclick = () => window.ntc.closeWindow();
$('#chooseMedia').onclick = async () => addMediaFiles(await window.ntc.chooseMediaFiles());
$('#mediaDropzone').onclick = async () => addMediaFiles(await window.ntc.chooseMediaFiles());
$('#mediaDropzone').onkeydown = async event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); addMediaFiles(await window.ntc.chooseMediaFiles()); } };
['dragenter', 'dragover'].forEach(name => $('#mediaDropzone').addEventListener(name, event => { event.preventDefault(); $('#mediaDropzone').classList.add('dragging'); }));
['dragleave', 'drop'].forEach(name => $('#mediaDropzone').addEventListener(name, event => { event.preventDefault(); $('#mediaDropzone').classList.remove('dragging'); }));
$('#mediaDropzone').addEventListener('drop', event => { const files = [...event.dataTransfer.files].map(file => file.path || window.ntc.pathForFile(file)).filter(Boolean); if (files.length) addMediaFiles(files); else showToast('Não foi possível acessar o arquivo arrastado. Use Selecionar arquivos.'); });
$('#converterFormat').onchange = event => { conversionQualityOptions(event.target.value); updateConverterExtension(event.target.value); rememberEditorChange(); };
['trimStart', 'trimEnd'].forEach(id => $(`#${id}`).addEventListener('input', () => { paintWaveform(); rememberEditorChange(); }));
['converterQuality', 'converterOutputName', 'audioGain', 'eqBass', 'eqMid', 'eqTreble', 'metadataTitle', 'metadataArtist', 'metadataAlbum', 'metadataYear', 'metadataGenre'].forEach(id => $(`#${id}`).addEventListener('input', rememberEditorChange));
['audioGain', 'eqBass', 'eqMid', 'eqTreble'].forEach(id => $(`#${id}`).addEventListener('input', updatePreviewEffects));
$('#removeSilence').addEventListener('change', rememberEditorChange);
$('#normalizeAudio').addEventListener('change', rememberEditorChange);
$('#waveformCanvas').addEventListener('pointerdown', event => { waveformHandle = null; $('#waveformCanvas').setPointerCapture(event.pointerId); moveWaveformHandle(event); });
$('#waveformCanvas').addEventListener('pointermove', event => { if (event.buttons) moveWaveformHandle(event); });
['pointerup', 'pointercancel'].forEach(name => $('#waveformCanvas').addEventListener(name, () => { waveformHandle = null; }));
$('#waveformCanvas').addEventListener('wheel', event => { event.preventDefault(); event.stopPropagation(); const item = currentEditingConversion(); if (!item?.duration) return; const rect = $('#waveformCanvas').getBoundingClientRect(); const ratio = Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)); const [start, end, duration] = waveformBounds(item); const [from, to] = waveformViewport(duration, start, end); waveformFocus = from + ratio * (to - from); waveformZoom = Math.max(1, Math.min(8, waveformZoom + (event.deltaY < 0 ? .5 : -.5))); paintWaveform(); }, { passive: false, capture: true });
$('#rewindPreview').onclick = () => seekPreview(-5); $('#forwardPreview').onclick = () => seekPreview(5);
$('#playSelection').onclick = playSelectedRange;
$('#undoEdit').onclick = undoEditorChange; $('#redoEdit').onclick = redoEditorChange;
$('#saveConversionEdits').onclick = () => { saveConversionEdits(); startNextConversion(); }; $('#chooseConverterFolder').onclick = chooseConverterFolder; $('#chooseCover').onclick = chooseCover;
$('#removeCover').onclick = () => { const item = currentEditingConversion(); if (item) { item.cover = null; $('#coverName').textContent = 'Sem alteração'; } };
$('#startConversions').onclick = () => { saveConversionEdits(); startNextConversion(); };
$('#abortConversions').onclick = () => { if (currentConversion) { abortedConversions.add(currentConversion.conversionId); window.ntc.cancelConversion(currentConversion.conversionId); } conversionQueue = []; editingConversionId = null; $('#converterEditor').classList.add('hidden'); $('#conversionProgress').classList.add('hidden'); renderConversionQueue(); };
$('#dismissEditAfterDownload').onclick = hideEditAfterDownload;
$('#openDownloadedInEditor').onclick = async () => { const item = downloadedAudioToEdit; hideEditAfterDownload(); if (!item) return; await addMediaFiles([item.file]); $$('.nav-item').forEach(button => button.classList.toggle('active', button.dataset.view === 'converter')); $$('.view').forEach(view => view.classList.toggle('active', view.id === 'converterView')); };
document.addEventListener('keydown', event => {
  const tag = event.target?.tagName; const editorActive = $('#converterView').classList.contains('active'); if (!editorActive) return;
  if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'z' && !event.shiftKey) { event.preventDefault(); undoEditorChange(); return; }
  if ((event.ctrlKey || event.metaKey) && (event.key.toLowerCase() === 'y' || (event.key.toLowerCase() === 'z' && event.shiftKey))) { event.preventDefault(); redoEditorChange(); return; }
  if (['INPUT', 'SELECT', 'TEXTAREA', 'BUTTON'].includes(tag)) return;
  if (event.code === 'Space') { event.preventDefault(); playSelectedRange(); return; }
  if (event.key === 'ArrowLeft') { event.preventDefault(); seekPreview(-5); }
  if (event.key === 'ArrowRight') { event.preventDefault(); seekPreview(5); }
});
document.addEventListener('keydown', async event => {
  const downloaderActive = $('#downloaderView').classList.contains('active'); const tag = event.target?.tagName;
  if (downloaderActive && (event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'v' && !['INPUT', 'TEXTAREA'].includes(tag)) { try { const text = await navigator.clipboard.readText(); if (text) { event.preventDefault(); $('#videoUrl').value = text.trim(); $('#videoUrl').focus(); loadPreview(); } } catch { showToast('Cole o link diretamente no campo.'); } }
  if (event.key === 'Escape' && !$('#confirmDialog').classList.contains('hidden')) return;
  if (event.key === 'Escape' && current) { event.preventDefault(); window.ntc.cancelDownload(current.downloadId); }
  if (event.key === 'Escape' && currentConversion) { event.preventDefault(); window.ntc.cancelConversion(currentConversion.conversionId); }
});
document.addEventListener('keydown', event => { if (event.key === 'Escape' && !$('#confirmDialog').classList.contains('hidden')) closeConfirm(false); if (event.key === 'Escape' && !$('#changelogDialog').classList.contains('hidden')) $('#changelogDialog').classList.add('hidden'); });
syncSettings(); $('#compressionFolderPath').textContent = localStorage.getItem('ntc-compression-folder') || folder || 'Downloads'; setFormatOptions(); conversionQualityOptions('mp3'); updateConverterExtension('mp3'); renderHistory(); renderQueue(); renderConversionQueue(); renderCompressionQueue(); configureRecordingShortcut($('#recordShortcut').value); window.ntc.appVersion().then(version => { $('#appVersion').textContent = `v${version}`; }).catch(() => { $('#appVersion').textContent = 'Indisponível'; }); window.ntc.defaultDownloadFolder().then(value => { if (!folder) { folder = value; localStorage.setItem('ntc-folder', folder); syncSettings(); } refreshSpaceHint(); });
