(() => {
  'use strict';
  const core = window.NTCRandomCore;
  const stateApi = window.NTCRandomToolsState;
  const root = document.getElementById('randomToolsApp');
  if (!core || !stateApi || !root) return;
  const STORE_KEY = 'ntc-random-tools-v1';
  const MAX_LIST = 10000;
  const toolGroups = [
    ['Rápidos', [['coin','Cara ou coroa','Jogue uma ou várias moedas.','🪙'],['dice','Dados','Dados clássicos, personalizados e notação.','🎲'],['decision','Sim ou não','Uma resposta rápida para sua pergunta.','◉'],['rps','Pedra, papel e tesoura','Clássico ou com lagarto e Spock.','✊'],['reaction','Tempo de reação','Teste seus reflexos.','◷'],['cps','Teste de cliques','Meça seus cliques por segundo.','⌁']]],
    ['Sorteios', [['wheel','Roleta','Monte opções com pesos e salve suas roletas.','◉'],['picker','Sortear itens','Escolha um ou vários nomes da sua lista.','⇄'],['number','Número aleatório','Gere inteiros ou decimais em uma faixa.','№'],['cards','Cartas','Compre de um baralho sem repetir cartas.','♠']]],
    ['Listas', [['teams','Criar equipes','Divida participantes sem deixar ninguém de fora.','♟'],['shuffle','Embaralhar e ordenar','Crie uma ordem aleatória para sua lista.','⇄']]],
    ['Jogos rápidos', [['guess','Adivinhe o número','Descubra o número com dicas de maior ou menor.','?'],['higher','Maior ou menor','Acerte se o próximo valor será maior ou menor.','↑']]],
    ['Aleatórios', [['color','Cor aleatória','Gere uma cor e copie seus formatos.','◉'],['letter','Letra e caracteres','Gere letras ou strings recreativas.','Aa']]]
  ];
  const allTools = toolGroups.flatMap(([group, items]) => items.map(([id, name, detail, icon]) => ({ id, group, name, detail, icon })));
  function cleanOptions(options) { return Array.isArray(options) ? options.slice(0, 1000).map(x => ({ label: String(x?.label || '').trim().slice(0, 160), weight: Number.isSafeInteger(Number(x?.weight)) && Number(x.weight) > 0 ? Number(x.weight) : 1 })).filter(x => x.label) : []; }
  const stateStore = stateApi.createStore(localStorage, STORE_KEY, allTools.map(tool => tool.id));
  let data = stateStore.load();
  let current = 'home';
  let homeQuery = '';
  let wheel = { id: '', name: 'Minha roleta', options: [{ label: 'Pizza', weight: 1 }, { label: 'Hambúrguer', weight: 1 }, { label: 'Japonês', weight: 1 }], removeWinner: false };
  let wheelRotation = 0, wheelTimer = 0, wheelResult = '', wheelSpinning = false;
  let coinHistory = [], coinLastSummary = '', diceHistory = [], diceExpression = '1d6', pickerHistory = [], numberHistory = [], decisionHistory = [];
  let deck = null, drawnCards = [], deckJokers = false;
  let teamResult = null, shuffleResult = null;
  let rpsMode = 'classic';
  let guessGame = null, higherGame = null, reactionGame = { phase: 'ready', started: 0, timeout: 0, message: 'Quando estiver pronto, comece o teste.' };
  let cpsGame = { active: false, started: 0, clicks: 0, timeout: 0, duration: 5 };
  function save() { if (!stateStore.save(data)) announce('Não foi possível salvar as preferências locais.'); }
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const byId = id => allTools.find(tool => tool.id === id);
  const announce = message => { const status = document.getElementById('randomToolsStatus'); if (status) status.textContent = message; try { window.NTCMediaAppBridge?.showToast(message); } catch {} };
  const fmt = value => Number(value).toLocaleString('pt-BR');
  const copy = async value => { try { await window.ntc.copyText(String(value)); announce('Resultado copiado.'); } catch { announce('Não foi possível copiar o resultado.'); } };
  const inputValue = (form, name, fallback = '') => new FormData(form).get(name) ?? fallback;
  const savedListControls = () => `<div class="rt-saved-tools"><label>Lista salva<select data-action="load-list"><option value="">Escolha uma lista…</option>${data.lists.map(item => `<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('')}</select></label><label>Nome para salvar<input data-list-name maxlength="60" placeholder="Ex.: Amigos"></label><button type="button" class="rt-button subtle" data-action="save-current-list">Salvar lista atual</button>${data.lists.length ? '<button type="button" class="rt-button subtle danger" data-action="delete-list">Excluir selecionada</button>' : ''}</div>`;
  function toolCard(tool, compact = false) { const active = data.favorites.includes(tool.id); return `<article class="rt-tool-card${compact ? ' compact' : ''}"><button type="button" class="rt-tool-open" data-open-tool="${tool.id}"><span class="rt-tool-icon" aria-hidden="true">${tool.icon}</span><span class="rt-tool-copy"><strong>${esc(tool.name)}</strong><small>${esc(tool.detail)}</small></span><span class="rt-tool-arrow" aria-hidden="true">→</span></button><button type="button" class="rt-favorite${active ? ' active' : ''}" data-favorite="${tool.id}" aria-pressed="${active}" aria-label="${active ? 'Remover dos' : 'Adicionar aos'} favoritos" title="${active ? 'Remover dos favoritos' : 'Adicionar aos favoritos'}">${active ? '★' : '☆'}</button></article>`; }
  function renderHome() {
    const query = homeQuery.trim().toLocaleLowerCase('pt-BR');
    const favoriteTools = allTools.filter(tool => data.favorites.includes(tool.id));
    const recentTools = data.recent.map(byId).filter(Boolean);
    const groups = toolGroups.map(([name, tools]) => [name, tools.filter(tool => !query || `${tool[1]} ${tool[2]} ${name}`.toLocaleLowerCase('pt-BR').includes(query)).map(item => byId(item[0]))]).filter(([, tools]) => tools.length);
    root.innerHTML = `<section class="rt-home"><div class="rt-home-top"><div><span class="rt-kicker">UTILIDADE + DIVERSÃO</span><h2>Escolha uma ferramenta</h2><p>Sem conta, internet, apostas ou dinheiro — só decisões e jogos locais.</p></div><label class="rt-search"><span aria-hidden="true">⌕</span><input type="search" id="rtToolSearch" value="${esc(homeQuery)}" placeholder="Buscar ferramenta…" aria-label="Buscar ferramenta"></label></div>
      ${favoriteTools.length ? `<section class="rt-section"><div class="rt-section-title"><h3>Favoritos</h3><span>Acesso rápido</span></div><div class="rt-tool-grid favorites">${favoriteTools.map(tool => toolCard(tool, true)).join('')}</div></section>` : ''}
      ${recentTools.length ? `<section class="rt-section"><div class="rt-section-title"><h3>Recentes</h3><span>Suas últimas ferramentas</span></div><div class="rt-tool-grid recent">${recentTools.slice(0, 5).map(tool => toolCard(tool, true)).join('')}</div></section>` : ''}
      ${groups.length ? groups.map(([name, tools]) => `<section class="rt-section"><div class="rt-section-title"><h3>${esc(name)}</h3><span>${tools.length} ${tools.length === 1 ? 'ferramenta' : 'ferramentas'}</span></div><div class="rt-tool-grid">${tools.map(tool => toolCard(tool)).join('')}</div></section>`).join('') : '<div class="rt-empty">Nenhuma ferramenta corresponde à busca.</div>'}
      <div class="rt-footer-note"><label><input id="rtSkipMotion" type="checkbox" ${data.skipMotion ? 'checked' : ''}> Pular animações</label><span>As animações são apenas visuais; o resultado é calculado antes.</span></div></section>`;
    document.getElementById('rtToolSearch').oninput = event => { homeQuery = event.target.value; const start = event.target.selectionStart; renderHome(); const next = document.getElementById('rtToolSearch'); next.focus(); next.setSelectionRange(start, start); };
    document.getElementById('rtSkipMotion').onchange = event => { data.skipMotion = event.target.checked; save(); const heading = document.getElementById('randomToolsSkipMotion'); if (heading) heading.checked = data.skipMotion; };
  }
  function shell(id, content) { const tool = byId(id); root.innerHTML = `<div class="rt-workspace"><div class="rt-workspace-head"><button class="rt-button subtle" type="button" data-action="home">← Todas as ferramentas</button><button class="rt-favorite rt-work-favorite${data.favorites.includes(id) ? ' active' : ''}" type="button" data-favorite="${id}" aria-pressed="${data.favorites.includes(id)}" aria-label="Favoritar ${esc(tool.name)}" title="Favoritar">${data.favorites.includes(id) ? '★' : '☆'}</button></div><div class="rt-tool-heading"><span class="rt-tool-icon large" aria-hidden="true">${tool.icon}</span><div><span class="rt-kicker">${esc(tool.group.toLocaleUpperCase('pt-BR'))}</span><h2>${esc(tool.name)}</h2><p>${esc(tool.detail)}</p></div></div>${content}<p class="rt-status" id="randomToolsStatus" role="status" aria-live="polite"></p></div>`; }
  const actionButton = (action, label, extra = '') => `<button class="rt-button ${extra}" type="button" data-action="${action}">${label}</button>`;
  const copyCache = new Map(); let nextCopyId = 1;
  const copyButton = value => { const id=String(nextCopyId++);copyCache.set(id,String(value));while(copyCache.size>40)copyCache.delete(copyCache.keys().next().value);return `<button class="rt-button subtle" type="button" data-copy="${id}">Copiar</button>`; };
  function updateCopyButton(container, value) {
    if (!container) return;
    const existing = container.querySelector('[data-copy]');
    if (existing) {
      const id = existing.dataset.copy;
      if (copyCache.has(id)) { copyCache.set(id, String(value)); return; }
      existing.dataset.copy = String(nextCopyId++);
      copyCache.set(existing.dataset.copy, String(value));
      while (copyCache.size > 40) copyCache.delete(copyCache.keys().next().value);
      return;
    }
    container.insertAdjacentHTML('afterbegin', copyButton(value));
  }
  function renderCoin() {
    const total = data.coin.heads + data.coin.tails, face = coinHistory[0] || '';
    shell('coin', `<form class="rt-panel rt-form" data-form="coin"><label>Quantidade de moedas<input name="count" type="number" min="1" max="10000" value="1" required></label><button class="rt-button primary" type="submit">Jogar</button></form>
      <div class="rt-result-panel"><div class="rt-coin-face${face ? ' revealed' : ''}" id="rtCoinFace" aria-live="polite">${face === 'Cara' ? 'CARA' : face === 'Coroa' ? 'COROA' : '🪙'}</div><div class="rt-coin-summary" id="rtCoinSummary">${coinLastSummary || (face ? `Último lançamento: ${esc(face)}` : 'O resultado aparece aqui.')}</div><div class="rt-inline-actions">${coinLastSummary ? copyButton(coinLastSummary) : ''}${actionButton('reset-coin','Resetar estatísticas','subtle')}</div></div>
      <section class="rt-panel"><div class="rt-section-title"><h3>Estatísticas</h3><span>${fmt(total)} lançamentos</span></div><div class="rt-stat-grid"><div><strong>${fmt(data.coin.heads)}</strong><span>Cara · ${total ? (data.coin.heads / total * 100).toFixed(1) : '0,0'}%</span></div><div><strong>${fmt(data.coin.tails)}</strong><span>Coroa · ${total ? (data.coin.tails / total * 100).toFixed(1) : '0,0'}%</span></div><div><strong>${fmt(total)}</strong><span>Total</span></div></div></section>
      <section class="rt-panel"><div class="rt-section-title"><h3>Histórico desta sessão</h3>${actionButton('clear-coin-history','Limpar','subtle')}</div><ol class="rt-history">${coinHistory.length ? coinHistory.slice(0, 20).map(x => `<li>${esc(x)}</li>`).join('') : '<li class="muted">Faça um lançamento para começar.</li>'}</ol></section>`);
  }
  function renderDice() {
    const last = diceHistory[0];
    shell('dice', `<form class="rt-panel rt-form rt-dice-form" data-form="dice"><label>Expressão de dados<input name="expression" maxlength="40" value="${esc(diceExpression)}" placeholder="2d20+5" required></label><div class="rt-dice-presets">${['d2','d4','d6','d8','d10','d12','d20','d100'].map(x => `<button class="rt-chip" type="button" data-dice-preset="${x}">${x.toUpperCase()}</button>`).join('')}</div><button class="rt-button primary" type="submit">Rolar dados</button></form>
      <section class="rt-panel rt-output" id="rtDiceOutput">${last ? `<div class="rt-result-large">${fmt(last.total)}</div><p>${esc(last.expression)} · soma ${fmt(last.sum)} ${last.modifier ? `· modificador ${last.modifier > 0 ? '+' : ''}${last.modifier}` : ''}</p><div class="rt-dice-values">${last.values.slice(0, 100).map(value => `<span>🎲 ${value}</span>`).join('')}${last.values.length > 100 ? `<span>+ ${fmt(last.values.length - 100)} dados ocultos</span>` : ''}</div><div class="rt-inline-actions">${copyButton(`${last.expression} → [${last.values.join(', ')}] = ${last.total}`)}</div>` : '<div class="rt-empty">Configure e role seus dados para ver o resultado.</div>'}</section>
      <section class="rt-panel"><div class="rt-section-title"><h3>Histórico da sessão</h3>${actionButton('clear-dice-history','Limpar','subtle')}</div><ol class="rt-history">${diceHistory.length ? diceHistory.map(item => `<li>${esc(item.expression)} → [${item.values.slice(0, 20).join(', ')}${item.values.length > 20 ? ', …' : ''}] = ${fmt(item.total)} ${copyButton(`${item.expression} → [${item.values.join(', ')}] = ${item.total}`)}</li>`).join('') : '<li class="muted">Nenhuma rolagem ainda.</li>'}</ol></section>`);
  }
  function renderWheel() {
    const totalWeight = wheel.options.reduce((sum, item) => sum + (Number(item.weight) || 1), 0);
    shell('wheel', `<section class="rt-wheel-layout"><div class="rt-panel rt-wheel-stage"><div class="rt-wheel-pointer" aria-hidden="true">▼</div><canvas id="rtWheelCanvas" width="520" height="520" aria-label="Roleta com as opções atuais"></canvas><div class="rt-wheel-result" id="rtWheelResult" aria-live="polite">${wheelResult ? `Resultado: ${esc(wheelResult)} ${copyButton(wheelResult)}` : 'Adicione opções para começar.'}</div>${actionButton('spin-wheel','Girar roleta','primary rt-spin')}</div>
      <div class="rt-wheel-editor"><section class="rt-panel"><div class="rt-section-title"><h3>Opções</h3><span>${wheel.options.length} opções · ${wheel.options.some(x => x.weight !== 1) ? 'pesos ativos' : 'peso igual'}</span></div><div class="rt-wheel-options">${wheel.options.map((item,index) => `<div class="rt-wheel-option"><span class="rt-option-index">${index+1}</span><input data-wheel-label="${index}" maxlength="160" value="${esc(item.label)}" aria-label="Nome da opção ${index+1}"><label class="rt-weight">Peso<input type="number" data-wheel-weight="${index}" min="1" max="1000000" value="${Number(item.weight)||1}" aria-label="Peso da opção ${index+1}"></label><button class="rt-icon-button" type="button" data-wheel-up="${index}" aria-label="Mover opção para cima" title="Mover para cima">↑</button><button class="rt-icon-button" type="button" data-wheel-down="${index}" aria-label="Mover opção para baixo" title="Mover para baixo">↓</button><button class="rt-icon-button" type="button" data-wheel-duplicate="${index}" aria-label="Duplicar opção" title="Duplicar opção">⧉</button><button class="rt-icon-button danger" type="button" data-wheel-remove="${index}" aria-label="Remover opção" title="Remover">×</button></div>`).join('') || '<p class="muted">Adicione pelo menos duas opções para girar.</p>'}</div><form class="rt-add-options" data-form="wheel-add"><textarea name="options" rows="3" placeholder="Cole uma opção por linha…" aria-label="Novas opções"></textarea><button class="rt-button subtle" type="submit">Adicionar opções</button></form>${data.lists.length?`<label>Carregar lista salva<select data-action="load-wheel-list"><option value="">Escolha uma lista…</option>${data.lists.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('')}</select></label>`:''}<label class="rt-check"><input type="checkbox" data-remove-winner ${wheel.removeWinner ? 'checked' : ''}> Remover vencedor depois de sortear</label><p class="rt-hint">${wheel.options.some(x => x.weight !== 1) ? 'Pesos ativos: cada opção recebe a chance proporcional ao peso indicado.' : 'Peso igual: todas as opções têm a mesma chance.'}</p></section>
      <section class="rt-panel"><div class="rt-section-title"><h3>Salvar roleta</h3><span>Fica neste dispositivo</span></div><label>Nome<input data-wheel-name maxlength="60" value="${esc(wheel.name)}"></label><div class="rt-inline-actions"><button class="rt-button subtle" type="button" data-action="save-wheel">Salvar como nova</button>${wheel.id ? '<button class="rt-button subtle" type="button" data-action="update-wheel">Salvar alterações</button><button class="rt-button subtle" type="button" data-action="rename-wheel">Renomear</button><button class="rt-button subtle" type="button" data-action="duplicate-wheel">Duplicar</button><button class="rt-button subtle danger" type="button" data-action="delete-wheel">Excluir</button>' : ''}</div>${data.wheels.length ? `<label>Carregar roleta salva<select data-action="load-wheel"><option value="">Escolha uma roleta…</option>${data.wheels.map(item => `<option value="${esc(item.id)}" ${wheel.id===item.id?'selected':''}>${esc(item.name)}</option>`).join('')}</select></label>` : '<p class="muted">Nenhuma roleta salva ainda.</p>'}</section></div></section>`);
    drawWheel();
  }
  function drawWheel() {
    const canvas = document.getElementById('rtWheelCanvas'); if (!canvas) return;
    const ctx = canvas.getContext('2d'); if (!ctx) return;
    const options = wheel.options.filter(item => item.label); const total = options.reduce((sum,item)=>sum+item.weight,0) || 1;
    const colors = ['#856a91','#665575','#92789a','#584960','#a186a9','#746380','#9a829f','#4d4054','#b094b7','#61506c'];
    let angle = -Math.PI / 2; ctx.clearRect(0,0,520,520);
    if (!options.length) { ctx.beginPath(); ctx.arc(260,260,250,0,Math.PI*2); ctx.fillStyle='#302833'; ctx.fill(); ctx.fillStyle='#ddd'; ctx.font='20px sans-serif'; ctx.textAlign='center'; ctx.fillText('Adicione opções',260,265); return; }
    options.forEach((item,index) => { const span = Math.PI*2*item.weight/total; ctx.beginPath(); ctx.moveTo(260,260); ctx.arc(260,260,250,angle,angle+span); ctx.closePath(); ctx.fillStyle=colors[index%colors.length]; ctx.fill(); ctx.strokeStyle='#19151c'; ctx.lineWidth=3; ctx.stroke(); const mid=angle+span/2; ctx.save(); ctx.translate(260,260); ctx.rotate(mid); ctx.textAlign='right'; ctx.fillStyle='#fff'; ctx.font='600 14px Segoe UI, sans-serif'; ctx.fillText(item.label.slice(0,22),225,5); ctx.restore(); angle+=span; });
    ctx.beginPath(); ctx.arc(260,260,18,0,Math.PI*2); ctx.fillStyle='#e2d5e7'; ctx.fill();
  }
  function renderPicker() {
    const last = pickerHistory[0];
    shell('picker', `<section class="rt-panel"><form class="rt-form" data-form="picker"><label>Itens ou nomes · um por linha<textarea name="items" rows="8" maxlength="500000" placeholder="Ana&#10;Bruno&#10;Carlos" aria-label="Itens para sortear"></textarea></label>${savedListControls()}<div class="rt-controls-row"><label>Quantidade<input name="count" type="number" min="1" max="10000" value="1"></label><label class="rt-check"><input name="noRepeat" type="checkbox" checked> Não repetir itens</label><label class="rt-check"><input name="removeDrawn" type="checkbox"> Remover sorteados da lista</label><label class="rt-check"><input name="dedupe" type="checkbox"> Remover duplicados automaticamente</label></div><button class="rt-button primary" type="submit">Sortear</button></form></section><section class="rt-panel rt-output" id="rtPickerOutput">${last ? `<h3>Resultado · ${last.items.length} item(ns)</h3><ol class="rt-result-list">${last.items.slice(0,200).map(item=>`<li>${esc(item)}</li>`).join('')}${last.items.length>200?`<li>… mais ${fmt(last.items.length-200)} itens</li>`:''}</ol><div class="rt-inline-actions">${copyButton(last.items.join('\n'))}</div>` : '<div class="rt-empty">Cole uma lista ou carregue uma lista salva para sortear.</div>'}</section><section class="rt-panel"><div class="rt-section-title"><h3>Últimos sorteios da sessão</h3>${actionButton('clear-picker-history','Limpar','subtle')}</div><ol class="rt-history">${pickerHistory.slice(0,10).map(item=>`<li>${fmt(item.items.length)} selecionado(s) · ${item.items.slice(0,3).map(esc).join(', ')}${item.items.length>3?'…':''}</li>`).join('')||'<li class="muted">Sem histórico nesta sessão.</li>'}</ol></section>`);
  }
  function renderNumber() {
    const last = numberHistory[0];
    shell('number', `<form class="rt-panel rt-form" data-form="number"><div class="rt-controls-row"><label>Mínimo<input name="min" type="number" value="1" required></label><label>Máximo<input name="max" type="number" value="100" required></label><label>Quantidade<input name="count" type="number" min="1" max="100000" value="1" required></label><label>Casas decimais<select name="decimals"><option value="0">Inteiros</option><option value="1">1 casa</option><option value="2">2 casas</option><option value="4">4 casas</option><option value="6">6 casas</option></select></label></div><label class="rt-check"><input name="repeat" type="checkbox"> Permitir resultados repetidos</label><button class="rt-button primary" type="submit">Gerar números</button></form><section class="rt-panel rt-output">${last?`<div class="rt-result-large">${last.values.slice(0,12).map(x=>esc(x)).join(' · ')}${last.values.length>12?' · …':''}</div><p>${fmt(last.values.length)} número(s) · mínimo ${esc(last.min)} · máximo ${esc(last.max)} · média ${esc(last.mean)}</p><div class="rt-inline-actions">${copyButton(last.values.join('\n'))}</div>`:'<div class="rt-empty">Escolha uma faixa para gerar números.</div>'}</section><section class="rt-panel"><div class="rt-section-title"><h3>Histórico da sessão</h3>${actionButton('clear-number-history','Limpar','subtle')}</div><ol class="rt-history">${numberHistory.slice(0,10).map(x=>`<li>${fmt(x.values.length)} resultado(s) entre ${esc(x.min)} e ${esc(x.max)} · ${x.values.slice(0,5).join(', ')}${x.values.length>5?'…':''}</li>`).join('')||'<li class="muted">Sem histórico nesta sessão.</li>'}</ol></section>`);
  }
  function renderDecision() { const last=decisionHistory[0]; shell('decision', `<form class="rt-panel rt-form" data-form="decision"><label>Pergunta <span class="rt-optional">opcional</span><input name="question" maxlength="240" placeholder="Devo pedir pizza?"></label><label>Respostas<select name="mode"><option value="two">Sim / Não · 50/50</option><option value="three">Sim / Não / Talvez</option></select></label><button class="rt-button primary" type="submit">Decidir</button></form><section class="rt-panel rt-decision-result" aria-live="polite"><span>${last?.question?esc(last.question):'Sua decisão'}</span><strong>${last?esc(last.answer):'—'}</strong>${last?copyButton(`${last.question?`${last.question} → `:''}${last.answer}`):''}</section><section class="rt-panel"><div class="rt-section-title"><h3>Histórico da sessão</h3>${actionButton('clear-decision-history','Limpar','subtle')}</div><ol class="rt-history">${decisionHistory.slice(0,20).map(x=>`<li>${x.question?`${esc(x.question)} → `:''}<strong>${esc(x.answer)}</strong></li>`).join('')||'<li class="muted">Nenhuma decisão ainda.</li>'}</ol></section>`); }
  function renderCards() {
    if (!deck) { deckJokers=false; deck=core.shuffle(core.createDeck(false)); }
    shell('cards', `<section class="rt-panel rt-card-draw-panel"><div class="rt-section-title"><h3>Baralho</h3><span>${deck.length} / ${deckJokers?54:52} cartas restantes · ${52+(deckJokers?2:0)-deck.length} compradas</span></div><div class="rt-controls-row"><label>Quantidade<input id="rtCardCount" type="number" min="2" max="${deck.length}" value="5" ${deck.length<2?'disabled':''}></label><label class="rt-check"><input id="rtJokers" type="checkbox" ${deckJokers?'checked':''}> Incluir coringas</label></div><div class="rt-inline-actions">${actionButton('draw-card','Comprar carta','primary')}<button class="rt-button" type="button" data-action="draw-cards" ${deck.length<2?'disabled':''}>Comprar várias</button>${actionButton('reset-deck','Reiniciar baralho','subtle')}</div><div class="rt-playing-cards" id="rtPlayingCards" aria-live="polite">${drawnCards.length?`${drawnCards.map(cardMarkup).join('')}<div class="rt-inline-actions">${copyButton(drawnCards.map(card=>`${card.rank}${card.suit}`).join(', '))}</div>`:`<p class="muted">${deck.length?'Compre uma carta para começar.':'O baralho acabou. Reinicie para embaralhar novamente.'}</p>`}</div></section>`); }
  function cardMarkup(card) { return `<article class="rt-card-face${card.red?' red':''}" aria-label="${esc(card.rank)} de ${esc(card.suit)}"><span>${esc(card.rank)}<br>${esc(card.suit)}</span><strong>${esc(card.suit)}</strong><span>${esc(card.rank)}<br>${esc(card.suit)}</span></article>`; }
  function renderTeams() {
    shell('teams', `<section class="rt-panel"><form class="rt-form" data-form="teams"><label>Participantes · um por linha<textarea name="items" rows="9" maxlength="500000" placeholder="Ana&#10;Bruno&#10;Carlos&#10;Eduardo" aria-label="Participantes"></textarea></label>${savedListControls()}<div class="rt-controls-row"><label>Dividir por<select name="mode"><option value="teams">Número de equipes</option><option value="size">Pessoas por equipe</option></select></label><label>Quantidade<input name="count" type="number" min="1" value="2" required></label><label class="rt-check"><input name="dedupe" type="checkbox"> Remover duplicados automaticamente</label></div><button class="rt-button primary" type="submit">Criar equipes</button></form></section><section class="rt-panel rt-output">${teamResult?renderTeamMarkup(teamResult):'<div class="rt-empty">Adicione participantes para criar equipes.</div>'}</section>`);
  }
  function renderTeamMarkup(result) { const all=result.teams.flat(); return `<div class="rt-section-title"><h3>${result.teams.length} equipes · ${all.length} participantes</h3><div>${copyButton(result.teams.map((team,i)=>`TIME ${i+1}\n${team.join('\n')}`).join('\n\n'))} ${actionButton('reshuffle-teams','Embaralhar novamente','subtle')}</div></div><div class="rt-team-grid">${result.teams.map((team,i)=>`<section><h4>${esc(result.names?.[i]||`Time ${i+1}`)} <small>${team.length}</small></h4><ol>${team.slice(0,1000).map(p=>`<li>${esc(p)}</li>`).join('')}${team.length>1000?`<li>… +${fmt(team.length-1000)}</li>`:''}</ol></section>`).join('')}</div>`; }
  function renderShuffle() {
    shell('shuffle', `<section class="rt-panel"><form class="rt-form" data-form="shuffle"><label>Lista · um item por linha<textarea name="items" rows="9" maxlength="500000" placeholder="Pessoas, tarefas, apresentações…" aria-label="Lista para embaralhar"></textarea></label>${savedListControls()}<label class="rt-check"><input name="dedupe" type="checkbox"> Remover duplicados automaticamente</label><button class="rt-button primary" type="submit">Embaralhar lista</button></form></section><section class="rt-panel rt-output">${shuffleResult?`<div class="rt-section-title"><h3>Ordem aleatória · ${fmt(shuffleResult.length)} itens</h3><div>${copyButton(shuffleResult.join('\n'))} ${actionButton('reshuffle-list','Embaralhar novamente','subtle')}</div></div><ol class="rt-result-list">${shuffleResult.slice(0,1000).map(item=>`<li>${esc(item)}</li>`).join('')}${shuffleResult.length>1000?`<li>… mais ${fmt(shuffleResult.length-1000)} itens; use Copiar para ver todos.</li>`:''}</ol><button class="rt-button subtle" type="button" data-action="use-shuffle-as-input">Usar resultado como nova entrada</button>`:'<div class="rt-empty">Adicione itens para criar uma ordem aleatória.</div>'}</section>`);
  }
  function renderRps() {
    const last=window.__ntcRpsLast;
    shell('rps', `<section class="rt-panel"><label>Modo<select id="rtRpsMode"><option value="classic" ${rpsMode==='classic'?'selected':''}>Clássico · Pedra / Papel / Tesoura</option><option value="expanded" ${rpsMode==='expanded'?'selected':''}>Expandido · + Lagarto / Spock</option></select></label><div class="rt-rps-grid">${[['pedra','✊','Pedra'],['papel','✋','Papel'],['tesoura','✌','Tesoura'],['lagarto','🦎','Lagarto'],['spock','🖖','Spock']].map(([id,icon,label])=>`<button class="rt-choice" type="button" data-rps="${id}" ${['lagarto','spock'].includes(id)&&rpsMode!=='expanded'?'hidden':''}><span>${icon}</span>${label}</button>`).join('')}</div><div class="rt-rps-result" id="rtRpsResult" aria-live="polite">${last?`<p>Você: <strong>${esc(last.player)}</strong> · NTC: <strong>${esc(last.computer)}</strong></p><h3>${last.result==='vitória'?'Você venceu!':last.result==='empate'?'Empate':'NTC venceu'}</h3>${copyButton(`Você: ${last.player} · NTC: ${last.computer} · ${last.result}`)}`:'Escolha sua jogada.'}</div><div class="rt-rps-footer"><div class="rt-stat-grid"><div><strong>${fmt(data.rps.wins)}</strong><span>Vitórias</span></div><div><strong>${fmt(data.rps.draws)}</strong><span>Empates</span></div><div><strong>${fmt(data.rps.losses)}</strong><span>Derrotas</span></div></div>${actionButton('reset-rps','Resetar placar','subtle')}</div></section>`);
  }
  function renderGuess() { const g=guessGame; shell('guess', `<section class="rt-panel"><form class="rt-form" data-form="guess"><label>Dificuldade<select name="difficulty"><option value="easy">Fácil · 1–10</option><option value="normal" selected>Normal · 1–100</option><option value="hard">Difícil · 1–1.000</option><option value="custom">Personalizado</option></select></label><div class="rt-controls-row rt-custom-range hidden"><label>Mínimo<input name="min" type="number" value="1"></label><label>Máximo<input name="max" type="number" value="100"></label></div><button class="rt-button primary" type="submit">${g?'Novo jogo':'Começar jogo'}</button></form>${g?`<form class="rt-panel rt-form" data-form="guess-submit"><p>Estou pensando em um número entre <strong>${fmt(g.min)}</strong> e <strong>${fmt(g.max)}</strong>.</p><label>Seu palpite<input name="guess" type="number" min="${g.min}" max="${g.max}" required ${g.done?'disabled':''}></label><button class="rt-button primary" type="submit" ${g.done?'disabled':''}>Tentar</button></form>`:''}<div class="rt-result-panel" id="rtGuessFeedback" aria-live="polite"><strong>${g?esc(g.message):'Comece um novo jogo.'}</strong>${g?`<span>Tentativas: ${g.attempts}${data.records.guesses[g.difficulty]?` · recorde: ${data.records.guesses[g.difficulty]}`:''}</span>`:''}</div>`); }
  function renderHigher() { shell('higher', `<section class="rt-panel rt-higher-card"><div class="rt-result-large">${higherGame?higherGame.current:'?'}</div><p>${higherGame?`Sequência atual: ${higherGame.streak} · Recorde local: ${fmt(data.records.higherBest)}`:'Comece para revelar o primeiro número.'}</p><div class="rt-inline-actions">${!higherGame?actionButton('start-higher','Começar jogo','primary'):higherGame.over?actionButton('start-higher','Jogar novamente','primary'):`${actionButton('higher-guess','Próximo é MAIOR','primary')} ${actionButton('lower-guess','Próximo é MENOR','subtle')}`}</div><p id="rtHigherFeedback" aria-live="polite">${higherGame?esc(higherGame.message):''}</p></section>`); }
  function renderReaction() { const r=data.records; shell('reaction', `<section class="rt-panel rt-reaction"><p>${esc(reactionGame.message)}</p><button class="rt-reaction-button ${reactionGame.phase==='ready'?'ready':reactionGame.phase==='wait'?'waiting':'go'}" data-action="reaction-click" type="button">${reactionGame.phase==='ready'?'Começar':reactionGame.phase==='wait'?'Espere…':'CLIQUE!'}</button><div class="rt-stat-grid"><div><strong>${r.reactionBest?`${r.reactionBest} ms`:'—'}</strong><span>Melhor</span></div><div><strong>${r.reactionSamples.length?`${Math.round(r.reactionSamples.reduce((a,b)=>a+b,0)/r.reactionSamples.length)} ms`:'—'}</strong><span>Média recente</span></div><div><strong>${r.reactionSamples.length?`${r.reactionSamples.at(-1)} ms`:'—'}</strong><span>Último</span></div></div></section>`); }
  function renderCps() { shell('cps', `<section class="rt-panel rt-cps"><label>Duração<select id="rtCpsDuration" ${cpsGame.active?'disabled':''}><option value="1" ${cpsGame.duration===1?'selected':''}>1 segundo</option><option value="5" ${cpsGame.duration===5?'selected':''}>5 segundos</option><option value="10" ${cpsGame.duration===10?'selected':''}>10 segundos</option></select></label><button type="button" class="rt-cps-button" data-action="cps-click" ${cpsGame.active?'':'disabled'}>${cpsGame.active?'CLIQUE!':'Inicie o teste'}</button>${actionButton('start-cps',cpsGame.active?'Teste em andamento':'Começar teste',cpsGame.active?'subtle':'primary')}<p id="rtCpsStatus" aria-live="polite">${cpsGame.active?`${cpsGame.clicks} cliques`:cpsGame.last?`${cpsGame.last.clicks} cliques · ${cpsGame.last.cps.toFixed(2)} CPS`:'Clique rapidamente quando o teste começar.'}</p><div class="rt-stat-grid"><div><strong>${fmt(cpsGame.last?.clicks||0)}</strong><span>Cliques</span></div><div><strong>${cpsGame.last?cpsGame.last.cps.toFixed(2):'—'}</strong><span>CPS</span></div><div><strong>${data.records.cpsBest?data.records.cpsBest.toFixed(2):'—'}</strong><span>Recorde local</span></div></div></section>`); }
  function renderColor() { const color=window.__ntcRandomColor||''; shell('color', `<section class="rt-panel rt-color-tool"><div class="rt-color-swatch" style="--random-color:${color||'#28222c'}" aria-label="${color?`Cor ${color}`:'Prévia da cor'}"></div><div class="rt-color-values"><strong>${color||'—'}</strong><span>${color?rgbFromHex(color):'Gere uma cor para ver RGB e HSL.'}</span><span>${color?hslFromHex(color):''}</span></div><div class="rt-inline-actions">${actionButton('generate-color','Gerar cor','primary')}${color?copyButton(color):''}</div></section>`); }
  function hexChannels(hex) { return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)); }
  function rgbFromHex(hex) { const [r,g,b]=hexChannels(hex); return `RGB(${r}, ${g}, ${b})`; }
  function hslFromHex(hex) { const [r0,g0,b0]=hexChannels(hex).map(x=>x/255); const max=Math.max(r0,g0,b0),min=Math.min(r0,g0,b0); let h=0,s=0,l=(max+min)/2; if(max!==min){const d=max-min;s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r0:h=(g0-b0)/d+(g0<b0?6:0);break;case g0:h=(b0-r0)/d+2;break;default:h=(r0-g0)/d+4;}h*=60;}return `HSL(${Math.round(h)}°, ${Math.round(s*100)}%, ${Math.round(l*100)}%)`; }
  function renderLetter() { shell('letter', `<form class="rt-panel rt-form" data-form="letter"><label>Tipo<select name="mode"><option value="upper">Letras maiúsculas</option><option value="lower">Letras minúsculas</option><option value="both" selected>Maiúsculas e minúsculas</option><option value="string">String recreativa</option></select></label><label>Quantidade<input name="count" type="number" min="1" max="256" value="1"></label><div class="rt-optional-fields rt-character-options hidden" id="rtStringOptions"><span>Caracteres adicionais</span><label class="rt-check"><input name="numbers" type="checkbox"> Números</label><label class="rt-check"><input name="symbols" type="checkbox"> Símbolos</label></div><p class="rt-hint">Não use como senha segura; este recurso é para jogos e conteúdo aleatório.</p><button class="rt-button primary" type="submit">Gerar</button></form><section class="rt-panel rt-output" id="rtLetterOutput">${window.__ntcRandomText?`<div class="rt-result-large">${esc(window.__ntcRandomText)}</div>${copyButton(window.__ntcRandomText)}`:'<div class="rt-empty">Gere letras ou caracteres para começar.</div>'}</section>`); const form=root.querySelector('[data-form="letter"]'); form.querySelector('[name="mode"]').onchange=()=>form.querySelector('#rtStringOptions').classList.toggle('hidden',form.querySelector('[name="mode"]').value!=='string'); }
  function renderTool(id) { current=id; switch(id){case'coin':renderCoin();break;case'dice':renderDice();break;case'wheel':renderWheel();break;case'picker':renderPicker();break;case'number':renderNumber();break;case'decision':renderDecision();break;case'cards':renderCards();break;case'teams':renderTeams();break;case'shuffle':renderShuffle();break;case'rps':renderRps();break;case'guess':renderGuess();break;case'higher':renderHigher();break;case'reaction':renderReaction();break;case'cps':renderCps();break;case'color':renderColor();break;case'letter':renderLetter();break;default:renderHome();current='home';} }
  function openTool(id) { if (!byId(id)) return; current=id; data.recent=[id,...data.recent.filter(x=>x!==id)].slice(0,5); save(); if(id==='cards'){deck=core.shuffle(core.createDeck(false));deckJokers=false;drawnCards=[];} if(id==='wheel'){wheelResult='';wheelRotation=0;} if(id==='guess')guessGame=null; if(id==='higher')higherGame=null; renderTool(id); }
  function toggleFavorite(id) { data.favorites=data.favorites.includes(id)?data.favorites.filter(x=>x!==id):[...data.favorites,id]; save(); current==='home'?renderHome():renderTool(current); }
  function readList(form, { dedupe = false } = {}) { return core.parseList(inputValue(form,'items'),{dedupe,max:MAX_LIST}); }
  function saveCurrentList(items) { const name=root.querySelector('[data-list-name]')?.value.trim(); if(!name){announce('Informe um nome para salvar a lista.');root.querySelector('[data-list-name]')?.focus();return;} let list=data.lists.find(item=>item.name.toLocaleLowerCase('pt-BR')===name.toLocaleLowerCase('pt-BR')); if(list){list.items=items;} else {list={id:`list-${Date.now()}-${data.lists.length}`,name:name.slice(0,60),items};data.lists.unshift(list);} data.lists=data.lists.slice(0,100); save(); announce(`Lista “${list.name}” salva neste dispositivo.`); renderTool(current); }
  function loadSavedList(id) { const list=data.lists.find(item=>item.id===id); if(!list)return; const target=root.querySelector('textarea[name="items"]'); if(target)target.value=list.items.join('\n'); announce(`Lista “${list.name}” carregada.`); }
  function parseWheelDraft() { if(wheel.options.some(item=>!String(item.label||'').trim()))throw new Error('Preencha ou remova as opções vazias.'); if(wheel.options.some(item=>!Number.isSafeInteger(Number(item.weight))||Number(item.weight)<1||Number(item.weight)>1000000))throw new Error('Cada peso deve ser um inteiro entre 1 e 1.000.000.'); const options=cleanOptions(wheel.options); if(options.length<2)throw new Error('Adicione pelo menos duas opções para girar.'); return options; }
  function spinWheel() {
    if (wheelSpinning) return;
    try {
      const options=parseWheelDraft(); const winner=core.weightedChoice(options); wheelResult=winner.label;
      recordUsage('randomDraws');
      const total=options.reduce((sum,item)=>sum+item.weight,0); let before=0; const index=options.indexOf(winner); for(let i=0;i<index;i++)before+=options[i].weight;
      const center=-Math.PI/2+(before+winner.weight/2)/total*Math.PI*2; const delta=(((-Math.PI/2-center)*180/Math.PI)%360+360)%360; const target=wheelRotation+6*360+delta;
      const canvas=document.getElementById('rtWheelCanvas'); const result=document.getElementById('rtWheelResult');
      if(result)result.innerHTML=`Resultado: ${esc(winner.label)} ${copyButton(winner.label)}`;
      wheelSpinning=true;
      const spinButton=root.querySelector('[data-action="spin-wheel"]');if(spinButton)spinButton.disabled=true;
      if(canvas){canvas.classList.toggle('no-motion',data.skipMotion);canvas.style.transform=`rotate(${target}deg)`;}
      clearTimeout(wheelTimer);
      wheelTimer=setTimeout(()=>{if(wheel.removeWinner){wheel.options=wheel.options.filter(item=>item!==winner);wheelRotation=target%360;}else wheelRotation=target%360;wheelSpinning=false;if(current==='wheel'){if(wheel.removeWinner)renderWheel();else{const button=root.querySelector('[data-action="spin-wheel"]');if(button)button.disabled=false;}}},data.skipMotion?0:3200);
      if(options.length<2)announce(`A roleta escolheu “${winner.label}”. Adicione opções para girar novamente.`);
    } catch(error){wheelSpinning=false;announce(error.message||'Confira as opções e os pesos da roleta.');}
  }
  function updateDeckControls() { const panel=root.querySelector('.rt-card-draw-panel');if(!panel)return;const total=deckJokers?54:52,remaining=deck?.length||0,status=panel.querySelector('.rt-section-title span'),count=panel.querySelector('#rtCardCount'),many=panel.querySelector('[data-action="draw-cards"]');if(status)status.textContent=`${remaining} / ${total} cartas restantes · ${total-remaining} compradas`;if(count){count.max=String(remaining);count.disabled=remaining<2;if(remaining>=2&&Number(count.value)>remaining)count.value=String(remaining);}if(many)many.disabled=remaining<2; }
  function cardsMarkup(cards) { const place=document.getElementById('rtPlayingCards'); if(!place)return; drawnCards.push(...cards); if(!drawnCards.length){place.innerHTML=`<p class="muted">${deck.length?'Compre uma carta para começar.':'O baralho acabou. Reinicie para embaralhar novamente.'}</p>`;updateDeckControls();return;} place.innerHTML=`${drawnCards.map(cardMarkup).join('')}<div class="rt-inline-actions">${copyButton(drawnCards.map(card=>`${card.rank}${card.suit}`).join(', '))}</div>`;updateDeckControls(); }
  const recordUsage=(event,count=1)=>window.NTCLabsStats?.record(event,count);
  function performForm(form) {
    const kind=form.dataset.form;
    try {
      if(kind==='coin'){
        const count=Number(inputValue(form,'count'));if(!Number.isSafeInteger(count)||count<1||count>10000)throw new Error('Escolha de 1 a 10.000 moedas.');
        const flips=Array.from({length:count},()=>core.randomInteger(0,1)===0?'Cara':'Coroa'); const heads=flips.filter(x=>x==='Cara').length,tails=count-heads;
        data.coin.heads+=heads;data.coin.tails+=tails;save();coinHistory.unshift(...flips.reverse());coinHistory=coinHistory.slice(0,100);
        coinLastSummary=count===1?`Resultado: ${flips.at(-1)}`:`${fmt(heads)} Cara · ${fmt(tails)} Coroa · ${fmt(count)} moedas`;
        const face=document.getElementById('rtCoinFace');if(face){face.classList.toggle('rolling',!data.skipMotion);face.textContent=count===1?flips.at(-1).toUpperCase():'🪙';}
        const summary=document.getElementById('rtCoinSummary');if(summary)summary.textContent=coinLastSummary;
        const coinActions=root.querySelector('.rt-result-panel .rt-inline-actions');updateCopyButton(coinActions,coinLastSummary);
        const hist=root.querySelector('.rt-history');if(hist)hist.innerHTML=coinHistory.slice(0,20).map(x=>`<li>${esc(x)}</li>`).join('');
        const stats=root.querySelector('.rt-stat-grid');if(stats){const total=data.coin.heads+data.coin.tails;stats.innerHTML=`<div><strong>${fmt(data.coin.heads)}</strong><span>Cara · ${(data.coin.heads/total*100).toFixed(1)}%</span></div><div><strong>${fmt(data.coin.tails)}</strong><span>Coroa · ${(data.coin.tails/total*100).toFixed(1)}%</span></div><div><strong>${fmt(total)}</strong><span>Total</span></div>`;}
        recordUsage('coinFlips',count);recordUsage('randomDraws');
      } else if(kind==='dice'){
        const expression=String(inputValue(form,'expression')).trim(),answer=core.rollDice(expression);diceExpression=expression;diceHistory.unshift(answer);diceHistory=diceHistory.slice(0,50);renderDice();recordUsage('diceRolls');recordUsage('randomDraws');
      } else if(kind==='wheel-add'){
        const items=core.parseList(inputValue(form,'options'),{max:1000});wheel.options.push(...items.map(label=>({label:label.slice(0,160),weight:1})));wheel.options=wheel.options.slice(0,1000);wheelResult='';renderWheel();
      } else if(kind==='picker'){
        let items=readList(form,{dedupe:form.elements.dedupe.checked});if(!items.length)throw new Error('Adicione pelo menos um item.');const count=Number(inputValue(form,'count'));if(!Number.isSafeInteger(count)||count<1||count>10000)throw new Error('Quantidade inválida.');const noRepeat=form.elements.noRepeat.checked;if(noRepeat&&count>items.length)throw new Error('A quantidade supera os itens disponíveis sem repetição.');const selected=noRepeat?core.sampleWithoutReplacement(items,count):Array.from({length:count},()=>core.randomChoice(items));pickerHistory.unshift({items:selected});pickerHistory=pickerHistory.slice(0,30);if(form.elements.removeDrawn.checked){items=core.removeOccurrences(items,selected);form.elements.items.value=items.join('\n');}renderPicker();recordUsage('randomDraws');
      } else if(kind==='number'){
        const min=Number(inputValue(form,'min')),max=Number(inputValue(form,'max')),count=Number(inputValue(form,'count')),decimals=Number(inputValue(form,'decimals'));if(!Number.isFinite(min)||!Number.isFinite(max)||min>max)throw new Error('Mínimo e máximo inválidos.');if(!Number.isSafeInteger(count)||count<1||count>100000)throw new Error('Escolha até 100.000 resultados.');const scale=10**decimals,lo=Math.ceil(min*scale),hi=Math.floor(max*scale);if(!Number.isSafeInteger(lo)||!Number.isSafeInteger(hi)||lo>hi)throw new Error('A faixa não cabe em um número seguro.');const unique=!form.elements.repeat.checked;if(unique&&count>hi-lo+1)throw new Error('Não há valores distintos suficientes nessa faixa.');const values=unique?core.sampleIntegerRange(lo,hi,count).map(n=>(n/scale).toFixed(decimals)):Array.from({length:count},()=> (core.randomInteger(lo,hi)/scale).toFixed(decimals));const nums=values.map(Number);numberHistory.unshift({values,min,max,mean:(nums.reduce((a,b)=>a+b,0)/nums.length).toFixed(decimals)});numberHistory=numberHistory.slice(0,30);renderNumber();recordUsage('randomDraws');
      } else if(kind==='decision'){
        const question=inputValue(form,'question').trim().slice(0,240),options=inputValue(form,'mode')==='three'?['Sim','Não','Talvez']:['Sim','Não'];decisionHistory.unshift({question,answer:core.randomChoice(options)});decisionHistory=decisionHistory.slice(0,30);renderDecision();recordUsage('randomDraws');
      } else if(kind==='teams'){
        const people=readList(form,{dedupe:form.elements.dedupe.checked});if(!people.length)throw new Error('Adicione pelo menos uma pessoa.');const amount=Number(inputValue(form,'count'));if(!Number.isSafeInteger(amount)||amount<1)throw new Error('Informe uma quantidade válida.');const count=inputValue(form,'mode')==='size'?Math.ceil(people.length/amount):amount;if(count>1000)throw new Error('O limite é de 1.000 equipes.');teamResult={teams:core.createTeams(people,count),names:Array.from({length:count},(_,i)=>`Time ${i+1}`),people,teamCount:count};renderTeams();recordUsage('randomDraws');
      } else if(kind==='shuffle'){
        const items=readList(form,{dedupe:form.elements.dedupe.checked});if(!items.length)throw new Error('Adicione itens para embaralhar.');shuffleResult=core.shuffle(items);renderShuffle();recordUsage('randomDraws');
      } else if(kind==='guess'){
        const difficulty=inputValue(form,'difficulty');const ranges={easy:[1,10],normal:[1,100],hard:[1,1000]};let [min,max]=ranges[difficulty]||[Number(inputValue(form,'min')),Number(inputValue(form,'max'))];if(!Number.isSafeInteger(min)||!Number.isSafeInteger(max)||min>=max||max-min>1_000_000_000)throw new Error('Informe uma faixa válida de até 1 bilhão de números.');guessGame={difficulty,min,max,target:core.randomInteger(min,max),attempts:0,done:false,message:'Tente adivinhar!'};renderGuess();
      } else if(kind==='guess-submit'){
        if(!guessGame||guessGame.done)throw new Error('Comece um novo jogo primeiro.');const guess=Number(inputValue(form,'guess'));if(!Number.isSafeInteger(guess)||guess<guessGame.min||guess>guessGame.max)throw new Error('Palpite fora da faixa.');guessGame.attempts++;if(guess===guessGame.target){guessGame.done=true;guessGame.message=`Acertou! O número era ${guessGame.target}.`;const old=Number(data.records.guesses[guessGame.difficulty])||Infinity;if(guessGame.attempts<old)data.records.guesses[guessGame.difficulty]=guessGame.attempts;save();}else guessGame.message=guess<guessGame.target?'Muito baixo.':'Muito alto.';renderGuess();
      } else if(kind==='letter'){
        let mode=inputValue(form,'mode'),count=Number(inputValue(form,'count'));if(!Number.isSafeInteger(count)||count<1||count>256)throw new Error('Escolha de 1 a 256 caracteres.');const letters=mode==='upper'?'ABCDEFGHIJKLMNOPQRSTUVWXYZ':mode==='lower'?'abcdefghijklmnopqrstuvwxyz':'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';let chars=letters;if(mode==='string'){if(form.elements.numbers.checked)chars+='0123456789';if(form.elements.symbols.checked)chars+='!@#$%&*+-_?';}window.__ntcRandomText=Array.from({length:count},()=>core.randomCharacter(chars)).join('');renderLetter();recordUsage('generations');
      }
    } catch(error){announce(error.message||'Confira os valores informados.');}
  }
  function submitListTool(action) {
    const form=root.querySelector(action==='save-current-list'?'[data-form="picker"],[data-form="teams"],[data-form="shuffle"]':'[data-form="picker"],[data-form="teams"],[data-form="shuffle"]');if(!form)return;
    try{saveCurrentList(readList(form));}catch(error){announce(error.message);}
  }
  function removeDuplicateInput(form) { const area=form?.querySelector('textarea[name="items"]');if(!area)return;try{area.value=core.parseList(area.value,{dedupe:true}).join('\n');announce('Duplicados removidos da lista.');}catch(error){announce(error.message);} }
  function handleClick(event) {
    const fav=event.target.closest('[data-favorite]');if(fav){event.preventDefault();event.stopPropagation();toggleFavorite(fav.dataset.favorite);return;}
    const open=event.target.closest('[data-open-tool]');if(open){openTool(open.dataset.openTool);return;}
    const copyTarget=event.target.closest('[data-copy]');if(copyTarget){void copy(copyCache.get(copyTarget.dataset.copy)||'');return;}
    const preset=event.target.closest('[data-dice-preset]');if(preset){diceExpression=preset.dataset.dicePreset;const input=root.querySelector('[data-form="dice"] [name="expression"]');if(input)input.value=diceExpression;return;}
    const rowInput=event.target.closest('[data-wheel-label],[data-wheel-weight]');
    const duplicate=event.target.closest('[data-wheel-duplicate]');if(duplicate){if(wheel.options.length>=1000){announce('O limite é de 1.000 opções na roleta.');return;}const i=Number(duplicate.dataset.wheelDuplicate);if(wheel.options[i])wheel.options.splice(i+1,0,{...wheel.options[i]});wheelResult='';renderWheel();return;}
    const remove=event.target.closest('[data-wheel-remove]');if(remove){wheel.options.splice(Number(remove.dataset.wheelRemove),1);wheelResult='';renderWheel();return;}
    const moveUp=event.target.closest('[data-wheel-up]');if(moveUp){const i=Number(moveUp.dataset.wheelUp);if(i>0)[wheel.options[i-1],wheel.options[i]]=[wheel.options[i],wheel.options[i-1]];renderWheel();return;}
    const moveDown=event.target.closest('[data-wheel-down]');if(moveDown){const i=Number(moveDown.dataset.wheelDown);if(i<wheel.options.length-1)[wheel.options[i],wheel.options[i+1]]=[wheel.options[i+1],wheel.options[i]];renderWheel();return;}
    if(rowInput)return;
    const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;
    if(action==='home'){renderHome();current='home';}
    else if(action==='spin-wheel')spinWheel();
    else if(action==='save-current-list')submitListTool(action);
    else if(action==='delete-list'){const select=root.querySelector('[data-action="load-list"]');data.lists=data.lists.filter(x=>x.id!==select?.value);save();renderTool(current);}
    else if(action==='save-wheel'){try{parseWheelDraft();const name=root.querySelector('[data-wheel-name]')?.value.trim();if(!name)throw new Error('Informe um nome para a roleta.');wheel.name=name.slice(0,60);wheel.id=`wheel-${Date.now()}-${data.wheels.length}`;data.wheels.unshift({...wheel,options:cleanOptions(wheel.options)});data.wheels=data.wheels.slice(0,100);save();renderWheel();announce('Roleta salva neste dispositivo.');}catch(error){announce(error.message);}}
    else if(action==='update-wheel'){try{const options=parseWheelDraft(),name=root.querySelector('[data-wheel-name]')?.value.trim();if(!name)throw new Error('Informe um nome para a roleta.');const saved=data.wheels.find(item=>item.id===wheel.id);if(!saved)throw new Error('Esta roleta não está mais salva.');wheel.name=name.slice(0,60);wheel.options=options;saved.name=wheel.name;saved.options=cleanOptions(options);saved.removeWinner=Boolean(wheel.removeWinner);save();renderWheel();announce('Alterações da roleta salvas.');}catch(error){announce(error.message);}}
    else if(action==='rename-wheel'){const name=root.querySelector('[data-wheel-name]')?.value.trim();if(!name){announce('Informe um nome para a roleta.');return;}const saved=data.wheels.find(x=>x.id===wheel.id);if(saved){saved.name=name.slice(0,60);wheel.name=saved.name;save();renderWheel();announce('Roleta renomeada.');}}
    else if(action==='duplicate-wheel'){const source=data.wheels.find(x=>x.id===wheel.id);if(source){const duplicate={...source,id:`wheel-${Date.now()}-${data.wheels.length}`,name:`${source.name} (cópia)`,options:cleanOptions(source.options)};data.wheels.unshift(duplicate);wheel={...duplicate,options:cleanOptions(duplicate.options)};save();renderWheel();announce('Roleta duplicada.');}}
    else if(action==='delete-wheel'){data.wheels=data.wheels.filter(x=>x.id!==wheel.id);wheel={id:'',name:'Minha roleta',options:[],removeWinner:false};wheelResult='';save();renderWheel();announce('Roleta removida.');}
    else if(action==='draw-card'||action==='draw-cards'){if(!deck?.length){announce('O baralho acabou. Reinicie para embaralhar novamente.');return;}if(action==='draw-card'){const c=deck.shift();cardsMarkup([c]);recordUsage('randomDraws');}else{const count=Number(root.querySelector('#rtCardCount')?.value);if(!Number.isSafeInteger(count)||count<2||count>deck.length){announce(deck.length<2?'São necessárias pelo menos duas cartas restantes para comprar várias.':`Escolha de 2 a ${deck.length} cartas.`);return;}cardsMarkup(deck.splice(0,count));recordUsage('randomDraws',count);}}
    else if(action==='reset-deck'){deck=core.shuffle(core.createDeck(deckJokers));drawnCards=[];cardsMarkup([]);announce('Baralho embaralhado novamente.');}
    else if(action==='reset-coin'){data.coin={heads:0,tails:0};coinHistory=[];coinLastSummary='';save();renderCoin();}
    else if(action==='clear-coin-history'){coinHistory=[];coinLastSummary='';renderCoin();}
    else if(action==='clear-dice-history'){diceHistory=[];renderDice();}
    else if(action==='clear-picker-history'){pickerHistory=[];renderPicker();}
    else if(action==='clear-number-history'){numberHistory=[];renderNumber();}
    else if(action==='clear-decision-history'){decisionHistory=[];renderDecision();}
    else if(action==='reset-rps'){data.rps={wins:0,draws:0,losses:0};save();renderRps();}
    else if(action==='reshuffle-teams'){if(teamResult)teamResult.teams=core.createTeams(teamResult.people,teamResult.teamCount);renderTeams();}
    else if(action==='reshuffle-list'){if(shuffleResult)shuffleResult=core.shuffle(shuffleResult);renderShuffle();}
    else if(action==='use-shuffle-as-input'){const result=shuffleResult?.join('\n');renderShuffle();const area=root.querySelector('[data-form="shuffle"] textarea');if(area)area.value=result||'';}
    else if(action==='start-higher'){higherGame={current:core.randomInteger(1,100),streak:0,endedStreak:null,over:false,message:'O próximo valor será maior ou menor?'};renderHigher();}
    else if(action==='higher-guess'||action==='lower-guess'){if(!higherGame||higherGame.over)return;const round=core.resolveHigherLowerRound(higherGame.current,higherGame.streak,action==='higher-guess'?'higher':'lower',core.randomInteger(1,100));Object.assign(higherGame,round);if(round.correct&&round.streak>data.records.higherBest){data.records.higherBest=round.streak;save();}renderHigher();}
    else if(action==='reaction-click')reactionClick();
    else if(action==='start-cps')startCps();
    else if(action==='cps-click'&&cpsGame.active){cpsGame.clicks++;const status=root.querySelector('#rtCpsStatus');if(status)status.textContent=`${cpsGame.clicks} cliques`;}
    else if(action==='generate-color'){window.__ntcRandomColor=`#${[0,0,0].map(()=>core.randomInteger(0,255).toString(16).padStart(2,'0')).join('')}`;renderColor();}
  }
  function reactionClick(){if(reactionGame.phase==='ready'){reactionGame.phase='wait';reactionGame.message='Espere o sinal…';const delay=core.randomInteger(1200,3800);reactionGame.started=0;reactionGame.timeout=setTimeout(()=>{if(reactionGame.phase!=='wait')return;reactionGame.phase='go';reactionGame.started=performance.now();reactionGame.message='Agora!';if(current==='reaction')renderReaction();},delay);renderReaction();}else if(reactionGame.phase==='wait'){clearTimeout(reactionGame.timeout);reactionGame.phase='ready';reactionGame.message='Muito cedo! Comece de novo quando estiver pronto.';renderReaction();}else if(reactionGame.phase==='go'){const time=Math.max(1,Math.round(performance.now()-reactionGame.started));data.records.reactionBest=data.records.reactionBest?Math.min(data.records.reactionBest,time):time;data.records.reactionSamples.push(time);data.records.reactionSamples=data.records.reactionSamples.slice(-50);save();reactionGame={phase:'ready',message:`${time} ms — bom reflexo!`,started:0,timeout:0};renderReaction();}}
  function startCps(){if(cpsGame.active)return;cpsGame.duration=Number(root.querySelector('#rtCpsDuration')?.value)||5;cpsGame={...cpsGame,active:true,started:performance.now(),clicks:0};renderCps();cpsGame.timeout=setTimeout(()=>{const elapsed=Math.max(.01,(performance.now()-cpsGame.started)/1000);const cps=cpsGame.clicks/elapsed;cpsGame.active=false;cpsGame.last={clicks:cpsGame.clicks,cps:Number(cps.toFixed(2))};data.records.cpsBest=Math.max(data.records.cpsBest,cpsGame.last.cps);save();if(current==='cps')renderCps();},cpsGame.duration*1000);}
  function spinRps(move){rpsMode=core.resolveRpsMode(move,rpsMode);const moves=rpsMode==='expanded'?['pedra','papel','tesoura','lagarto','spock']:['pedra','papel','tesoura'];const computer=core.randomChoice(moves);const result=core.rpsResult(move,computer,rpsMode);data.rps[result==='vitória'?'wins':result==='empate'?'draws':'losses']++;save();window.__ntcRpsLast={player:move,computer,result};renderRps();recordUsage('randomDraws');}
  root.addEventListener('click',event=>{const rps=event.target.closest('[data-rps]');if(rps){spinRps(rps.dataset.rps);return;}handleClick(event);});
  root.addEventListener('submit',event=>{const form=event.target.closest('[data-form]');if(!form)return;event.preventDefault();performForm(form);});
  root.addEventListener('change',event=>{
    if(event.target.id==='rtJokers'){deckJokers=event.target.checked;drawnCards=[];deck=core.shuffle(core.createDeck(deckJokers));cardsMarkup([]);const status=root.querySelector('.rt-section-title span');if(status)status.textContent=`${deck.length} / ${deckJokers?54:52} cartas restantes · 0 compradas`;}
    if(event.target.matches('[data-remove-winner]'))wheel.removeWinner=event.target.checked;
    if(event.target.matches('[data-wheel-label]')){const i=Number(event.target.dataset.wheelLabel);if(wheel.options[i])wheel.options[i].label=event.target.value;drawWheel();}
    if(event.target.matches('[data-wheel-weight]')){const i=Number(event.target.dataset.wheelWeight);if(wheel.options[i])wheel.options[i].weight=Number(event.target.value);drawWheel();}
    if(event.target.matches('[data-action="load-wheel"]')){const found=data.wheels.find(x=>x.id===event.target.value);if(found){wheel={...found,options:cleanOptions(found.options)};wheelResult='';renderWheel();}}
    if(event.target.matches('[data-action="load-wheel-list"]')){const list=data.lists.find(item=>item.id===event.target.value);if(list){wheel.options=list.items.map(label=>({label,weight:1}));wheelResult='';renderWheel();}}
    if(event.target.matches('[data-action="load-list"]'))loadSavedList(event.target.value);
    if(event.target.matches('[data-form="guess"] [name="difficulty"]'))root.querySelector('.rt-custom-range')?.classList.toggle('hidden',event.target.value!=='custom');
    if(event.target.matches('#rtRpsMode')){rpsMode=event.target.value==='expanded'?'expanded':'classic';root.querySelectorAll('[data-rps="lagarto"],[data-rps="spock"]').forEach(button=>button.hidden=rpsMode!=='expanded');}
  });
  root.addEventListener('input',event=>{
    if(event.target.matches('[data-wheel-label]')){const i=Number(event.target.dataset.wheelLabel);if(wheel.options[i])wheel.options[i].label=event.target.value;drawWheel();}
    if(event.target.matches('[data-wheel-weight]')){const i=Number(event.target.dataset.wheelWeight);if(wheel.options[i])wheel.options[i].weight=Number(event.target.value);drawWheel();}
  });
  const motion=document.getElementById('randomToolsSkipMotion');motion.checked=Boolean(data.skipMotion);motion.onchange=()=>{data.skipMotion=motion.checked;save();};
  window.NTCRandomTools={open:()=>{document.getElementById('randomToolsSkipMotion').checked=Boolean(data.skipMotion);renderHome();}};
  renderHome();
})();
