// Windows-only, bounded RPC host. The renderer never supplies uninstall commands or removal paths.
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Web.Script.Serialization;
using Microsoft.Win32;
using System.Runtime.InteropServices;
using System.Security.AccessControl;
using System.Security.Principal;
using System.Security.Cryptography;
using System.IO.Pipes;
using Microsoft.Win32.SafeHandles;

class UninstallerHost {
  static JavaScriptSerializer json = new JavaScriptSerializer { MaxJsonLength=64*1024*1024, RecursionLimit=100 };
  static string store;
  const string UninstallKey="Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall";
  static Dictionary<string,Dictionary<string,object>> programs=new Dictionary<string,Dictionary<string,object>>();
  static Dictionary<string,Dictionary<string,object>> scans=new Dictionary<string,Dictionary<string,object>>();
  static Dictionary<string,Dictionary<string,object>> snapshots=new Dictionary<string,Dictionary<string,object>>();
  static Dictionary<string,Dictionary<string,object>> monitors=new Dictionary<string,Dictionary<string,object>>();
  static Dictionary<string,string> picked=new Dictionary<string,string>();
  static Dictionary<string,string> pickedIdentity=new Dictionary<string,string>();
  static Dictionary<string,string> normalizedPaths=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);
  static bool Admin { get { return new WindowsPrincipal(WindowsIdentity.GetCurrent()).IsInRole(WindowsBuiltInRole.Administrator); } }
  static Dictionary<string,object> D(params object[] p) { var d=new Dictionary<string,object>(); for(int i=0;i<p.Length;i+=2)d[(string)p[i]]=p[i+1];return d; }
  static string S(IDictionary<string,object>d,string k) { object v;return d!=null&&d.TryGetValue(k,out v)&&v!=null?Convert.ToString(v):""; }
  static bool B(IDictionary<string,object>d,string k) { object v;return d!=null&&d.TryGetValue(k,out v)&&v is bool&&(bool)v; }
  static string ID(){return Guid.NewGuid().ToString("N");}
  static string Hash(string v){using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(Encoding.UTF8.GetBytes(v))).Replace("-","").ToLowerInvariant();}
  static string Full(string v){try{if(string.IsNullOrWhiteSpace(v)||v.IndexOf('\0')>=0||!Path.IsPathRooted(v)||v.StartsWith("\\\\"))return "";string cached;if(normalizedPaths.TryGetValue(v,out cached))return cached;string path=Path.GetFullPath(Environment.ExpandEnvironmentVariables(v.Trim().Trim('"'))).TrimEnd('\\');if(normalizedPaths.Count<200000)normalizedPaths[v]=path;return path;}catch{return "";}}
  static bool Under(string p,string r){p=Full(p);r=Full(r);return p!=""&&r!=""&&(p.Equals(r,StringComparison.OrdinalIgnoreCase)||p.StartsWith(r+"\\",StringComparison.OrdinalIgnoreCase));}
  static string RegistryId(string hive,int view,string key){return "reg:"+hive+":"+view+":"+Hash(key.ToLowerInvariant());}
  static RegistryKey Base(string hive,int view){if(hive!="HKCU"&&hive!="HKLM")throw new Exception("Hive inválida.");return RegistryKey.OpenBaseKey(hive=="HKCU"?RegistryHive.CurrentUser:RegistryHive.LocalMachine,view==32?RegistryView.Registry32:RegistryView.Registry64);}
  static bool Sensitive(string p){
    p=Full(p);if(p==""||p.Length<=3)return true;
    string[] parents={Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),Environment.GetFolderPath(Environment.SpecialFolder.CommonProgramFiles),Environment.GetFolderPath(Environment.SpecialFolder.CommonProgramFilesX86),Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)};
    if(parents.Any(x=>Full(x)==p||Under(x,p)))return true;
    foreach(var data in new[]{Environment.GetFolderPath(Environment.SpecialFolder.MyPictures),Environment.GetFolderPath(Environment.SpecialFolder.MyVideos),Environment.GetFolderPath(Environment.SpecialFolder.MyMusic),Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Downloads"),Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Temp")})if(Full(data)==p||Under(data,p))return true;
    string windows=Environment.GetFolderPath(Environment.SpecialFolder.Windows);
    if(Under(p,windows)||Under(windows,p)||Under(p,store)||Under(store,p))return true;
    return p.IndexOf("\\WindowsApps",StringComparison.OrdinalIgnoreCase)>=0||p.IndexOf("\\Windows Kits",StringComparison.OrdinalIgnoreCase)>=0||p.IndexOf("\\Common Files",StringComparison.OrdinalIgnoreCase)>=0||p.IndexOf("\\NTC Uninstaller Quarantine",StringComparison.OrdinalIgnoreCase)>=0||p.IndexOf("\\NTC Utilities Uninstaller Backups",StringComparison.OrdinalIgnoreCase)>=0;
  }
  static bool Link(string p){return (File.GetAttributes(p)&FileAttributes.ReparsePoint)!=0;}
  static void SafeAncestors(string p){p=Full(p);if(p==""||Sensitive(p))throw new Exception("Caminho protegido ou inválido.");var cur=p;while(cur.Length>3){if(File.Exists(cur)||Directory.Exists(cur)){if(Link(cur))throw new Exception("Reparse point/junction: preservado.");}cur=Path.GetDirectoryName(cur);if(string.IsNullOrEmpty(cur))break;}}
  static bool Shared(string root,string id){Dictionary<string,object> chosen;programs.TryGetValue(id,out chosen);return programs.Values.Any(p=>S(p,"id")!=id&&!(chosen!=null&&S(p,"name")==S(chosen,"name")&&S(p,"command")==S(chosen,"command")&&S(p,"location")==S(chosen,"location"))&&S(p,"location")!=""&&(Under(root,S(p,"location"))||Under(S(p,"location"),root)));}
  static bool IsProtectedName(string n){return System.Text.RegularExpressions.Regex.IsMatch(n,"(?i)(NTC Utilities|Microsoft Visual C\\+\\+|Microsoft .NET|WebView2|DirectX|Windows .*Update|Security Update|Runtime|Driver|SDK|Redistributable|Python|Node\\.js|Java|Antivirus|Anti-virus)");}
  [DllImport("msi.dll",CharSet=CharSet.Unicode)]static extern int MsiQueryProductState(string product);
  [DllImport("shell32.dll",CharSet=CharSet.Unicode)]static extern IntPtr CommandLineToArgvW(string cmd,out int argc);
  [DllImport("kernel32.dll")]static extern IntPtr LocalFree(IntPtr h);
  static string Quote(string s){if(s.Length>0&&!s.Any(c=>char.IsWhiteSpace(c)||c=='"'))return s;var b=new StringBuilder("\"");int slash=0;foreach(char c in s){if(c=='\\'){slash++;continue;}if(c=='"'){b.Append('\\',slash*2+1);b.Append(c);}else{b.Append('\\',slash);b.Append(c);}slash=0;}b.Append('\\',slash*2);b.Append('"');return b.ToString();}
  static string[] SplitCommand(string command){
    command=Environment.ExpandEnvironmentVariables(command??"").Trim();if(command=="")return new string[0];
    // Resolve unquoted paths with spaces only when an unambiguous existing .exe prefix exists.
    if(!command.StartsWith("\"")){int pos=command.IndexOf(".exe",StringComparison.OrdinalIgnoreCase);if(pos>=0&&File.Exists(command.Substring(0,pos+4)))command=Quote(command.Substring(0,pos+4))+command.Substring(pos+4);}
    int count;IntPtr ptr=CommandLineToArgvW(command,out count);if(ptr==IntPtr.Zero)throw new Exception("Comando inválido.");try{var a=new string[count];for(int i=0;i<count;i++)a[i]=Marshal.PtrToStringUni(Marshal.ReadIntPtr(ptr,i*IntPtr.Size));return a;}finally{LocalFree(ptr);}
  }
  static string[] ValidExe(string command){var a=SplitCommand(command);if(a.Length==0)throw new Exception("Desinstalador não registrado.");var file=Full(a[0]);var blocked=new[]{"cmd.exe","powershell.exe","pwsh.exe","wscript.exe","cscript.exe","rundll32.exe","regsvr32.exe","mshta.exe","reg.exe","sc.exe"};if(file==""||!file.EndsWith(".exe",StringComparison.OrdinalIgnoreCase)||!File.Exists(file)||blocked.Contains(Path.GetFileName(file).ToLowerInvariant()))throw new Exception("Desinstalador ausente ou despachante de comandos não suportado com segurança.");a[0]=file;return a;}
  static object Inventory(bool appx){
    if(appx){var x=Bridge("appx",D());foreach(var id in programs.Values.Where(p=>S(p,"type")=="MSIX/AppX").Select(p=>S(p,"id")).ToArray())programs.Remove(id);var arr=x["items"] as IEnumerable;if(arr!=null)foreach(var v in arr){var d=(Dictionary<string,object>)v;d["id"]="appx:"+Hash(S(d,"package"));d["type"]="MSIX/AppX";d["size"]=null;d["date"]="";d["broken"]=false;programs[S(d,"id")]=d;}return D("items",programs.Values.Where(p=>S(p,"type")=="MSIX/AppX").ToArray());}
    foreach(var old in programs.Values.Where(p=>S(p,"type")!="MSIX/AppX").Select(p=>S(p,"id")).ToArray())programs.Remove(old);
    var warnings=new List<string>();
    foreach(string hive in new[]{"HKCU","HKLM"})foreach(int view in new[]{64,32}){
      try{using(var b=Base(hive,view))using(var root=b.OpenSubKey(UninstallKey)){
        if(root==null)continue;foreach(var name in root.GetSubKeyNames())try{using(var k=root.OpenSubKey(name)){
          var display=Convert.ToString(k.GetValue("DisplayName"));if(string.IsNullOrWhiteSpace(display))continue;
          var command=Convert.ToString(k.GetValue("UninstallString"));var quiet=Convert.ToString(k.GetValue("QuietUninstallString"));var location=Full(Convert.ToString(k.GetValue("InstallLocation")));var product=Convert.ToString(k.GetValue("WindowsInstaller"))=="1"&&System.Text.RegularExpressions.Regex.IsMatch(name,"^\\{[0-9a-fA-F-]{36}\\}$")?name:"";
          string issue="";bool broken=false;if(product!=""){if(MsiQueryProductState(product)<0){issue="Registro MSI não confirma o produto instalado.";broken=true;}}else try{ValidExe(command!=""?command:quiet);}catch(Exception e){issue=e.Message;var parsed=SplitCommand(command!=""?command:quiet);broken=parsed.Length==0||(Full(parsed[0])!=""&&!File.Exists(Full(parsed[0])));}
          if(location!=""&&!Directory.Exists(location)){issue="Pasta registrada não existe.";broken=true;}
          var item=D("id",RegistryId(hive,view,UninstallKey+"\\"+name),"name",display,"version",Convert.ToString(k.GetValue("DisplayVersion")),"publisher",Convert.ToString(k.GetValue("Publisher")),"location",location,"type",product!=""?"MSI":"EXE","architecture",view+" bits · visão do registro","date",Convert.ToString(k.GetValue("InstallDate")),"size",k.GetValue("EstimatedSize")==null?null:(object)(Convert.ToInt64(k.GetValue("EstimatedSize"))*1024),"sizeSource","Informado pelo instalador","command",command,"quiet",quiet,"productCode",product,"website",Convert.ToString(k.GetValue("URLInfoAbout")),"icon",Convert.ToString(k.GetValue("DisplayIcon")),"hive",hive,"view",view,"key",UninstallKey+"\\"+name,"source",hive+" · "+view+" bits · "+UninstallKey+"\\"+name,"broken",issue!="","issue",issue,"protected",Convert.ToString(k.GetValue("SystemComponent"))=="1"||k.GetValue("ParentKeyName")!=null||IsProtectedName(display)||display=="NTC Utilities");
          item["broken"]=broken;item["fingerprint"]=Hash(json.Serialize(item));programs[S(item,"id")]=item;
        }}catch(Exception e){warnings.Add(name+": "+e.Message);}
      }}catch(Exception e){warnings.Add(hive+": "+e.Message);}
    }
    return D("items",programs.Values.Where(p=>S(p,"type")!="MSIX/AppX").GroupBy(p=>S(p,"name")+"|"+S(p,"location")+"|"+S(p,"command")+"|"+S(p,"version")).Select(g=>g.OrderByDescending(p=>Convert.ToInt32(p["view"])).First()).ToArray(),"warnings",warnings);
  }
  static Dictionary<string,object> ProgramBy(string id){Dictionary<string,object> p;if(!programs.TryGetValue(id,out p))throw new Exception("Atualize a lista e selecione um programa válido.");return p;}
  static List<string> Roots(Dictionary<string,object> p){var roots=new List<string>();var loc=S(p,"location");if(loc!=""&&!Sensitive(loc)&&!Shared(loc,S(p,"id")))roots.Add(loc);return roots;}
  static bool Related(string command,List<string> roots){try{var a=SplitCommand(command);return a.Length>0&&roots.Any(r=>Under(a[0],r));}catch{return false;}}
  static Dictionary<string,object> Candidate(string cat,string path,string confidence,string reason,bool personal,bool eligible,object target){var t=(Dictionary<string,object>)target;var metadata=D();foreach(var key in new[]{"command","commands","start","type","hive","view","key","value","valueKind","principal","logon"})if(t.ContainsKey(key))metadata[key]=t[key];if(t.ContainsKey("data")&&t["data"] is Dictionary<string,object>){var data=(Dictionary<string,object>)t["data"];if(data.ContainsKey("ApplicationName"))metadata["ApplicationName"]=data["ApplicationName"];}return D("id",ID(),"category",cat,"path",path,"confidence",confidence,"reasons",new[]{reason},"metadata",metadata,"personal",personal,"eligible",eligible,"selected",eligible&&confidence=="high"&&!personal,"target",target,"size",null);}
  static bool PersonalPath(string p){return System.Text.RegularExpressions.Regex.IsMatch(p,"(?i)(\\\\(saves?|mods?|workshop|screenshots?|profiles?|projects?|userdata|downloads|documents)(\\\\|$)|\\.(sav|db|sqlite|cfg|ini|json|txt|blend|psd|ntcproject)$)");}
  static Dictionary<string,object> Measure(string root,int budget){long bytes=0;int files=0,dirs=0;bool personal=false,incomplete=false;var signatures=new List<string>();var stack=new Stack<string>();stack.Push(root);while(stack.Count>0){var p=stack.Pop();if(++files>budget){incomplete=true;break;}try{if(Link(p)){incomplete=true;continue;}personal|=PersonalPath(p);string relative=p.Substring(root.Length);if(Directory.Exists(p)){dirs++;signatures.Add(relative+"|D|"+Directory.GetLastWriteTimeUtc(p).Ticks);foreach(var q in Directory.GetFileSystemEntries(p))stack.Push(q);}else{var info=new FileInfo(p);bytes+=info.Length;signatures.Add(relative+"|"+info.Length+"|"+info.LastWriteTimeUtc.Ticks);}}catch{incomplete=true;}}signatures.Sort(StringComparer.OrdinalIgnoreCase);return D("bytes",bytes,"entries",files,"folders",dirs,"personal",personal,"incomplete",incomplete,"digest",Hash(string.Join("\n",signatures)));}
  static void RegistryCandidates(string hive,int view,string key,string category,List<string> roots,List<Dictionary<string,object>> items,int depth,ref int budget,bool readOnly){
    if(depth<0||budget--<=0)return;try{using(var b=Base(hive,view))using(var k=b.OpenSubKey(key)){
      if(k==null)return;foreach(var value in k.GetValueNames()){var content=Convert.ToString(k.GetValue(value));if(Related(content,roots)||roots.Any(r=>Full(content)==r)){bool uncertain=readOnly||category=="Registro"||key.IndexOf("\\CLSID",StringComparison.OrdinalIgnoreCase)>=0||key.IndexOf("shellex",StringComparison.OrdinalIgnoreCase)>=0;items.Add(Candidate(category,hive+"\\"+key+" · "+(value==""?"(Padrão)":value),uncertain?"medium":"high","O valor aponta diretamente para um executável/caminho registrado; chaves gerais, COM e extensões permanecem protegidas.",false,!uncertain,D("kind","registryValue","hive",hive,"view",view,"key",key,"value",value,"data",k.GetValue(value, null, RegistryValueOptions.DoNotExpandEnvironmentNames),"valueKind",k.GetValueKind(value).ToString())));}}
      if(depth>0)foreach(var n in k.GetSubKeyNames())RegistryCandidates(hive,view,key+"\\"+n,category,roots,items,depth-1,ref budget,readOnly);
    }}catch{}
  }
  static IEnumerable<string> SafeFiles(string root,string pattern,int budget){var list=new List<string>();var dirs=new Stack<string>();if(Directory.Exists(root))dirs.Push(root);while(dirs.Count>0&&list.Count<budget){var p=dirs.Pop();try{if(Link(p))continue;foreach(var file in Directory.EnumerateFiles(p,pattern)){if(list.Count>=budget)break;list.Add(file);}if(list.Count>=budget)break;foreach(var x in Directory.GetDirectories(p))if(!Link(x))dirs.Push(x);}catch{}}return list;}
  static string Shortcut(string file){dynamic shell=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell"));try{dynamic shortcut=shell.CreateShortcut(file);return Convert.ToString(shortcut.TargetPath);}finally{Marshal.FinalReleaseComObject(shell);}}
  static List<Dictionary<string,object>> Resources(List<string> roots,bool deep,List<string> warnings){
    var items=new List<Dictionary<string,object>>();
    if(roots.Count==0)return items;
    foreach(string hive in new[]{"HKCU","HKLM"})foreach(int view in new[]{64,32}){
      int budget=deep?20000:3000;
      RegistryCandidates(hive,view,"Software\\Microsoft\\Windows\\CurrentVersion\\Run","Inicialização",roots,items,0,ref budget,false);
      RegistryCandidates(hive,view,"Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce","Inicialização",roots,items,0,ref budget,false);
      if(deep){RegistryCandidates(hive,view,"Software\\Classes","Associações / protocolos",roots,items,4,ref budget,false);RegistryCandidates(hive,view,"Software\\Classes\\CLSID","COM / extensões",roots,items,3,ref budget,true);RegistryCandidates(hive,view,"Software","Registro",roots,items,2,ref budget,false);if(budget<=0)warnings.Add("Limite de chaves atingido: análise do registro é parcial.");}
    }
    try{using(var b=Base("HKLM",64))using(var service=b.OpenSubKey("SYSTEM\\CurrentControlSet\\Services"))foreach(var n in service.GetSubKeyNames())using(var k=service.OpenSubKey(n)){
      string command=Convert.ToString(k.GetValue("ImagePath"));if(!Related(command,roots))continue;int type=Convert.ToInt32(k.GetValue("Type",0));bool driver=(type&3)!=0;var basic=new[]{"Type","Start","ErrorControl","ImagePath","DisplayName","ObjectName","Description"};bool simple=type==16&&Convert.ToString(k.GetValue("ObjectName","LocalSystem"))=="LocalSystem"&&k.GetSubKeyNames().Length==0&&k.GetValueNames().All(v=>basic.Contains(v));var c=Candidate(driver?"Drivers":"Serviços",n,"high","ImagePath aponta para a pasta exclusiva. Só serviço standalone simples LocalSystem pode ser removido; drivers, dependências e configurações avançadas são preservados.",false,simple,D("kind","service","name",n,"command",command,"start",k.GetValue("Start"),"type",type,"digest",Hash(json.Serialize(RegistryBackup(k)))));c["selected"]=false;try{using(var serviceStatus=new System.ServiceProcess.ServiceController(n))c["status"]=serviceStatus.Status.ToString();}catch{}items.Add(c);
    }}catch(Exception e){warnings.Add("Serviços: "+e.Message);}
    try{dynamic scheduler=Activator.CreateInstance(Type.GetTypeFromProgID("Schedule.Service"));scheduler.Connect();ScanTasks(scheduler.GetFolder("\\"),roots,items,0);Marshal.FinalReleaseComObject(scheduler);}catch(Exception e){warnings.Add("Tarefas: "+e.Message);}
    try{dynamic policy=Activator.CreateInstance(Type.GetTypeFromProgID("HNetCfg.FwPolicy2"));var allRules=new List<Dictionary<string,object>>();foreach(dynamic rule in policy.Rules)allRules.Add(FirewallData(rule));foreach(var rule in allRules){string app=S(rule,"ApplicationName");if(roots.Any(r=>Under(app,r))){bool exclusive=allRules.Count(r=>S(r,"Name")==S(rule,"Name"))==1&&S(rule,"ServiceName")==""&&!B(rule,"Advanced");var c=Candidate("Firewall",S(rule,"Name"),"high","ApplicationName aponta diretamente para a instalação; nomes duplicados, regras de serviço e configurações avançadas são preservados.",false,exclusive,D("kind","firewall","data",rule,"digest",Hash(json.Serialize(rule))));c["selected"]=false;items.Add(c);}}Marshal.FinalReleaseComObject(policy);}catch(Exception e){warnings.Add("Firewall: "+e.Message);}
    foreach(var r in new[]{Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),Environment.GetFolderPath(Environment.SpecialFolder.CommonDesktopDirectory),Environment.GetFolderPath(Environment.SpecialFolder.Programs),Environment.GetFolderPath(Environment.SpecialFolder.CommonPrograms)})foreach(var lnk in SafeFiles(r,"*.lnk",3000))try{string target=Shortcut(lnk);if(roots.Any(p=>Under(target,p)))items.Add(Candidate("Atalhos",lnk,"high","O destino do atalho aponta para a instalação exclusiva.",false,true,D("kind","file","path",lnk,"identity",SafeFs.Identity(lnk),"shortcutTarget",target)));}catch{}
    foreach(var scope in new[]{EnvironmentVariableTarget.User,EnvironmentVariableTarget.Machine})foreach(DictionaryEntry v in Environment.GetEnvironmentVariables(scope)){var value=Convert.ToString(v.Value);if(value.Split(';').Any(segment=>roots.Any(r=>Under(segment,r))))items.Add(Candidate("Ambiente",scope+" · "+v.Key,"medium","Há um segmento de caminho associado; variável possivelmente compartilhada, preservada.",false,false,D("kind","environment","name",v.Key)));}
    return items.GroupBy(x=>S(x,"category")+S(x,"path")).Select(g=>g.First()).ToList();
  }
  static void ScanTasks(dynamic folder,List<string> roots,List<Dictionary<string,object>> items,int depth){if(depth>10)return;foreach(dynamic task in folder.GetTasks(0)){var commands=new List<string>();bool all=true,related=false;foreach(dynamic action in task.Definition.Actions)try{string command=Convert.ToString(action.Path);commands.Add(command);bool owned=roots.Any(r=>Under(command,r));all&=owned;related|=owned;}catch{all=false;}if(!related)continue;int logon=Convert.ToInt32(task.Definition.Principal.LogonType);string taskPath=Convert.ToString(task.Path);bool eligible=all&&(logon==3||logon==5)&&!taskPath.StartsWith("\\Microsoft\\Windows\\",StringComparison.OrdinalIgnoreCase);var c=Candidate("Tarefas agendadas",taskPath,"high","A tarefa tem ação na instalação. Só tarefas com todas as ações exclusivas e sem credencial armazenada são removíveis.",false,eligible,D("kind","task","xml",Convert.ToString(task.Xml),"commands",commands,"logon",logon,"principal",Convert.ToString(task.Definition.Principal.UserId)));c["selected"]=false;items.Add(c);}foreach(dynamic child in folder.GetFolders(0))ScanTasks(child,roots,items,depth+1);}
  static Dictionary<string,object> FirewallData(dynamic rule){int protocol=Convert.ToInt32(rule.Protocol);bool advanced=false;try{var extended=(IFirewallAdvanced)(object)rule;var interfaces=extended.Interfaces as Array;advanced=interfaces!=null&&interfaces.Length>0;advanced|=extended.EdgeTraversalOptions!=(Convert.ToBoolean(rule.EdgeTraversal)?1:0);advanced|=extended.SecureFlags!=0||!string.IsNullOrEmpty(extended.LocalAppPackageId)||!string.IsNullOrEmpty(extended.LocalUserOwner)||!string.IsNullOrEmpty(extended.LocalUserAuthorizedList)||!string.IsNullOrEmpty(extended.RemoteUserAuthorizedList)||!string.IsNullOrEmpty(extended.RemoteMachineAuthorizedList);}catch{advanced=true;}return D("Name",Convert.ToString(rule.Name),"Description",Convert.ToString(rule.Description),"ApplicationName",Convert.ToString(rule.ApplicationName),"ServiceName",Convert.ToString(rule.ServiceName),"Advanced",advanced,"Protocol",protocol,"LocalPorts",protocol==6||protocol==17?Convert.ToString(rule.LocalPorts):"","RemotePorts",protocol==6||protocol==17?Convert.ToString(rule.RemotePorts):"","LocalAddresses",Convert.ToString(rule.LocalAddresses),"RemoteAddresses",Convert.ToString(rule.RemoteAddresses),"IcmpTypesAndCodes",protocol==1||protocol==58?Convert.ToString(rule.IcmpTypesAndCodes):"","Direction",Convert.ToInt32(rule.Direction),"Enabled",Convert.ToBoolean(rule.Enabled),"Grouping",Convert.ToString(rule.Grouping),"Profiles",Convert.ToInt32(rule.Profiles),"EdgeTraversal",Convert.ToBoolean(rule.EdgeTraversal),"InterfaceTypes",Convert.ToString(rule.InterfaceTypes),"Action",Convert.ToInt32(rule.Action));}
  static void RemoveSystem(Dictionary<string,object> candidate,Dictionary<string,object> record,List<string> roots,Action persist){var t=(Dictionary<string,object>)candidate["target"];switch(S(t,"kind")){
    case "service":{string name=S(t,"name");using(var b=Base("HKLM",64))using(var k=b.OpenSubKey("SYSTEM\\CurrentControlSet\\Services\\"+name)){if(k==null)throw new Exception("Serviço já ausente.");var backup=RegistryBackup(k);if(Hash(json.Serialize(backup))!=S(t,"digest")||!Related(Convert.ToString(k.GetValue("ImagePath")),roots)||Convert.ToInt32(k.GetValue("Type",0))!=16)throw new Exception("Configuração do serviço mudou. Preservado.");record["backup"]=backup;persist();}using(var service=new System.ServiceProcess.ServiceController(name)){if(service.Status!=System.ServiceProcess.ServiceControllerStatus.Stopped){if(!service.CanStop)throw new Exception("Serviço não pode ser parado com segurança.");service.Stop();service.WaitForStatus(System.ServiceProcess.ServiceControllerStatus.Stopped,TimeSpan.FromSeconds(10));}}SafeService.Delete(name);record["rebootRequired"]=System.ServiceProcess.ServiceController.GetServices().Any(s=>s.ServiceName==name);break;}
    case "task":{dynamic scheduler=Activator.CreateInstance(Type.GetTypeFromProgID("Schedule.Service"));try{scheduler.Connect();string taskPath=S(candidate,"path"),parent=taskPath.Substring(0,taskPath.LastIndexOf('\\')+1),name=taskPath.Substring(taskPath.LastIndexOf('\\')+1);dynamic folder=scheduler.GetFolder(parent);dynamic task=folder.GetTask(name);string xml=Convert.ToString(task.Xml);if(xml!=S(t,"xml"))throw new Exception("Tarefa mudou. Preservada.");record["backup"]=D("xml",xml,"principal",S(t,"principal"),"logon",t["logon"]);persist();bool enabled=Convert.ToBoolean(task.Enabled);task.Enabled=false;try{folder.DeleteTask(name,0);}catch{try{task.Enabled=enabled;}catch{}throw;}}finally{Marshal.FinalReleaseComObject(scheduler);}break;}
    case "firewall":{dynamic policy=Activator.CreateInstance(Type.GetTypeFromProgID("HNetCfg.FwPolicy2"));try{var expected=(Dictionary<string,object>)t["data"];string name=S(expected,"Name");var matches=new List<object>();foreach(dynamic rule in policy.Rules)if(Convert.ToString(rule.Name)==name)matches.Add(rule);if(matches.Count!=1||Hash(json.Serialize(FirewallData(matches[0])))!=S(t,"digest"))throw new Exception("Regra mudou ou nome é compartilhado. Preservada.");record["backup"]=expected;persist();policy.Rules.Remove(name);}finally{Marshal.FinalReleaseComObject(policy);}break;}
  }}
  static void RestoreSystem(Dictionary<string,object> record){var t=(Dictionary<string,object>)record["target"];var backup=(Dictionary<string,object>)record["backup"];switch(S(t,"kind")){
    case "service":{string name=S(t,"name");if(System.ServiceProcess.ServiceController.GetServices().Any(s=>s.ServiceName==name))throw new Exception("Conflito: serviço já existe ou aguarda exclusão/reboot.");var values=((IEnumerable)backup["values"]).Cast<Dictionary<string,object>>().ToDictionary(v=>S(v,"name"),v=>v["data"]);SafeService.Create(name,values);break;}
    case "task":{dynamic scheduler=Activator.CreateInstance(Type.GetTypeFromProgID("Schedule.Service"));try{scheduler.Connect();string taskPath=S(record,"path"),parent=taskPath.Substring(0,taskPath.LastIndexOf('\\')+1),name=taskPath.Substring(taskPath.LastIndexOf('\\')+1);dynamic folder=scheduler.GetFolder(parent);bool exists=false;try{folder.GetTask(name);exists=true;}catch{}if(exists)throw new Exception("Conflito: tarefa já existe.");folder.RegisterTask(name,S(backup,"xml"),2,S(backup,"principal"),null,Convert.ToInt32(backup["logon"]),null);}finally{Marshal.FinalReleaseComObject(scheduler);}break;}
    case "firewall":{dynamic policy=Activator.CreateInstance(Type.GetTypeFromProgID("HNetCfg.FwPolicy2"));try{foreach(dynamic old in policy.Rules)if(Convert.ToString(old.Name)==S(backup,"Name"))throw new Exception("Conflito: regra já existe.");dynamic rule=Activator.CreateInstance(Type.GetTypeFromProgID("HNetCfg.FWRule"));rule.Name=S(backup,"Name");rule.Description=S(backup,"Description");rule.ApplicationName=S(backup,"ApplicationName");rule.Protocol=Convert.ToInt32(backup["Protocol"]);int protocol=Convert.ToInt32(backup["Protocol"]);if(protocol==6||protocol==17){rule.LocalPorts=S(backup,"LocalPorts");rule.RemotePorts=S(backup,"RemotePorts");}if(protocol==1||protocol==58)rule.IcmpTypesAndCodes=S(backup,"IcmpTypesAndCodes");rule.LocalAddresses=S(backup,"LocalAddresses");rule.RemoteAddresses=S(backup,"RemoteAddresses");rule.Direction=Convert.ToInt32(backup["Direction"]);rule.Enabled=Convert.ToBoolean(backup["Enabled"]);rule.Grouping=S(backup,"Grouping");rule.Profiles=Convert.ToInt32(backup["Profiles"]);rule.EdgeTraversal=Convert.ToBoolean(backup["EdgeTraversal"]);rule.InterfaceTypes=S(backup,"InterfaceTypes");rule.Action=Convert.ToInt32(backup["Action"]);policy.Rules.Add(rule);}finally{Marshal.FinalReleaseComObject(policy);}break;}
  }}
  static Dictionary<string,object> Analyze(Dictionary<string,object> p,bool deep,bool forced){
    var frozen=json.Deserialize<Dictionary<string,object>>(json.Serialize(p));var roots=Roots(frozen);var items=new List<Dictionary<string,object>>();var warnings=new List<string>();
    if(roots.Count==0)warnings.Add("Não há pasta exclusiva registrada e segura. Itens ambíguos serão preservados.");
    foreach(var root in roots)if(Directory.Exists(root))try{SafeAncestors(root);foreach(var entry in Directory.GetFileSystemEntries(root)){
      bool link=Link(entry);var measure=Measure(entry,30000);var c=Candidate(Directory.Exists(entry)?"Pastas":"Arquivos",entry,"high", "Item está na pasta de instalação registrada, sem sobreposição conhecida com outro produto.",B(measure,"personal"),!link&&!B(measure,"incomplete"),D("kind","file","path",entry,"identity",link?"":SafeFs.Identity(entry),"treeDigest",measure["digest"],"root",root));c["size"]=measure["bytes"];if(link)c["reasons"]=new[]{"Reparse point: alvo preservado."};if(B(measure,"incomplete"))c["reasons"]=new[]{"Análise parcial ou link interno: item preservado."};items.Add(c);
    }}catch(Exception e){warnings.Add(root+": "+e.Message);}
    items.AddRange(Resources(roots,deep,warnings));
    string key=S(frozen,"key");if(key!="")try{using(var b=Base(S(frozen,"hive"),Convert.ToInt32(frozen["view"])))using(var k=b.OpenSubKey(key))if(k!=null){items.Add(Candidate("Registro",S(frozen,"hive")+"\\"+key,"high","Entrada de desinstalação exata do produto selecionado, com identidade e valores registrados.",false,true,D("kind","registryKey","hive",S(frozen,"hive"),"view",frozen["view"],"key",key,"digest",Hash(json.Serialize(RegistryBackup(k))))));}}catch{}
    if(deep){string name=S(frozen,"name");if(name!=""&&name.IndexOfAny(Path.GetInvalidFileNameChars())<0)foreach(string basePath in new[]{Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"AppData","LocalLow")}){string possible=Path.Combine(basePath,name);if(Directory.Exists(possible)&&!roots.Any(r=>Under(possible,r)))items.Add(Candidate("Dados pessoais",possible,"low","Somente o nome da pasta coincide. Isso não prova propriedade exclusiva; item preservado.",true,false,D("kind","possible")));}}
    AddTrackedEvidence(frozen,items,warnings);var scan=D("id",ID(),"program",frozen,"roots",roots,"forced",forced,"created",DateTime.UtcNow.ToString("o"),"items",items,"warnings",warnings,"mode",deep?"deep":"normal");scans[S(scan,"id")]=scan;return PublicScan(scan);
  }
  static void AddTrackedEvidence(Dictionary<string,object> p,List<Dictionary<string,object>> items,List<string> warnings){string dir=Path.Combine(store,"monitored");if(!Directory.Exists(dir))return;int used=0;foreach(string file in Directory.GetFiles(dir,"*.json").Take(100))try{var log=json.Deserialize<Dictionary<string,object>>(File.ReadAllText(file));bool same=((IEnumerable)log["programs"]).Cast<Dictionary<string,object>>().Any(a=>S(a,"id")==S(p,"id")&&S(a,"location")==S(p,"location"));if(!same)continue;var paths=new HashSet<string>(((IEnumerable)log["changes"]).Cast<Dictionary<string,object>>().Select(c=>S(c,"path")),StringComparer.OrdinalIgnoreCase);foreach(var c in items)if(paths.Contains(S(c,"path"))){c["reasons"]=((IEnumerable)c["reasons"]).Cast<string>().Concat(new[]{"Também registrado no snapshot desta instalação. Correlação temporal é corroborativa, não prova autoria."}).ToArray();used++;}}catch{}if(used>0)warnings.Add(used+" candidato(s) têm evidência complementar no registro local da instalação monitorada.");}
  static Dictionary<string,object> PublicScan(Dictionary<string,object> scan){var d=new Dictionary<string,object>(scan);d.Remove("roots");d["items"]=((List<Dictionary<string,object>>)scan["items"]).Select(x=>{var p=new Dictionary<string,object>(x);p.Remove("target");return p;}).ToArray();return d;}
  static Dictionary<string,object> RegistryBackup(RegistryKey k){var values=new List<object>();foreach(var n in k.GetValueNames())values.Add(D("name",n,"kind",k.GetValueKind(n).ToString(),"data",k.GetValue(n,null,RegistryValueOptions.DoNotExpandEnvironmentNames)));var children=new Dictionary<string,object>();foreach(var n in k.GetSubKeyNames())using(var child=k.OpenSubKey(n))children[n]=RegistryBackup(child);return D("values",values,"children",children);}
  static object Typed(object data,string kind){if(kind=="Binary")return ((IEnumerable)data).Cast<object>().Select(Convert.ToByte).ToArray();if(kind=="MultiString")return ((IEnumerable)data).Cast<object>().Select(Convert.ToString).ToArray();if(kind=="DWord")return Convert.ToInt32(data);if(kind=="QWord")return Convert.ToInt64(data);return Convert.ToString(data);}
  static void RestoreRegistry(RegistryKey key,Dictionary<string,object> backup){foreach(Dictionary<string,object> v in (IEnumerable)backup["values"]){string n=S(v,"name");if(key.GetValueNames().Contains(n))throw new Exception("Conflito no registro: valor já existe.");key.SetValue(n,Typed(v["data"],S(v,"kind")),(RegistryValueKind)Enum.Parse(typeof(RegistryValueKind),S(v,"kind")));}foreach(var child in (Dictionary<string,object>)backup["children"]){using(var sub=key.CreateSubKey(child.Key))RestoreRegistry(sub,(Dictionary<string,object>)child.Value);}}
  static void Atomic(string path,object value){string temp=path+"."+ID()+".tmp";File.WriteAllText(temp,json.Serialize(value),new UTF8Encoding(false));if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);}
  static Dictionary<string,object> ReadHistory(string id){if(!System.Text.RegularExpressions.Regex.IsMatch(id??"","^[a-f0-9]{32}$"))throw new Exception("ID de histórico inválido.");var dir=Path.Combine(store,id);SafeFs.NoLinks(dir);var h=json.Deserialize<Dictionary<string,object>>(File.ReadAllText(Path.Combine(dir,"journal.json")));bool changed=false;foreach(Dictionary<string,object> r in (IEnumerable)h["records"]){if(S(r,"status")!="planned")continue;var t=(Dictionary<string,object>)r["target"];bool removed=false;if(S(t,"kind")=="file"){string expected=QuarantinePath(S(t,"path"),id,S(r,"id"),false);if(S(r,"quarantine")==expected&&(File.Exists(expected)||Directory.Exists(expected))){SafeFs.NoLinks(expected);removed=true;}}else if(r.ContainsKey("backup")&&(S(t,"kind")=="registryKey"||S(t,"kind")=="registryValue")){using(var b=Base(S(t,"hive"),Convert.ToInt32(t["view"])))using(var k=b.OpenSubKey(S(t,"key")))removed=k==null||S(t,"kind")=="registryValue"&&!k.GetValueNames().Contains(S(t,"value"));}if(removed){r["status"]="removed";r["recoveredJournal"]=true;h["backupAvailable"]=true;changed=true;}}if(changed)Atomic(Path.Combine(dir,"journal.json"),h);return h;}
  static string QuarantinePath(string original,string operation,string candidate,bool create){
    if(!System.Text.RegularExpressions.Regex.IsMatch(operation??"","^[a-f0-9]{32}$")||!System.Text.RegularExpressions.Regex.IsMatch(candidate??"","^[a-f0-9]{32}$"))throw new Exception("ID de backup inválido.");
    string dir=Path.Combine(store,operation);
    if(!Path.GetPathRoot(original).Equals(Path.GetPathRoot(store),StringComparison.OrdinalIgnoreCase)){
      string root=Path.Combine(Path.GetPathRoot(original),"NTC Uninstaller Quarantine");string user=Path.Combine(root,WindowsIdentity.GetCurrent().User.Value);
      if(create){if(Admin){ProtectStore(root);ProtectStore(user);}else{ProtectUserStore(root);ProtectUserStore(user);}}
      dir=Path.Combine(user,operation);if(create)Directory.CreateDirectory(dir);
    }
    if(create)SafeFs.NoLinks(dir);return Path.Combine(dir,candidate);
  }
  static void ProtectUserStore(string dir){SafeFs.NoLinks(dir);var user=WindowsIdentity.GetCurrent().User;var admins=new SecurityIdentifier(WellKnownSidType.BuiltinAdministratorsSid,null);if(Directory.Exists(dir)){var owner=(SecurityIdentifier)Directory.GetAccessControl(dir).GetOwner(typeof(SecurityIdentifier));if(!owner.Equals(user)&&!owner.Equals(admins))throw new Exception("Pasta de quarentena existente tem proprietário não confiável.");}else Directory.CreateDirectory(dir);var acl=new DirectorySecurity();acl.SetOwner(user);acl.SetAccessRuleProtection(true,false);foreach(var sid in new[]{user,admins,new SecurityIdentifier(WellKnownSidType.LocalSystemSid,null)})acl.AddAccessRule(new FileSystemAccessRule(sid,FileSystemRights.FullControl,InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit,PropagationFlags.None,AccessControlType.Allow));Directory.SetAccessControl(dir,acl);}
  static object Clean(string scanId,object[] selected){
    Dictionary<string,object> scan;if(!scans.TryGetValue(scanId,out scan))throw new Exception("Análise expirada. Analise novamente.");var program=(Dictionary<string,object>)scan["program"];if(B(program,"protected"))throw new Exception("Componente protegido.");
    var candidates=(List<Dictionary<string,object>>)scan["items"];var choices=selected.Select(v=>Convert.ToString(v)).Distinct().ToArray();if(choices.Length==0)throw new Exception("Selecione os itens a revisar.");var chosen=choices.Select(id=>candidates.SingleOrDefault(c=>S(c,"id")==id)??throwError("Item fora da análise.")).ToArray();if(chosen.Any(c=>!B(c,"eligible")||S(c,"confidence")=="low"))throw new Exception("Item protegido/ambíguo não pode ser removido.");
    // No removal while the app remains registered unless the explicit forced workflow was approved.
    Inventory(false);if(!B(scan,"forced")&&programs.ContainsKey(S(program,"id")))throw new Exception("O produto ainda está registrado. Conclua o desinstalador ou use a análise forçada confirmada.");
    var roots=(List<string>)scan["roots"];if(roots.Any(r=>Shared(r,S(program,"id"))))throw new Exception("A pasta passou a ser usada por outro programa. Analise novamente.");
    string op=ID(),dir=Path.Combine(store,op);Directory.CreateDirectory(dir);SafeFs.NoLinks(dir);var records=new List<Dictionary<string,object>>();var history=D("id",op,"name",S(program,"name"),"program",program,"date",DateTime.UtcNow.ToString("o"),"records",records,"bytes",0L,"restored",false,"backupAvailable",true,"status","in-progress");string journal=Path.Combine(dir,"journal.json");Atomic(journal,history);long removed=0;
    history["preservedCandidates"]=candidates.Where(c=>!choices.Contains(S(c,"id"))).Select(c=>D("category",c["category"],"path",c["path"],"size",c["size"],"personal",c["personal"],"reasons",c["reasons"])).ToArray();foreach(var c in chosen){var t=(Dictionary<string,object>)c["target"];var record=D("id",S(c,"id"),"category",c["category"],"path",c["path"],"target",t,"personal",c["personal"],"confidence",c["confidence"],"reasons",c["reasons"],"status","planned");records.Add(record);Atomic(journal,history);
      try{
        if(S(t,"kind")=="file"){
          var file=S(t,"path");SafeAncestors(file);if(S(t,"root")!=""&&!roots.Any(r=>Under(file,r)))throw new Exception("Fora da raiz autorizada.");if(S(t,"shortcutTarget")!=""&&!roots.Any(r=>Under(Shortcut(file),r)))throw new Exception("Destino do atalho mudou.");var size=Measure(file,200000);if(B(size,"incomplete"))throw new Exception("Pasta contém links ou entradas inacessíveis. Preservada.");if(S(t,"treeDigest")!=""&&S(size,"digest")!=S(t,"treeDigest"))throw new Exception("Conteúdo mudou desde a análise. Preservado.");string dest=QuarantinePath(file,op,S(c,"id"),true);record["quarantine"]=dest;record["bytes"]=size["bytes"];record["metadata"]=D("attributes",File.GetAttributes(file).ToString(),"created",File.GetCreationTimeUtc(file).ToString("o"),"modified",File.GetLastWriteTimeUtc(file).ToString("o"));Atomic(journal,history);SafeFs.Move(file,dest,S(t,"identity"));removed+=Convert.ToInt64(size["bytes"]);
        }else if(new[]{"service","task","firewall"}.Contains(S(t,"kind"))){RemoveSystem(c,record,roots,()=>Atomic(journal,history));}else{
          string hive=S(t,"hive"),key=S(t,"key");int view=Convert.ToInt32(t["view"]);using(var b=Base(hive,view))using(var k=b.OpenSubKey(key,true)){
            if(k==null)throw new Exception("Entrada já ausente.");if(S(t,"kind")=="registryKey"){
              if(key!=S(program,"key")||hive!=S(program,"hive"))throw new Exception("Somente a entrada exata do produto é permitida.");var backup=RegistryBackup(k);if(Hash(json.Serialize(backup))!=S(t,"digest"))throw new Exception("Entrada mudou. Analise novamente.");record["backup"]=backup;Atomic(journal,history);
            }else{
              var raw=k.GetValue(S(t,"value"),null,RegistryValueOptions.DoNotExpandEnvironmentNames);if(json.Serialize(raw)!=json.Serialize(t["data"])||k.GetValueKind(S(t,"value")).ToString()!=S(t,"valueKind"))throw new Exception("Valor mudou. Preservado.");if(!Related(Convert.ToString(raw),roots)&&!roots.Any(r=>Full(Convert.ToString(raw))==r))throw new Exception("Evidência do valor não confere.");record["backup"]=D("values",new[]{D("name",S(t,"value"),"kind",S(t,"valueKind"),"data",raw)},"children",D());Atomic(journal,history);k.DeleteValue(S(t,"value"),false);
            }
          }
          if(S(t,"kind")=="registryKey")using(var b=Base(hive,view))b.DeleteSubKeyTree(key,false);
        }
        if(S(t,"kind")=="file"&&(File.Exists(S(t,"path"))||Directory.Exists(S(t,"path"))||!File.Exists(S(record,"quarantine"))&&!Directory.Exists(S(record,"quarantine"))))throw new Exception("Não foi possível confirmar a mudança para quarentena.");record["status"]="removed";record["verified"]=true;
      }catch(Exception e){record["status"]="preserved";record["error"]=e.Message;}
      history["bytes"]=removed;Atomic(journal,history);
    }
    history["status"]="complete";history["backupAvailable"]=records.Any(r=>S(r,"status")=="removed");Atomic(journal,history);scans.Remove(scanId);return history;
  }
  static Dictionary<string,object> throwError(string message){throw new Exception(message);}
  static object Restore(string id){
    var h=ReadHistory(id);var dir=Path.Combine(store,id);
    foreach(Dictionary<string,object> r in (IEnumerable)h["records"]){if(S(r,"status")!="removed")continue;try{
      var t=(Dictionary<string,object>)r["target"];
      if(S(t,"kind")=="file"){
        string original=S(t,"path"),backup=S(r,"quarantine");if(!backup.Equals(QuarantinePath(original,id,S(r,"id"),false),StringComparison.OrdinalIgnoreCase))throw new Exception("Backup fora do escopo.");
        if(File.Exists(original)||Directory.Exists(original))throw new Exception("Conflito: caminho original já existe. Não foi sobrescrito.");
        var measure=Measure(backup,200000);if(B(measure,"incomplete")||S(t,"treeDigest")!=""&&S(t,"treeDigest")!=S(measure,"digest"))throw new Exception("O conteúdo em quarentena mudou. Backup preservado para revisão.");SafeAncestors(original);Directory.CreateDirectory(Path.GetDirectoryName(original));SafeFs.Move(backup,original,SafeFs.Identity(backup));
      }else if(new[]{"service","task","firewall"}.Contains(S(t,"kind"))){RestoreSystem(r);
      }else{using(var b=Base(S(t,"hive"),Convert.ToInt32(t["view"]))){
        string key=S(t,"key");using(var existing=b.OpenSubKey(key)){if(S(t,"kind")=="registryKey"&&existing!=null)throw new Exception("Conflito: chave original já existe.");if(S(t,"kind")=="registryValue"&&existing!=null&&existing.GetValueNames().Contains(S(t,"value")))throw new Exception("Conflito: valor original já existe.");}
        using(var k=b.CreateSubKey(key))RestoreRegistry(k,(Dictionary<string,object>)r["backup"]);
      }}r["status"]="restored";r.Remove("error");
    }catch(Exception e){r["error"]=e.Message;}Atomic(Path.Combine(dir,"journal.json"),h);}
    h["restored"]=((IEnumerable)h["records"]).Cast<Dictionary<string,object>>().All(r=>S(r,"status")!="removed");h["backupAvailable"]=!B(h,"restored");Atomic(Path.Combine(dir,"journal.json"),h);return h;
  }
  static object History(){var list=new List<object>();foreach(var dir in Directory.GetDirectories(store))try{var id=Path.GetFileName(dir);if(!System.Text.RegularExpressions.Regex.IsMatch(id,"^[a-f0-9]{32}$"))continue;var h=ReadHistory(id);var summary=new Dictionary<string,object>(h);summary.Remove("program");list.Add(summary);}catch{}return list.OrderByDescending(x=>S((Dictionary<string,object>)x,"date")).ToArray();}
  static object Uninstall(Dictionary<string,object> p,bool quiet){
    if(B(p,"protected"))throw new Exception("Componente protegido.");if(S(p,"type")=="MSIX/AppX"){var result=Bridge("removeAppx",D("package",S(p,"package")));string op=ID(),dir=Path.Combine(store,op);Directory.CreateDirectory(dir);Atomic(Path.Combine(dir,"journal.json"),D("id",op,"name",S(p,"name"),"program",p,"date",DateTime.UtcNow.ToString("o"),"records",new object[0],"bytes",0,"status","official-uninstaller","backupAvailable",false,"result",result));return result;}
    string id=S(p,"id"),fingerprint=S(p,"fingerprint");Inventory(false);var current=ProgramBy(id);if(S(current,"fingerprint")!=fingerprint)throw new Exception("O registro do produto mudou. Atualize a lista.");
    var args=S(p,"productCode")!=""?new[]{Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),"msiexec.exe"),"/x",S(p,"productCode"),"/norestart",quiet?"/qn":"/qf"}:ValidExe(quiet&&S(p,"quiet")!=""||S(p,"command")==""?S(p,"quiet"):S(p,"command"));
    var start=new ProcessStartInfo(args[0],string.Join(" ",args.Skip(1).Select(Quote))){UseShellExecute=S(p,"productCode")==""};
    // Only the registered uninstaller is elevated; cleanup itself requires a separately authenticated host.
    if(S(p,"hive")=="HKLM"&&!Admin){start.UseShellExecute=true;start.Verb="runas";}
    using(var proc=Process.Start(start)){proc.WaitForExit();int exit=proc.ExitCode;Inventory(false);bool still=programs.ContainsKey(id);var result=D("exitCode",exit,"rebootRequired",exit==3010||exit==1641,"stillRegistered",still,"completed",!still&&new[]{0,3010,1641}.Contains(exit),"message",still?"O produto ainda está registrado. O desinstalador pode ter iniciado outro processo; confirme a conclusão e atualize antes da limpeza.":"O registro do produto não está mais presente.");
      if(!still)result["scan"]=Analyze(p,true,false);
      string op=ID(),dir=Path.Combine(store,op);Directory.CreateDirectory(dir);Atomic(Path.Combine(dir,"journal.json"),D("id",op,"name",S(p,"name"),"program",p,"date",DateTime.UtcNow.ToString("o"),"records",new object[0],"bytes",0,"status","official-uninstaller","backupAvailable",false,"result",result.Where(kv=>kv.Key!="scan").ToDictionary(kv=>kv.Key,kv=>kv.Value)));return result;}
  }
  static Dictionary<string,object> Bridge(string action,object input){var script=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"uninstaller-windows.ps1");if(!File.Exists(script))throw new Exception("Ponte Windows ausente no pacote.");string ps=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows),"System32","WindowsPowerShell","v1.0","powershell.exe");var start=new ProcessStartInfo(ps,"-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "+Quote(script)+" -Action "+action){UseShellExecute=false,RedirectStandardInput=true,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true,StandardOutputEncoding=Encoding.UTF8};using(var proc=Process.Start(start)){proc.StandardInput.Write(json.Serialize(input));proc.StandardInput.Close();var errorTask=proc.StandardError.ReadToEndAsync();string output=proc.StandardOutput.ReadToEnd();proc.WaitForExit();var d=json.Deserialize<Dictionary<string,object>>(output);if(proc.ExitCode!=0||d.ContainsKey("error"))throw new Exception(S(d,"error")!=""?S(d,"error"):errorTask.Result);return d;}}
  [DllImport("user32.dll")]static extern bool GetCursorPos(out POINT point);
  [DllImport("user32.dll")]static extern IntPtr WindowFromPoint(POINT point);
  [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr window,out uint pid);
  struct POINT{public int X,Y;}
  static object Processes(List<string> roots){var list=new List<object>();foreach(var proc in Process.GetProcesses())try{string file=proc.MainModule.FileName;if(roots.Any(r=>Under(file,r)))list.Add(D("pid",proc.Id,"path",file,"name",proc.ProcessName,"started",proc.StartTime.ToUniversalTime().ToString("o")));}catch{}return list;}
  static object Identify(string file){file=Full(file);if(file.EndsWith(".lnk",StringComparison.OrdinalIgnoreCase))file=Full(Shortcut(file));return D("path",file,"matches",programs.Values.Where(p=>S(p,"location")!=""&&Under(file,S(p,"location"))).Select(p=>S(p,"id")).ToArray());}
  static Dictionary<string,object> Snapshot(){Inventory(false);var files=new Dictionary<string,object>();var warnings=new List<string>();int budget=60000;var roots=programs.Values.SelectMany(p=>Roots(p)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(r=>r,StringComparer.OrdinalIgnoreCase).ToList();var partialRoots=new List<string>();for(int index=0;index<roots.Count;index++){string root=roots[index];int allowance=Math.Max(1,budget/(roots.Count-index));var observed=SafeFiles(root,"*",allowance).ToArray();if(observed.Length>=allowance)partialRoots.Add(root);foreach(var f in observed)try{var i=new FileInfo(f);files[f]=i.Length+"|"+i.LastWriteTimeUtc.Ticks;budget--;}catch{}}if(partialRoots.Count>0)warnings.Add("Snapshot de arquivos parcial em "+partialRoots.Count+" pasta(s): limite distribuído entre as instalações. Não há varredura de toda a unidade.");var resources=new Dictionary<string,object>();foreach(var c in Resources(roots,true,warnings))resources[S(c,"category")+"|"+S(c,"path")]=json.Serialize(c["target"]);var apps=programs.Values.Select(p=>json.Deserialize<Dictionary<string,object>>(json.Serialize(p))).ToArray();var s=D("id",ID(),"created",DateTime.UtcNow.ToString("o"),"programs",apps,"files",files,"resources",resources,"partialRoots",partialRoots,"warnings",warnings);snapshots[S(s,"id")]=s;Directory.CreateDirectory(Path.Combine(store,"snapshots"));Atomic(Path.Combine(store,"snapshots",S(s,"id")+".json"),s);return s;}
  static object Compare(string before,string after){Dictionary<string,object> a,b;if(!snapshots.TryGetValue(before,out a)||!snapshots.TryGetValue(after,out b))throw new Exception("Snapshot não disponível nesta sessão.");if(before==after)throw new Exception("Escolha dois snapshots diferentes.");var appsA=((IEnumerable)a["programs"]).Cast<Dictionary<string,object>>().ToDictionary(p=>S(p,"id"));var appsB=((IEnumerable)b["programs"]).Cast<Dictionary<string,object>>().ToArray();var newApps=appsB.Where(p=>!appsA.ContainsKey(S(p,"id"))).ToArray();var fa=(Dictionary<string,object>)a["files"];var fb=(Dictionary<string,object>)b["files"];var changes=fb.Where(kv=>!fa.ContainsKey(kv.Key)||SValue(fa[kv.Key])!=SValue(kv.Value)).Select(kv=>D("path",kv.Key,"change",fa.ContainsKey(kv.Key)?"modified":"created","confidence",newApps.Any(p=>Roots(p).Any(r=>Under(kv.Key,r)))?"medium":"low","reason","Diferença de snapshots; correlação temporal não prova qual processo criou o arquivo." )).ToArray();var ra=a.ContainsKey("resources")?(Dictionary<string,object>)a["resources"]:D();var rb=b.ContainsKey("resources")?(Dictionary<string,object>)b["resources"]:D();var resourceChanges=rb.Where(kv=>!ra.ContainsKey(kv.Key)||SValue(ra[kv.Key])!=SValue(kv.Value)).Select(kv=>D("path",kv.Key,"change",ra.ContainsKey(kv.Key)?"modified":"created","confidence","medium","reason","Recurso aponta a diretório registrado; snapshot não prova autoria." )).ToArray();return D("id",ID(),"before",before,"after",after,"programs",newApps,"changes",changes,"resourceChanges",resourceChanges,"warnings",new[]{"Não há atribuição por processo/ETW. Ruído permanece não atribuído e não é usado sozinho para remoção."});}
  static string SValue(object o){return Convert.ToString(o);}
  static object Dispatch(string action,Dictionary<string,object> request){
    switch(action){
      case "list":return Inventory(false);
      case "appx":return Inventory(true);
      case "health":return D("admin",Admin,"helper",AppDomain.CurrentDomain.BaseDirectory,"bridge",File.Exists(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"uninstaller-windows.ps1")),"protocol",1);
      case "icon":return WindowsProgramIcon.Read(ProgramBy(S(request,"id")));
      case "estimate":{var roots=Roots(ProgramBy(S(request,"id")));long bytes=0;bool partial=false;foreach(var r in roots){var measure=Measure(r,200000);bytes+=Convert.ToInt64(measure["bytes"]);partial|=B(measure,"incomplete");}return D("bytes",roots.Count==0?null:(object)bytes,"estimated",true,"partial",partial,"roots",roots);}
      case "metadata":{var p=ProgramBy(S(request,"id"));var command=S(p,"command")!=""?S(p,"command"):S(p,"quiet");var exe=ValidExe(command)[0];return D("path",exe,"role","Desinstalador registrado","company",FileVersionInfo.GetVersionInfo(exe).CompanyName,"signature",WindowsSignature.Check(exe));}
      case "analyze":return Analyze(ProgramBy(S(request,"id")),B(request,"deep"),B(request,"forced"));
      case "uninstall":{var p=ProgramBy(S(request,"id"));if(S(p,"type")!="MSIX/AppX"&&S(p,"fingerprint")!=S(request,"fingerprint"))throw new Exception("Identidade do produto mudou desde a confirmação. Atualize a lista.");return Uninstall(p,B(request,"quiet"));}
      case "clean":return Clean(S(request,"scanId"),((request["ids"] as IEnumerable)??new object[0]).Cast<object>().ToArray());
      case "history":return History();
      case "historyAnalyze":{var h=ReadHistory(S(request,"id"));var p=(Dictionary<string,object>)h["program"];Inventory(false);if(programs.ContainsKey(S(p,"id")))throw new Exception("O programa está novamente registrado. Use a lista atual.");return Analyze(p,true,false);}
      case "snapshots":return snapshots.Values.Select(s=>D("id",s["id"],"created",s["created"],"warnings",s["warnings"])).OrderByDescending(s=>S(s,"created")).ToArray();
      case "tracked":return Directory.Exists(Path.Combine(store,"monitored"))?Directory.GetFiles(Path.Combine(store,"monitored"),"*.json").Select(f=>json.DeserializeObject(File.ReadAllText(f))).ToArray():new object[0];
      case "restore":return Restore(S(request,"id"));
      case "purge":{string id=S(request,"id");var history=ReadHistory(id);var cross=new HashSet<string>();foreach(Dictionary<string,object> record in (IEnumerable)history["records"]){var target=(Dictionary<string,object>)record["target"];if(S(target,"kind")=="file"&&S(record,"quarantine")!=""){string expected=QuarantinePath(S(target,"path"),id,S(record,"id"),false);if(S(record,"quarantine")!=expected)throw new Exception("Destino de backup inválido.");var location=Path.GetDirectoryName(expected);if(location!=Path.Combine(store,id))cross.Add(location);}}foreach(string crossDir in cross)if(Directory.Exists(crossDir))SafeFs.DeleteBackup(crossDir,Path.GetDirectoryName(crossDir));var dir=Path.Combine(store,id);SafeFs.DeleteBackup(dir,store);return D("deleted",true);}
      case "processes":return Processes(Roots(ProgramBy(S(request,"id"))));
      case "closeProcesses":{var p=ProgramBy(S(request,"id"));var roots=Roots(p);var result=new List<object>();foreach(Dictionary<string,object> found in (IEnumerable)Processes(roots))try{using(var proc=Process.GetProcessById(Convert.ToInt32(found["pid"]))){if(!roots.Any(r=>Under(proc.MainModule.FileName,r)))continue;bool sent=proc.CloseMainWindow();if(sent)proc.WaitForExit(3000);if(!proc.HasExited&&B(request,"force"))proc.Kill();result.Add(D("pid",proc.Id,"closed",proc.HasExited));}}catch{}return result;}
      case "identify":return Identify(S(request,"path"));
      case "forcedTarget":{var file=Full(S(request,"path"));if(file.EndsWith(".lnk",StringComparison.OrdinalIgnoreCase))file=Full(Shortcut(file));var root=Directory.Exists(file)?file:Path.GetDirectoryName(file);SafeAncestors(root);if(Shared(root,""))throw new Exception("Há uma instalação registrada nesse local. Selecione-a na lista.");var p=D("id","forced:"+ID(),"name",Path.GetFileName(root),"location",root,"type","Alvo manual","protected",false,"source","Pasta explicitamente escolhida; propriedade não comprovada");programs[S(p,"id")]=p;var visible=Analyze(p,B(request,"deep"),true);var internalScan=scans[S(visible,"id")];foreach(var c in (List<Dictionary<string,object>>)internalScan["items"]){if(S(c,"confidence")!="low")c["confidence"]="medium";c["selected"]=false;c["reasons"]=((IEnumerable)c["reasons"]).Cast<string>().Concat(new[]{"Alvo manual: localização escolhida pelo usuário, sem prova de instalação exclusiva."}).ToArray();}return PublicScan(internalScan);}
      case "hunter":{System.Threading.Thread.Sleep(5000);POINT point;GetCursorPos(out point);uint pid;GetWindowThreadProcessId(WindowFromPoint(point),out pid);using(var proc=Process.GetProcessById((int)pid))return Identify(proc.MainModule.FileName);}
      case "restorePoint":return Bridge("restorePoint",D());
      case "snapshot":{var s=Snapshot();var summary=new Dictionary<string,object>(s);summary.Remove("files");summary.Remove("resources");return summary;}
      case "compare":return Compare(S(request,"before"),S(request,"after"));
      case "pick":{string file=Full(S(request,"path"));if(file==""||!File.Exists(file)||(!file.EndsWith(".exe",StringComparison.OrdinalIgnoreCase)&&!file.EndsWith(".msi",StringComparison.OrdinalIgnoreCase)))throw new Exception("Selecione um instalador EXE/MSI.");string id=ID();picked[id]=file;pickedIdentity[id]=SafeFs.Identity(file);return D("id",id,"path",file);}
      case "monitorStart":{string file;string id=S(request,"id");if(!picked.TryGetValue(id,out file))throw new Exception("Instalador não autorizado.");var baseline=Snapshot();if(SafeFs.Identity(file)!=pickedIdentity[id])throw new Exception("O instalador mudou desde a seleção.");var args=file.EndsWith(".msi",StringComparison.OrdinalIgnoreCase)?new[]{Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),"msiexec.exe"),"/i",file,"/norestart"}:new[]{file};var proc=Process.Start(new ProcessStartInfo(args[0],string.Join(" ",args.Skip(1).Select(Quote))){UseShellExecute=true});var m=D("id",ID(),"before",S(baseline,"id"),"installer",file,"pid",proc.Id,"started",DateTime.UtcNow.ToString("o"));monitors[S(m,"id")]=m;picked.Remove(id);pickedIdentity.Remove(id);return m;}
      case "monitorFinish":{Dictionary<string,object> m;if(!monitors.TryGetValue(S(request,"id"),out m))throw new Exception("Monitoramento ausente.");try{if(!Process.GetProcessById(Convert.ToInt32(m["pid"])).HasExited)throw new Exception("O instalador ainda está em execução. Aguarde a conclusão.");}catch(ArgumentException){}var final=Snapshot();var result=(Dictionary<string,object>)Compare(S(m,"before"),S(final,"id"));result["installer"]=m["installer"];result["date"]=DateTime.UtcNow.ToString("o");Directory.CreateDirectory(Path.Combine(store,"monitored"));Atomic(Path.Combine(store,"monitored",S(result,"id")+".json"),result);monitors.Remove(S(m,"id"));return result;}
      default:throw new Exception("Operação não permitida.");
    }
  }
  [DllImport("kernel32.dll",SetLastError=true)]static extern bool GetNamedPipeClientProcessId(SafePipeHandle pipe,out uint pid);
  static void Main(string[] args){
    Console.InputEncoding=new UTF8Encoding(false);Console.OutputEncoding=new UTF8Encoding(false);
    try{
      if(args.Length!=1&&args.Length!=5)throw new Exception("Argumentos inválidos.");store=Full(args[0]);if(store==""||!store.EndsWith("\\uninstaller",StringComparison.OrdinalIgnoreCase)||!Under(store,Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData))&&!Under(store,Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)))throw new Exception("Armazenamento fora do AppData.");Directory.CreateDirectory(store);SafeFs.NoLinks(store);
      LoadSnapshots();
      if(args.Length==5){if(!Admin||args[1]!="--pipe"||args[3]!="--pid"||!System.Text.RegularExpressions.Regex.IsMatch(args[2],"^ntc-uninstaller-[a-f0-9]{64}$"))throw new Exception("Canal inválido.");int parent=int.Parse(args[4]);string protectedRoot=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),"NTC Utilities Uninstaller Backups");ProtectStore(protectedRoot);store=Path.Combine(protectedRoot,WindowsIdentity.GetCurrent().User.Value);ProtectStore(store);LoadSnapshots();var security=new PipeSecurity();security.AddAccessRule(new PipeAccessRule(WindowsIdentity.GetCurrent().User,PipeAccessRights.ReadWrite,AccessControlType.Allow));using(var pipe=new NamedPipeServerStream(args[2],PipeDirection.InOut,1,PipeTransmissionMode.Byte,PipeOptions.None,65536,65536,security)){pipe.WaitForConnection();uint pid;if(!GetNamedPipeClientProcessId(pipe.SafePipeHandle,out pid)||pid!=parent)throw new Exception("Cliente não autorizado.");using(var reader=new StreamReader(pipe,new UTF8Encoding(false)))using(var writer=new StreamWriter(pipe,new UTF8Encoding(false))){writer.AutoFlush=true;Serve(reader,writer);}}}
      else Serve(Console.In,Console.Out);
    }catch(Exception e){Console.Error.WriteLine(e.Message);Environment.ExitCode=1;}
  }
  static void ProtectStore(string dir){SafeFs.NoLinks(dir);var admins=new SecurityIdentifier(WellKnownSidType.BuiltinAdministratorsSid,null);var system=new SecurityIdentifier(WellKnownSidType.LocalSystemSid,null);if(Directory.Exists(dir)){var acl=Directory.GetAccessControl(dir);var owner=(SecurityIdentifier)acl.GetOwner(typeof(SecurityIdentifier));if(!owner.Equals(admins)&&!owner.Equals(system))throw new Exception("Pasta de backups elevados existente não tem proprietário confiável. Operação bloqueada.");}else Directory.CreateDirectory(dir);var security=new DirectorySecurity();security.SetOwner(admins);security.SetAccessRuleProtection(true,false);foreach(var sid in new[]{admins,system})security.AddAccessRule(new FileSystemAccessRule(sid,FileSystemRights.FullControl,InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit,PropagationFlags.None,AccessControlType.Allow));Directory.SetAccessControl(dir,security);}
  static void LoadSnapshots(){snapshots.Clear();string dir=Path.Combine(store,"snapshots");if(!Directory.Exists(dir))return;SafeFs.NoLinks(dir);foreach(var f in Directory.GetFiles(dir,"*.json"))try{var s=json.Deserialize<Dictionary<string,object>>(File.ReadAllText(f));snapshots[S(s,"id")]=s;}catch{}}
  static void Serve(TextReader reader,TextWriter writer){string line;while((line=reader.ReadLine())!=null){object seq=null;try{if(line.Length>1024*1024)throw new Exception("Pedido grande demais.");var r=json.Deserialize<Dictionary<string,object>>(line);seq=r["seq"];var payload=(Dictionary<string,object>)r["payload"];var result=Dispatch(S(r,"action"),payload);writer.WriteLine(json.Serialize(D("seq",seq,"result",result)));}catch(Exception e){writer.WriteLine(json.Serialize(D("seq",seq,"error",e.Message)));}}}
}

// Explicit INetFwRule3 IDispatch contract; an INetFwRule enumerator does not expose these extended names dynamically.
[ComImport,Guid("B21563FF-D696-4222-AB46-4E89B73AB34A"),InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
interface IFirewallAdvanced {
  [DispId(12)]object Interfaces{get;}
  [DispId(19)]int EdgeTraversalOptions{get;}
  [DispId(20)]string LocalAppPackageId{get;}
  [DispId(21)]string LocalUserOwner{get;}
  [DispId(22)]string LocalUserAuthorizedList{get;}
  [DispId(23)]string RemoteUserAuthorizedList{get;}
  [DispId(24)]string RemoteMachineAuthorizedList{get;}
  [DispId(25)]int SecureFlags{get;}
}
static class WindowsSignature {
  [StructLayout(LayoutKind.Sequential)]struct FILEINFO{public uint size;public IntPtr name,file,subject;}
  [StructLayout(LayoutKind.Sequential)]struct DATA{public uint size;public IntPtr callback,sip;public uint ui,revoke,choice;public IntPtr file;public uint action;public IntPtr state,url;public uint flags,context;public IntPtr settings;}
  [DllImport("wintrust.dll",ExactSpelling=true)]static extern int WinVerifyTrust(IntPtr window,ref Guid action,ref DATA data);
  public static object Check(string file){var action=new Guid("00AAC56B-CD44-11d0-8CC2-00C04FC295EE");IntPtr name=Marshal.StringToCoTaskMemUni(file);var info=new FILEINFO{size=(uint)Marshal.SizeOf(typeof(FILEINFO)),name=name};IntPtr ptr=Marshal.AllocHGlobal(Marshal.SizeOf(typeof(FILEINFO)));Marshal.StructureToPtr(info,ptr,false);var data=new DATA{size=(uint)Marshal.SizeOf(typeof(DATA)),ui=2,choice=1,file=ptr,action=1,flags=0x1000|0x2000};int result;try{result=WinVerifyTrust(new IntPtr(-1),ref action,ref data);}finally{data.action=2;WinVerifyTrust(new IntPtr(-1),ref action,ref data);Marshal.FreeHGlobal(ptr);Marshal.FreeCoTaskMem(name);}string signer="";try{using(var cert=new System.Security.Cryptography.X509Certificates.X509Certificate2(System.Security.Cryptography.X509Certificates.X509Certificate.CreateFromSignedFile(file)))signer=cert.GetNameInfo(System.Security.Cryptography.X509Certificates.X509NameType.SimpleName,false);}catch{}return new Dictionary<string,object>{{"verified",result==0},{"status",result==0?"Confirmada pelo cache local":"Não confirmada localmente"},{"signer",signer},{"code",result.ToString("X8")},{"offline",true}};}
}

static class SafeService {
  [DllImport("advapi32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern IntPtr OpenSCManager(string machine,string database,uint access);
  [DllImport("advapi32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern IntPtr OpenService(IntPtr manager,string name,uint access);
  [DllImport("advapi32.dll",SetLastError=true)]static extern bool DeleteService(IntPtr service);
  [DllImport("advapi32.dll")]static extern bool CloseServiceHandle(IntPtr handle);
  [DllImport("advapi32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern IntPtr CreateService(IntPtr manager,string name,string display,uint access,uint type,uint start,uint error,string binary,string group,IntPtr tag,string dependencies,string account,string password);
  [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]struct DESCRIPTION{[MarshalAs(UnmanagedType.LPWStr)]public string text;}
  [DllImport("advapi32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool ChangeServiceConfig2(IntPtr service,uint info,ref DESCRIPTION description);
  public static void Delete(string name){IntPtr m=OpenSCManager(null,null,1);if(m==IntPtr.Zero)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());try{IntPtr s=OpenService(m,name,0x10000);if(s==IntPtr.Zero)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());try{if(!DeleteService(s))throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());}finally{CloseServiceHandle(s);}}finally{CloseServiceHandle(m);}}
  public static void Create(string name,Dictionary<string,object> values){if(Convert.ToInt32(values["Type"])!=16||Convert.ToString(values["ObjectName"])!="LocalSystem")throw new Exception("Configuração de serviço não suportada para restauração.");IntPtr m=OpenSCManager(null,null,2);if(m==IntPtr.Zero)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());try{IntPtr s=CreateService(m,name,values.ContainsKey("DisplayName")?Convert.ToString(values["DisplayName"]):name,0x10003,16,Convert.ToUInt32(values["Start"]),Convert.ToUInt32(values["ErrorControl"]),Convert.ToString(values["ImagePath"]),null,IntPtr.Zero,null,"LocalSystem",null);if(s==IntPtr.Zero)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());try{if(values.ContainsKey("Description")){var description=new DESCRIPTION{text=Convert.ToString(values["Description"])};if(!ChangeServiceConfig2(s,1,ref description)){int error=Marshal.GetLastWin32Error();DeleteService(s);throw new System.ComponentModel.Win32Exception(error);}}}finally{CloseServiceHandle(s);}}finally{CloseServiceHandle(m);}}
}

// Handle-based same-volume rename; ancestor handles prevent directory substitution during mutation.
static class SafeFs {
  [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern SafeFileHandle CreateFile(string file,uint access,uint share,IntPtr security,uint disposition,uint flags,IntPtr template);
  [DllImport("kernel32.dll",SetLastError=true)]static extern bool GetFileInformationByHandle(SafeFileHandle file,out INFO info);
  [DllImport("kernel32.dll",SetLastError=true)]static extern bool SetFileInformationByHandle(SafeFileHandle file,int cls,IntPtr data,uint size);
  [StructLayout(LayoutKind.Sequential)]struct INFO{public uint attributes;public System.Runtime.InteropServices.ComTypes.FILETIME creation,access,write;public uint volume,sizeHigh,sizeLow,links,indexHigh,indexLow;}
  static SafeFileHandle Open(string p,bool rename){var h=CreateFile(p,rename?0x10000u|0x80u:0x80u,3,IntPtr.Zero,3,0x2000000u|0x200000u,IntPtr.Zero);if(h.IsInvalid)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());INFO i;if(!GetFileInformationByHandle(h,out i)){h.Dispose();throw new Exception("Não foi possível ler a identidade do arquivo.");}if((i.attributes&0x400)!=0){h.Dispose();throw new Exception("Reparse point: operação recusada.");}return h;}
  public static string Identity(string p){using(var h=Open(p,false)){INFO i;GetFileInformationByHandle(h,out i);return i.volume+":"+i.indexHigh+":"+i.indexLow+":"+i.sizeHigh+":"+i.sizeLow+":"+i.write.dwHighDateTime+":"+i.write.dwLowDateTime;}}
  public static void NoLinks(string p){while(!string.IsNullOrEmpty(p)&&p.Length>3){if(File.Exists(p)||Directory.Exists(p))using(var h=Open(p,false)){}p=Path.GetDirectoryName(p);}}
  static void TreeSafe(string p){if((File.GetAttributes(p)&FileAttributes.ReparsePoint)!=0)throw new Exception("Link interno preservado.");if(Directory.Exists(p))foreach(var q in Directory.GetFileSystemEntries(p))TreeSafe(q);}
  public static void Move(string source,string destination,string expected){
    if(!Path.GetPathRoot(source).Equals(Path.GetPathRoot(destination),StringComparison.OrdinalIgnoreCase))throw new Exception("Quarentena em outra unidade: mova este item manualmente ou preserve-o. Não será copiado silenciosamente.");
    var locks=new List<SafeFileHandle>();try{
      foreach(var path in new[]{Path.GetDirectoryName(source),Path.GetDirectoryName(destination)}){var p=path;while(p!=null&&p.Length>3){locks.Add(Open(p,false));p=Path.GetDirectoryName(p);}}
      TreeSafe(source);if(Identity(source)!=expected)throw new Exception("O arquivo/pasta mudou desde a análise. Analise novamente.");
      using(var h=Open(source,true)){
        INFO i;GetFileInformationByHandle(h,out i);if((i.attributes&0x10)==0&&i.links>1)throw new Exception("Arquivo com hard links: preservado.");
        if(File.Exists(destination)||Directory.Exists(destination))throw new Exception("Destino já existe. Não será sobrescrito.");
        byte[] name=Encoding.Unicode.GetBytes(Path.GetFullPath(destination));int offset=IntPtr.Size==8?20:12;int length=offset+name.Length+8;IntPtr data=Marshal.AllocHGlobal(length);try{for(int n=0;n<length;n++)Marshal.WriteByte(data,n,0);Marshal.WriteInt32(data,offset-4,name.Length);Marshal.Copy(name,0,IntPtr.Add(data,offset),name.Length);if(!SetFileInformationByHandle(h,3,data,(uint)length))throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());}finally{Marshal.FreeHGlobal(data);}
      }
      if(!File.Exists(destination)&&!Directory.Exists(destination)||Identity(destination)!=expected)throw new Exception("Não foi possível confirmar o destino e a identidade após a movimentação.");
    }finally{foreach(var h in locks)h.Dispose();}
  }
  public static void DeleteBackup(string dir,string root){if(Path.GetDirectoryName(dir)!=root||!System.Text.RegularExpressions.Regex.IsMatch(Path.GetFileName(dir),"^[a-f0-9]{32}$"))throw new Exception("Backup fora do escopo.");NoLinks(dir);TreeSafe(dir);Directory.Delete(dir,true);}
}
